### ISSUE TITLE
getting started codelab part 6 document improvements.

### ISSUE THREAD

**Issue by Berttwm** [rachel-fenichel/blockly-samples#1034]
Some documentation improvements for **Part 6 (Creating a custom block)**, this particular part can be appended with additional details as explained below.

![image](https://user-images.githubusercontent.com/44689249/156294409-8274112f-5e1a-4113-b19b-3166a279de77.png)

It is important to also add the `<script src="scripts/sound_blocks.js"></script>` before  `<script src="scripts/main.js"></script>` as doing otherwise will not even show the "play" box as intended. I was stuck on this issue until I took a look at the `./complete-code/` folder

**Comment by jubishop** [comment]
I believe this is fixed by https://github.com/google/blockly-samples/commit/eade01201c542e30652ea191dae116ea2c0321e2
