### ISSUE TITLE
Plane demo doesn't show translations

### ISSUE THREAD

**Issue by BeksOmega** [rachel-fenichel/blockly-samples#1065]
**Category**

 - Examples

**Component**

Plane demo

**Describe the bug**

Translations are not being de-referenced, presumably because Blockly is loading before the translations are loading. This is bad because it's kinda the whole point of the demo.

**To Reproduce**

1. Open the plane demo.
2. Observe how things are not localized.

**Expected behavior**

Things should be localized

**Additional context**

Related to google/blockly-samples#1094

**Comment by maribethb** [comment]
The demo is working as expected now, this was probably related to the message loading issues linked above.
