### ISSUE TITLE
High contrast theme used serif-ed font (default)

### ISSUE THREAD

**Issue by BeksOmega** [rachel-fenichel/blockly-samples#1068]
**Describe the bug**

When you switch to the high contrast theme, all of Blockly's text becomes serif-ed. 

**To Reproduce**

1. Go to the advanced playground. 
2. Switch to the high contrast theme
3. Observe how the text of the blocks becomes serif-ed.

**Expected behavior**

Blocks should have Blockly's standard san-serif font.

**Screenshots**
![image](https://user-images.githubusercontent.com/25440652/159978347-f905a720-babc-4688-b073-1e96994602e4.png)

**Comment by BeksOmega** [comment]
![image](https://user-images.githubusercontent.com/25440652/159979438-110592a1-284a-4bc7-a5d8-0a849846b14f.png)

I think this is also causing the text measurement to break.

**Comment by BeksOmega** [comment]
Also causes the demo text to look different than the text for the other themes.

**Comment by BeksOmega** [comment]
@alschmiedt to confirm this is a bug

**Comment by alschmiedt** [comment]
If this is still happening then yes it is a bug. However, I just pulled samples and am having trouble reproducing so it might have been fixed already.

**Comment by BeksOmega** [comment]
Also cannot reproduce. Closing as fixed.
