### ISSUE TITLE
Review examples with latest version of Blockly

### ISSUE THREAD

**Issue by BeksOmega** [rachel-fenichel/blockly-samples#1076]
**Category**

 - Examples

**Component**

All components.

**Description**

Review all of the examples that do not have a peer dependency of `<something> - 8` to ensure that they work with version 8. Then update their peer dependencies.

**Comment by maribethb** [comment]
also since they are examples of using blockly with other frameworks my vote would be that we only make them compatible with v8, no need to model older versions of blockly since we don't really want people choosing to use v3 for example.

**Comment by gonfunko** [comment]
All examples have been updated to v9.
