### ISSUE TITLE
Getting Started with Blockly, Step 6 breaks the functionality when I add in the "play" block

### ISSUE THREAD

**Issue by sabrams61** [rachel-fenichel/blockly-samples#1117]
When I add the code for the "play" block to index.html:

`<block type="play_sound"></block>`

from sound_blocks.js:

```
Blockly.defineBlocksWithJsonArray([
  {
    "type": "play_sound",
    "message0": "Play %1",
    "args0": [
      {
        "type": "field_dropdown",
        "name": "VALUE",
        "options": [
          ["C4", "sounds/c4.m4a"],
          ["D4", "sounds/d4.m4a"],
          ["E4", "sounds/e4.m4a"],
          ["F4", "sounds/f4.m4a"],
          ["G4", "sounds/g4.m4a"]
        ]
      }
    ],
    "previousStatement": null,
    "nextStatement": null,
    "colour": 355
  }
]);
```

And added js code to main.js:

```
enableMakerMode();

  Blockly.inject('blocklyDiv', {
    toolbox: document.getElementById('toolbox'),
    scrollbars: false
});
```

When I go to edit, the green "repeat" block no longer works, and there's no "play" block added to the page. I've tried redoing this a number of times and it doesn't change.

Console error message:

```
Uncaught TypeError: Invalid block definition for type: play_sound
    at BlockSvg.Block (blockly:973:380)
    at new BlockSvg (blockly:1072:280)
    at WorkspaceSvg.module$exports$Blockly$WorkspaceSvg.WorkspaceSvg.newBlock (blockly:1199:90)
    at module$contents$Blockly$Xml_domToBlockHeadless (blockly:245:286)
    at $.module$exports$Blockly$Xml.domToBlock (blockly:236:280)
    at VerticalFlyout.module$exports$Blockly$Flyout.Flyout.createFlyoutBlock_ (blockly:1293:292)
    at VerticalFlyout.module$exports$Blockly$Flyout.Flyout.createFlyoutInfo_ (blockly:1289:423)
    at VerticalFlyout.module$exports$Blockly$Flyout.Flyout.show (blockly:1287:300)
    at module$contents$Blockly$inject_init (blockly:1265:232)
    at Object.inject (blockly:1260:284)
```

<img width="498" alt="Screen Shot 2022-04-19 at 10 19 39 AM" src="https://user-images.githubusercontent.com/69314688/164025424-526f9f62-b23d-43d8-8704-5cf5fead18d0.png">

**Comment by sabrams61** [comment]
One problem I noticed is that in blockly-samples/examples/getting-started-codelab/starter-code/index.html, there's a missing `</main>` end tag.

**Comment by sabrams61** [comment]
FYI, I cloned the repository from GitHub.

**Comment by sabrams61** [comment]
I think I found the error. In your instructions, you say when you add this line:

`<script src="scripts/sound_blocks.js"></script>`

Your block definitions must **come after importing Blocky**, since you will use Blockly functions in this file.

However, it also needs to come before:

`<script src="scripts/main.js"></script>`

Initially I added the line to the end of all links to JS files. When I moved the link to sound_blocks.js above the link to main.js, it started working.

**Comment by gonfunko** [comment]
Thank you for reporting this! We've updated the codelab to clarify where the script tag should be placed - as you noted, it needs to come before the other non-Blockly scripts, since main.js loads the toolbox into Blockly and thus needs to have the block definition from sound_blocks.js in place at that point. I'll also put together a PR closing the <main> tag.
