### ISSUE TITLE
My Blockly plugin doesn't work

### ISSUE THREAD

**Issue by RixInGithub** [rachel-fenichel/blockly-samples#1128]
I was trying to generate a Blockly plugin using [these docs](https://blocklycodelabs.dev/codelabs/custom-generator/index.html?index=..%2F..index#1), and it went unsuccessfull. [This is my demo](https://void-plugin.rixthetyrunt.repl.co), and it throws this error:
```
Uncaught TypeError: Cannot read properties of undefined (reading '__namespace__')
    at blocks_compressed.js:14:18
    at blocks_compressed.js:10:26
    at blocks_compressed.js:13:2
```
The error is this line in `blocks_compressed.js`:
```js
var $=__parent__.__namespace__;
```

This is the only block I am trying to generate:
![Block](https://user-images.githubusercontent.com/87478581/164715371-5139d9e7-2039-4af9-a487-20475b9f3677.png)

My script is this:

```js
Blockly.common.defineBlocksWithJsonArray([{
  "type": "void",
  "message0": "͡°  ͡° %1 %2",
  "args0": [
    {
      "type": "input_dummy"
    },
    {
      "type": "input_statement",
      "name": "FUNC1"
    }
  ],
  "tooltip": "Bruh gimme some blocks and see what happens!",
  "helpUrl": ""
}])

toolbox = {
	"kind": "flyoutToolbox",
	"contents": [
		{
			"kind": "block",
		}
	]
}

defaultOptions = {
	comments: true,
	toolbox: toolbox,
}
```

**Comment by BeksOmega** [comment]
Hello! Could you please direct your question to our [developer forum](https://groups.google.com/g/blockly)? You're more likely to get a response there as there are people asking questions over the weekend! Plus it helps us keep our issue tracker clean =)

But to give you a bit of help: If you want to create a block, check out [these docs](https://developers.google.com/blockly/guides/create-custom-blocks/overview). If you want to get started with Blockly, check out [these docs](https://blocklycodelabs.dev/codelabs/getting-started/index.html?index=..%2F..index#3). And if you want to create a plugin, check out [these docs](https://developers.google.com/blockly/guides/plugins/overview).

Best wishes,
--Beka
