### ISSUE TITLE
Create a Vue3 example

### ISSUE THREAD

**Issue by BeksOmega** [rachel-fenichel/blockly-samples#1130]
**Category**

 - Examples

**Component**

blockly-vue

**Is your feature request related to a problem? Please describe.**

Vue has released a new major version (3), and we have [reports](https://github.com/google/blockly/issues/3917#issuecomment-1109232597) that people are having trouble using our current Vue sample with it. At the moment I'm not sure what the issue is, but I think any fixes will likely be minimal as most of the changes in Vue3 were supposed to be internal (from what I'm reading).

**Describe the solution you'd like**

Ideally, one demo that is compatible with Vue2 and Vue3.

**Describe alternatives you've considered**

Two separate demos, one for Vue2 and one for Vue3.

**Additional context**

N/A

**Comment by e-gloo** [comment]
#1179 e-gloo:master

**Comment by gonfunko** [comment]
Fixed in #1179.
