### ISSUE TITLE
Create a Warnings codelab

### ISSUE THREAD

**Issue by BeksOmega** [rachel-fenichel/blockly-samples#1133]
**Category**

 - Codelabs

**Is your feature request related to a problem? Please describe.**

We had requests at the 2022 Blockly Summit for more info about [Warnings](https://developers.google.com/blockly/reference/js/Blockly.Warning) and [setWarningText](https://developers.google.com/blockly/reference/js/Blockly.BlockSvg#setWarningText). It seemed like many people hadn't discovered it, but thought it would be a cool feature to add to their application once they had seen it.

**Describe the solution you'd like**

A codelab explaining what warnings are, and giving an example of how to use them. The example should probably either apply warnings based on [validators](https://developers.google.com/blockly/guides/create-custom-blocks/fields/validators) or [move events](https://developers.google.com/blockly/guides/configure/web/events#blocklyeventsblock_move) (since those are the situations we normally see warnings being applied in).

**Describe alternatives you've considered**

Some docs about warnings, but I'm not sure where they would go.

**Additional context**

@maribethb I think this relates to the work you're doing wrt docs.

**Comment by johnnesky** [comment]
FYI I'm working on a codelab for this now! It'll use the JavaScript Extension API to apply a validator and a change listener to a custom block (otherwise defined via JSON), and when the validator isn't enough to enforce valid fields, a warning indicator will be applied and the block will be disabled.
