### ISSUE TITLE
Outdated keyboard nav documentation

### ISSUE THREAD

**Issue by SebCanet** [rachel-fenichel/blockly-samples#1136]
**Category**
 - Plugins
 - 
**Component**
keyboard navigation

**Describe the bug**

In the keyboard codelab, step 9 ([https://blocklycodelabs.dev/codelabs/keyboard-navigation/index.html?index=..%2F..index#8](https://blocklycodelabs.dev/codelabs/keyboard-navigation/index.html?index=..%2F..index#8)) refers to an outdated link (branch 07762ff4da):
[https://github.com/google/blockly/blob/07762ff4da3c713f7592c80052b1fa7cadb461a2/core/keyboard_nav/navigation.js](https://github.com/google/blockly/blob/07762ff4da3c713f7592c80052b1fa7cadb461a2/core/keyboard_nav/navigation.js)

I think the codelab should be updated, and maybe documentation upgraded with an example of the 'Change current key mappings' information.

Thanks.

**Comment by rachel-fenichel** [comment]
BeksOmega is this fixed?
