### ISSUE TITLE
RTC example needs updates

### ISSUE THREAD

**Issue by SebCanet** [rachel-fenichel/blockly-samples#1139]
**Category**

Examples

**Component**

blockly-rtc

**Describe the bug**

Updating Blockly version in dependencies breaks this example, serializaton method has changed so it cannot work anymore.

**To Reproduce**

1. Update blockly dependance from v4 to v8
2. npm install
3. npm run start-websocket
4. See error when opening browsers

Many thanks for updating this work!

**Comment by SebCanet** [comment]
After many tests, I can upgrade all dependencies except blockly in v6.20210701.0 and copy-webpack-plugin in v5.1.2.
It works in Windows but with "cross-env" dependency added, and adding "SET NODE_OPTIONS=--openssl-legacy-provider" before any script in package.json. So line
"audit": "npm audit fix",
becomes
"audit": "SET NODE_OPTIONS=--openssl-legacy-provider && cross-env npm audit fix",
Hope this help to help me :-D

**Comment by gonfunko** [comment]
This appears to have been resolved in #1346.
