### ISSUE TITLE
Bitmap field cursor improvements

### ISSUE THREAD

**Issue by maribethb** [rachel-fenichel/blockly-samples#1167]
**Category**
 - Plugins

**Component**
field-bitmap

**Is your feature request related to a problem? Please describe.**

- Sometimes when trying to "paint" the squares, the browser tries to activate "drag and drop" mode and stops you from painting
- the cursor is always the "drag" cursor like when you hover over other parts of the block, so it's not obvious you can click on the field to edit it (compare to a text input field, for example)

**Describe the solution you'd like**

- [x] disable drag and drop mode for this element (there are various methods such as preventing default on mousedown or on dragstart) - fixed by #1205
- [ ] set the cursor for the element to a different one that indicates you can click on the field (not drag)

**Additional context**

To work on this issue, first read the [background information](https://developers.google.com/blockly/guides/contribute/samples) about how to contribute to samples and verify your changes.

The field-bitmap plugin is a custom field in Blockly. The custom fields API allows one to change the cursor when the user is hovering over the field by [setting the `CURSOR` property](https://developers.google.com/blockly/guides/create-custom-blocks/fields/customizing-fields/creating#customizing_the_cursor). So, to fix this issue, you need to set the `CURSOR` property of the field to the string`'default'` which corresponds to the css value for the default mouse pointer.

Be sure to validate your changes as described in the Contributing docs.

**Comment by Vortue** [comment]
I would like to work on this! 😃
