### ISSUE TITLE
field-date uses closure compiler

### ISSUE THREAD

**Issue by maribethb** [rachel-fenichel/blockly-samples#1168]
**Category**

 - Plugins

**Component**

field-date

**Describe the bug**

The date picker field is using closure compiler. We should change this. Especially once Blockly is converted to es modules I don't know that this will continue to work in its current state.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by gonfunko** [comment]
Duplicate of #1301.
