### ISSUE TITLE
bitmap field is missing JsDoc

### ISSUE THREAD

**Issue by maribethb** [rachel-fenichel/blockly-samples#1174]
**Category**

 - Plugins

**Component**

field-bitmap

**Describe the bug**

Many methods in the plugin are missing jsdoc for the parameters.

**To Reproduce**

Run `npm run lint` and observe lint errors

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Priyankcoder** [comment]
Hi @maribethb, Can you please assign this to me? I am working on it.

**Comment by maribethb** [comment]
Fixed by #1176 , thanks @Priyankcoder !
