### ISSUE TITLE
Content highlight does not update when blocks are updated

### ISSUE THREAD

**Issue by BeksOmega** [rachel-fenichel/blockly-samples#1216]
**Category**

 - Plugins

**Component**

content-highlight

**Describe the bug**

When you mutate a block, the content highlight does not change to match the new size of the block.

**To Reproduce**

1. cd into the `plugins/content-highlight` directory
2. Run `npm run start`.
3. Drag an "if" block onto the workspace.
4. Click the gear icon.
5. Add little "if else" blocks inside the tiny workspace that pops up.
6. Observe how the white outline does not change to match the new size of the block.

![Screen recording 2022-08-04 3 52 45 PM](https://user-images.githubusercontent.com/25440652/182968751-ecd44e00-ecd2-4f83-b36e-4441089caaac.gif)

**Expected behavior**

The white outline should update to match the size of the block when it changes size.

**Additional context**

N/A

**Comment by BeksOmega** [comment]
This issue has a few steps to resolve:

1) Reproduce the issue using the steps outlined in the "To Reproduce" section. Once you can reproduce the bad behavior, you can test if your changes fixed it.
2) Modify the code in [plugins/content-highlight/src/index.js](https://github.com/google/blockly-samples/blob/master/plugins/content-highlight/src/index.js) updates in response to [Blockly.Events.BLOCK_CHANGE](https://developers.google.com/blockly/guides/configure/web/events#blocklyeventsblock_change) events, in addition to the ones it currently updates in response to.
3) Run the reproduction steps again, and verify that the content highlight properly updates to match the new size of the block.
4) Open your PR and resolve any PR comments.

After your PR is accepted, a Blockly team member will have to publish the GitHub Pages site, and then you'll be able to see your change live!

**Comment by vaish399** [comment]
Hello, excited to be working on this at GHC OSD!

**Comment by alschmiedt** [comment]
Fixed in #1288
