### ISSUE TITLE
Add css class docs to the workspace search plugin

### ISSUE THREAD

**Issue by BeksOmega** [rachel-fenichel/blockly-samples#1223]
**Category**

 - Plugins

**Component**

workspace-search

**Description**

Add documentation to the workpace-search plugin's [README](https://github.com/google/blockly-samples/blob/master/plugins/workspace-search/README.md) that informs developers about the css classes they can apply styles to, and what those styles will affect:
* blockly-ws-search
* blockly-ws-search-container
* blockly-ws-search-content
* blockly-ws-search-input
* blockly-ws-search-actions

See [these inline docs](https://github.com/google/blockly-samples/blob/0c64f5e6688f0d4589a7cc69091edd7e79d6d278/plugins/workspace-search/src/WorkspaceSearch.js#L157) for information about the structure of the workspace search, and what the different styles apply to.

**Comment by enatalie** [comment]
Could I try working on this one? Thanks!
