### ISSUE TITLE
`playgroundAPI` is missing some types

### ISSUE THREAD

**Issue by maribethb** [rachel-fenichel/blockly-samples#1224]
**Category**

 - Plugins

**Component**

dev-tools

**Describe the bug**

The Playground API exposed by dev-tools is written in JS, but it has handcrafted TypeScript type declarations [here]( https://github.com/google/blockly-samples/blob/0c64f5e6688f0d4589a7cc69091edd7e79d6d278/plugins/dev-tools/src/index.d.ts#L17). However, this type is missing the [`removeGenerator` function](https://github.com/google/blockly-samples/blob/0c64f5e6688f0d4589a7cc69091edd7e79d6d278/plugins/dev-tools/src/playground/index.js#L444).

`removeGenerator` should be added to the type so that API users know this function exists.

**To Reproduce**

1. Open any other plugin's `test/index.html` file.
2. Find the place in the code where `createPlayground` is called.
3. Try to use the `removeGenerator` API like so:

```js
createPlayground(....)
.then((playground) => {
  playground.removeGenerator('Python');
});
```

4. If you're using an editor with code completion, you may see an error like `Property 'removeGenerator' does not exist on type 'PlaygroundAPI'.`

**Expected behavior**

There is no error about a missing property.

**Additional context**

To work on this issue, first read the [background information](https://developers.google.com/blockly/guides/contribute/samples) about how to contribute to samples and verify your changes.

You will need to use another plugin to test your changes to the type declarations in dev-tools. Our plugins are independent npm packages, but for local development the plugins will be symlinked to each other automatically. All you need to do is ensure that you only run `npm install` in the root level of blockly-samples, and **not** in the specific plugin directory. This way, our automated tooling will link the plugins together and you'll be able to see your local changes to `dev-tools` inside another plugin.

**Comment by lmgillaspie** [comment]
Hi @BeksOmega ! I'll work on this!
