### ISSUE TITLE
Update plugins to use JSON toolbox definitions instead of xml.

### ISSUE THREAD

**Issue by maribethb** [rachel-fenichel/blockly-samples#1225]
**Category**
 - Plugins

**Component**

- [ ] block-dynamic-connection
- [ ] block-plus-minus
- [ ] dev-tools
- [ ] keyboard-navigation
- [ ] theme-dark
- [ ] theme-deuteranopia
- [ ] theme-highcontrast
- [ ] theme-modern
- [ ] theme-tritanopia

**Is your feature request related to a problem? Please describe.**

Many of the examples and plugins use XML toolboxes instead of the new JSON API. We should have our example code use the new APIs to best model what other developers can do with Blockly.

**Describe the solution you'd like**

Update the code in blockly-samples to use the JSON toolbox API.

**Additional context**

This issue has multiple parts. Several people can work on this issue at once, and it can be fixed over multiple PRs. If you'd like to work on this, consider adding a comment saying which plugin you are working on updating, to avoid duplicate work.

To work on this issue, first read the [background information](https://developers.google.com/blockly/guides/contribute/samples) about how to contribute to samples and verify your changes.

1. Learn about [defining a toolbox](https://developers.google.com/blockly/guides/configure/web/toolbox) and read about the XML format vs the JSON format.
2. In blockly-samples, navigate to a specific plugin's directory and run `npm run start` to start the playground. Look at the toolbox and what blocks are available.
3. Write a new copy of the toolbox definition in the JSON format instead of the XML format. The toolbox definition in most cases should now be in `test/index.js` instead of `test/index.html`.
4. Refresh the playground page and make sure the toolbox looks the same as it did before. You can compare against the version in master on the [samples site](https://google.github.io/blockly-samples/) to make sure the behavior hasn't changed.
5. Follow the rest of the instructions in the Contributing docs to verify your change and open a PR.

**Comment by BeksOmega** [comment]
Separated this out into individual issues for each plugin.
