### ISSUE TITLE
Update examples to use JSON toolbox definitions instead of xml.

### ISSUE THREAD

**Issue by maribethb** [rachel-fenichel/blockly-samples#1226]
**Category**
 - Examples

**Component**

- [ ] backpack-demo
- [ ] blockly-angular
- [ ] blockly-node
- [ ] blockly-parcel
- [ ] blockly-requirejs
- [ ] blockly-rtc
- [ ] blockly-umd
- [ ] blockly-webpack
- [ ] custom-dialogs-demo
- [ ] fixed-demo
- [ ] generator-demo
- [ ] graph-demo
- [ ] headless-demo
- [ ] interpreter-demo
- [ ] mirror-demo
- [ ] resizable-demo
- [ ] rtl-demo
- [ ] single-direction-scroll-demo
- [ ] toolbox-demo

Purposely excluded - these should not be updated:
- blockly-react: Appears to be custom handling of XML in the component
- blockly-svelte: Same
- blockly-vue: Same
- pitch-field-demo: Has custom xml handling
- plane-demo: May be deleted soon
- turtle-demo: Has custom xml handling
- any of the codelabs example code. These should be updated as well but require additional care to ensure that the starting and finished code matches, and the text of the codelab itself still makes sense.

**Is your feature request related to a problem? Please describe.**

Many of the examples and plugins use XML toolboxes instead of the new JSON API. We should have our example code use the new APIs to best model what other developers can do with Blockly.

**Describe the solution you'd like**

Update the code in blockly-samples to use the JSON toolbox API.

**Additional context**

This issue has multiple parts. Several people can work on this issue at once, and it can be fixed over multiple PRs. If you'd like to work on this, consider adding a comment saying which plugin you are working on updating, to avoid duplicate work.

To work on this issue, first read the [background information](https://developers.google.com/blockly/guides/contribute/samples) about how to contribute to samples and verify your changes.

1. Learn about [defining a toolbox](https://developers.google.com/blockly/guides/configure/web/toolbox) and read about the XML format vs the JSON format.
2. In blockly-samples, navigate to a specific example's directory. Some examples can be started with `npm run start` and some can be opened directly by opening the `index.html` file in a browser. The README may give specific instructions, or you can look in the `package.json` to see what scripts are defined. Note you may need to run `npm install` in the example directory. Either way, open the example's demo page to observe the toolbox and its contents.
3. Write a new copy of the toolbox definition in the JSON format instead of the XML format. Where exactly it should be declared will depend on the example. It will most likely make sense to declare the toolbox definition close to the location where it is used, i.e. where `Blockly.inject` is called.
4. Refresh the demo page and make sure the toolbox looks the same as it did before. You can compare against the version in master on the [samples site](https://google.github.io/blockly-samples/) to make sure the behavior hasn't changed. Note that not all demos are published on the samples site so it may not be there.
5. Follow the rest of the instructions in the Contributing docs to verify your change and open a PR.

**Comment by BeksOmega** [comment]
Created individual issues for each example instead.
