### ISSUE TITLE
Update backpack-demo to use JSON toolbox definitions instead of xml

### ISSUE THREAD

**Issue by BeksOmega** [rachel-fenichel/blockly-samples#1247]
**Category**
 - Examples

**Component**

backpack-demo

**Is your feature request related to a problem? Please describe.**

Many of the examples and plugins use XML toolboxes instead of the new JSON API. We should have our example code use the new APIs to best model what other developers can do with Blockly.

**Describe the solution you'd like**

Update the code in blockly-samples to use the JSON toolbox API.

**Additional context**

To work on this issue, first read the [background information](https://developers.google.com/blockly/guides/contribute/samples) about how to contribute to samples and verify your changes.

1. Learn about [defining a toolbox](https://developers.google.com/blockly/guides/configure/web/toolbox) and read about the XML format vs the JSON format.
2. In blockly-samples, navigate to the backpack-demo example's directory. Some examples can be started with `npm run start` and some can be opened directly by opening the `index.html` file in a browser. The README may give specific instructions, or you can look in the `package.json` to see what scripts are defined. Note you may need to run `npm install` in the example directory. Either way, open the example's demo page to observe the toolbox and its contents.
3. Write a new copy of the toolbox definition in the JSON format instead of the XML format. Where exactly it should be declared will depend on the example. It will most likely make sense to declare the toolbox definition close to the location where it is used, i.e. where `Blockly.inject` is called.
4. Refresh the demo page and make sure the toolbox looks the same as it did before. You can compare against the version in master on the [samples site](https://google.github.io/blockly-samples/) to make sure the behavior hasn't changed. Note that not all demos are published on the samples site so it may not be there.
5. Follow the rest of the instructions in the Contributing docs to verify your change and open a PR.

**Comment by nitesh-chowdhary** [comment]
can i contribute to this project, java is my programming language and I am a beginner

**Comment by BeksOmega** [comment]
Hi @Thenitesh143 Thank you for your interest =) Sadly we don't use Java in this repository, instead we use JavaScript and TypeScript.

That being said, this issue is still relatively beginner friendly, even if you don't have any programming experience! The most difficult part will probably be setting up your environment, which we have instructions for [here](https://developers.google.com/blockly/guides/contribute/get-started#step_by_step).

So if you're comfortable digging in and doing a bit of learning, we'd love to assign this issue to you!

Best wishes,
--Beka

**Comment by nitesh-chowdhary** [comment]
Yes, I would like to contribute.
It would be very nice of you if you could assign me the project.

**Comment by BeksOmega** [comment]
@Thenitesh143 Assigned you! If you have any questions please feel free to reply =)

**Comment by Thenitesh143** [comment]
@BeksOmega can you please tell me how to  understand which code I need to make changes on, how to run test cases and how to run it locally.

**Comment by Thenitesh143** [comment]
Do I have to change all xml code to json code

**Comment by Thenitesh143** [comment]
Or do I need to go to examples->backpack-demo->index.js and make changes

**Comment by Thenitesh143** [comment]
Or do I need to go to examples->backpack-demo->index.js and make changes

**Comment by nitesh-chowdhary** [comment]
@BeksOmega can you please help me out to write the comment to the PR it is getting rejected

**Comment by nitesh-chowdhary** [comment]
or can you please review it and let me know how to correct it or can you please ignore the commit message and merge the PR since it has passed all test cases except the conventional commit or else please help me with a commit to merge it
link given below
https://github.com/google/blockly-samples/pull/1336#issue-1409540148

**Comment by varshneydevansh** [comment]
If this issue is still open, I'd love to do this.

**Comment by BeksOmega** [comment]
@varshneydevansh I've assigned you! If you have any questions feel free to ask =)
