### ISSUE TITLE
Bitmap field cleanup

### ISSUE THREAD

**Issue by rachel-fenichel** [rachel-fenichel/blockly-samples#1312]
**Category**
 - Plugins

**Component**

field-bitmap

**Describe the bug**

Console warnings in the bitmap test page: 
- Not setting SERIALIZABLE correctly
- Using `css.register` with an array of strings instead of a multiline string.

**To Reproduce**
Check out `blocky-9-beta` (after this week, probably just check out `master`

**Expected behavior**

No console warnings

**Additional context**

**Comment by mikebarr24** [comment]
@rachel-fenichel 
Could I take a look at this issue?

**Comment by rachel-fenichel** [comment]
Go for it!
