### ISSUE TITLE
ScrollMetricsManager.js:20 Uncaught TypeError: Class extends value undefined is not a constructor or null  at ./node_modules/@blockly/plugin-scroll-options/src/ScrollMetricsManager.js (ScrollMetricsManager.js:20:1)     at options.factory (react refresh:6:1)

### ISSUE THREAD

**Issue by painghtetaung** [rachel-fenichel/blockly-samples#1321]
**Category**

**Component**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by cpcallen** [comment]
Hi @painghtetaung,

Can you provide more information about how to reproduce this error, please?

**Comment by maribethb** [comment]
I can't reproduce this on v3.0.8. @painghtetaung please provide more information about how we can reproduce. Thanks!

**Comment by BeksOmega** [comment]
Closing as cannot reproduce.
