### ISSUE TITLE
Refactor the +/- procedure blocks to use the new procedure data models

### ISSUE THREAD

**Issue by BeksOmega** [rachel-fenichel/blockly-samples#1324]
### Problem Statement

After the shared procedures project is mostly implemented we need to refactor the +/- blocks to use the new explicitly defined data models. Otherwise the +/- blocks will not be interchangeable with the built-in blocks, which is something we want to maintain. 

Related to https://github.com/google/blockly/issues/6526

**Comment by gonfunko** [comment]
Duplicate of #1665.
