### ISSUE TITLE
custom toolbox codelab provides es5 code that will no longer run

### ISSUE THREAD

**Issue by maribethb** [rachel-fenichel/blockly-samples#1328]
**Category**

 - Codelabs

**Component**

custom toolbox

**Describe the bug**

The custom toolbox code has an es5 class for the custom toolbox category. this is no longer compatible with blockly as we are no longer compiling down to es5.

**To Reproduce**

try to run the starter code for the codelab

**Expected behavior**

**Screenshots**

**Additional context**

We should remove the es5 class and only support the es6 class.

**Comment by mikebarr24** [comment]
@maribethb Could I have a go at this issue?

**Comment by Samridhi-98** [comment]
Hey @maribethb, I would like to take this one.

**Comment by BeksOmega** [comment]
Go for it @Samridhi-98 !
