### ISSUE TITLE
Update the headless demo to use JSON instead of XML

### ISSUE THREAD

**Issue by BeksOmega** [rachel-fenichel/blockly-samples#1335]
**Category**

 - Codelabs

**Component**

headless-demo

**Describe the bug**

XML is iceboxed, so our demos should use JSON.

See: https://google.github.io/blockly-samples/examples/headless-demo/

**How to fix**
In `examples/headless-demo/index.html` you want to:
1) Change the contents of the text area to be valid JSON instead of XML. You can get this by
  a) deserializing the existing XML into the [playground](https://blockly-demo.appspot.com/static/tests/playground.html) using the text area on the left, and the "Load" button
  b) Hitting the "Save JSON" button.
  c) Pasting the result back into `index.html`
2) Change the call to [Blockly.Xml.domToWorkspace](https://developers.google.com/blockly/reference/js/blockly.xml_namespace.domtoworkspace_1_function.md) to a call to [Blockly.serialization.workspaces.load](https://developers.google.com/blockly/reference/js/blockly.serialization_namespace.workspaces_namespace.load_1_function.md).

**Comment by mikebarr24** [comment]
Hey @BeksOmega. Would it be OK If I worked on this issue?

**Comment by BeksOmega** [comment]
Go for it @mikebarr24 ! I've assigned you :D Feel free to ask here if you get stuck or having any other questions!
