### ISSUE TITLE
Custom Dialogs sample doesn't work anymore

### ISSUE THREAD

**Issue by semiaddict** [rachel-fenichel/blockly-samples#1342]
**Category**

Examples

**Component**

custom-dialogs

**Describe the bug**

The [Custom Dialogs](https://google.github.io/blockly-samples/examples/custom-dialogs-demo/) example doesn't seem to work any more.
I get errors in Chrome and Firefox related to `Blockly.dialog not being defined`.
This might be related to the release of v9.

**To Reproduce**

1. Go to https://google.github.io/blockly-samples/examples/custom-dialogs-demo/
2. Open the 'Variables' category
3. Click on 'Create variable...'
4. Notice how it's the native dialog that is shown instead of the custom one
5. See the error in the console

**Expected behavior**

The custom dialog should be used instead of the native one.

**Screenshots**

N/A

**Additional context**

N/A

**Comment by BeksOmega** [comment]
Hello! This was fixed by https://github.com/google/blockly-samples/pull/1332 and should go out on Thursday =)

Thank you for the report!
