### ISSUE TITLE
fix codelabs css

### ISSUE THREAD

**Issue by maribethb** [rachel-fenichel/blockly-samples#1364]
**Category**

 - Codelabs

**Component**

all

**Describe the bug**

css is broken

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

https://groups.google.com/g/codelab-authors/c/WwSdRF4bjBE need to host the css files ourselves. they are providing a temporary workaround though

**Comment by rachel-fenichel** [comment]
I updated the site to use their new CSS file from the new bucket. I don't understand why we need to host the CSS files ourselves, since we need other files from their bucket and we don't want to be maintaining and updating our own CSS.

**Comment by maribethb** [comment]
You're right, we don't need to host ourselves. My initial interpretation of their workaround with the `tmp` bucket was that it would be temporary but it looks like they plan to keep the new bucket online.
