### ISSUE TITLE
Not clearing the blockly editor at first change the number button in edit mode

### ISSUE THREAD

**Issue by OracleGao** [rachel-fenichel/blockly-samples#1397]
- The doc [Getting started with Blockly - 7 Save/load workspace - Add the load method](https://blocklycodelabs.dev/codelabs/getting-started/index.html#6)  has a bug, when you first change the number button, the blockly editor not be cleared，because when click the new button, the button.blocklySave is undefined, the  'workspace' not be cleared up. The following fix it 
### fixed
``` javascript
    if (button.blocklySave) {
      Blockly.serialization.workspaces.load(button.blocklySave, workspace);
    }
``` 

- The code in the 'loadWorkspace' function should be replaced by the the following code

``` javascript
    if (button.blocklySave) {
      Blockly.serialization.workspaces.load(button.blocklySave, workspace);
    } else {
      Blockly.serialization.workspaces.load({}, workspace);
    }
```

**Comment by BeksOmega** [comment]
Hello @OracleGao ! Thanks for filing this issue :D

Would you be interested in putting up a pull request to fix the instructions? We have information on how to do so [here](https://developers.google.com/blockly/guides/contribute/get-started#step_by_step).

**Comment by maribethb** [comment]
see also #1521 (closing this bug since Justin is assigned to new one)
