### ISSUE TITLE
field-colour-hsv-sliders does not fire change events

### ISSUE THREAD

**Issue by BeksOmega** [rachel-fenichel/blockly-samples#1442]
**Category**

 - Plugins

**Component**

The field-colour-hsv-sliders field does not fire change events, so undo and redo don't work properly.

**Describe the bug**

**To Reproduce**

1. Go to the field colour slider demo: https://google.github.io/blockly-samples/plugins/field-colour-hsv-sliders/test/
2. Drag a block onto the workspace
3. Change its value
4. Undo
5. Observe how the block is deleted instead of triggering the value change.

**Expected behavior**

The value of the field should be reverted to the original value.

**Comment by johnnesky** [comment]
I can't reproduce this at the moment. I believe it got fixed when I was doing https://github.com/google/blockly-samples/pull/1464
