### ISSUE TITLE
The suggested blocks plugin is not available on the demo site

### ISSUE THREAD

**Issue by BeksOmega** [rachel-fenichel/blockly-samples#1444]
**Category**

 - Plugins

**Component**

suggested-blocks

**Describe the bug**

The suggested blocks plugin was never included in the index.md, so it isn't included on the demo site.

https://github.com/google/blockly-samples/blob/master/gh-pages/index.md

**To Reproduce**

1. Go to the demo site.
2. Observe how suggested-blocks does not exist.

**Expected behavior**

The demo should exist.

**Additional context**

It also appears the plugin isn't working locally. Tracking issue: https://github.com/google/blockly-samples/issues/1445

**Comment by BeksOmega** [comment]
This got left off the new demo site.

**Comment by shivalipatel6** [comment]
Can I take this on?

**Comment by BeksOmega** [comment]
Go for it @shivalipatel6 =)
