### ISSUE TITLE
The disabled-interactions plugin should not include the IDs of shadow blocks

### ISSUE THREAD

**Issue by BeksOmega** [rachel-fenichel/blockly-samples#1447]
**Category**

 - Plugins

**Component**

serialize-disabled-interactions

**Describe the bug**

The disabled interactions plugin serializes the IDs of shadows into the `notMovable` and `notDeletable` arrays, but we don't need to because being a shadow actually /determines/ those (not the other way around) and shadow-ness is already serialized separately.

So this is just duplicate data.

**To Reproduce**

1. Go to the serialize disabled interactions demo.
2. Drag out a block with shadows.
3. Serialize to json.
4. Observe how the shadow IDs are included in the serialize-disabled-interactions object.

**Expected behavior**

Shadow IDs are not included in the serialized state.

**Comment by mikebarr24** [comment]
@BeksOmega  Could I take a look at this?

**Comment by BeksOmega** [comment]
We're actually going to be adding the serialization to the built-in block serializer, and deprecating this plugin (ref: https://github.com/google/blockly/issues/6807). So I don't think it's as useful to fix this any more :/ But if you're still interested you can definitely look into it =)

**Comment by mikebarr24** [comment]
Sure I'll maybe leave it then. It's always nice to think that what you've done is useful. I'll find something else if that's OK.😀

**Comment by maribethb** [comment]
Closing this as obsolete as the plugin is deprecated.
