### ISSUE TITLE
strict-connection-checker demo does not allow the print block to be dragged from the flyout

### ISSUE THREAD

**Issue by BeksOmega** [rachel-fenichel/blockly-samples#1451]
**Category**

 - Plugins

**Component**

strict-connection-checker

**Describe the bug**

You cannot drag the `print` block from the toolbox, because its input has a `null` check, and its text shadow block has a `String` check.

**To Reproduce**

1. Go to the strict-connection-checker demo: https://google.github.io/blockly-samples/plugins/strict-connection-checker/test/
2. Attempt to drag the print block from the flyout.
3. Observe the errors in the console

**Expected behavior**

The print block in the strict connection checker demo should not have a shadow string block attached, so this error can never occur.

**Additional context**

N/A

**Comment by mikebarr24** [comment]
Hey @BeksOmega. If my other PR is all good, could I take a look at this?

**Comment by BeksOmega** [comment]
Go for it @mikebarr24 =)
