### ISSUE TITLE
Flexible Type Checks by using a function

### ISSUE THREAD

**Issue by Briskled** [rachel-fenichel/blockly-samples#1471]
**Category**
Plugins

**Component**
type-checks / implicit type casts

**Is your feature request related to a problem? Please describe.**
Type checks in Blockly are pretty basic. It should be possible to have implicit type casts. E.g. allow that you can plug any block into a string-input. Or in case you have types like Float, Integer, Hexadecimal, it should be possible to plug an integer into a float input and so on...

**Describe the solution you'd like**
Instead of checking wether output-type-list and input-type-list have at least one common element, there should be a customizable function to determine if a block can be put into an input. This could be done by a function argument such as:
`(blockOutputList, otherBlockInputList) => Boolean`

**Describe alternatives you've considered**
When (dynamically) building a block, compatible types can be added to a block input. Example: You want to build a block with output type: `A`
And another block with an input of type `B`. You want `A` to extend `B`, so it should be possible to plug the first block into the second. By default, this would not be possible. A workaround would be to add `A` together with `B` in the input list of the second block.

**Comment by gonfunko** [comment]
This can be achieved by registering a class that implements `IConnectionChecker` and overriding `doTypeChecks`, which is effectively the function you describe - it takes two `Connection` objects and returns whether they should or should not be allowed to connect to one another. More documentation is available here: https://developers.google.com/blockly/guides/configure/advanced/interfaces/connection_checker#overriding_the_connection_checker
