### ISSUE TITLE
getting started codelab (complete-code) doesn't work.

### ISSUE THREAD

**Issue by jubishop** [rachel-fenichel/blockly-samples#1521]
**Category**

Codelabs

**Component**

Complete-code (saving workspace to just one button)

**Describe the bug**

The workspace configuration isn't saved as specific for a single button.

**To Reproduce**

1. Open `examples/getting-started-codelab/complete-code/index.html` in browser.
2. Click "Edit" button in upper right.
3. Click "1" button to reveal workspace.
4. Drag a "Repeat 5 times" green operator onto the workspace and insert a red "play c4" operator inside it.
5. Click "Save" in upper right.
6. Click "2" button to reveal workspace.
7. Bug: The configuration inserted for button "1" shows in workspace "2".

**Expected behavior**

Each button should be opening it's own unique workspace, so the configuration put in the workspace for button "1" should not show in the workspace for button "2".

**Additional context**

I think I know the problem, in the `save()` method:

```js
  function save(button) {
    button.blocklySave = Blockly.serialization.workspaces.save(
        Blockly.getMainWorkspace());
  }
```

The main blockly workspace needs to be cleared after it's serialized and attached to that button.  Since it's never cleared, it shows the same when any other button is loaded.

**Comment by jubishop** [comment]
alternatively, in 

```javascript
  function loadWorkspace(button) {
    const workspace = Blockly.getMainWorkspace();
    if (button.blocklySave) {
      Blockly.serialization.workspaces.load(button.blocklySave, workspace);
    }
  }
```

an `else` block could be added and the workspace could be cleared there.

**Comment by jubishop** [comment]
note: i will submit a PR to fix this.

**Comment by maribethb** [comment]
> alternatively, in
> 
> ```js
>   function loadWorkspace(button) {
>     const workspace = Blockly.getMainWorkspace();
>     if (button.blocklySave) {
>       Blockly.serialization.workspaces.load(button.blocklySave, workspace);
>     }
>   }
> ```
> 
> an `else` block could be added and the workspace could be cleared there.

This is the intended design, I think this bug was introduced fairly recently (in terms of changes this codelab has undergone)

The codelab reuses the same workspace for each button on purpose, to demonstrate saving and loading with xml. But it's a confusing choice and imo using multiple workspaces (or pretending to) is one of the problems with this codelab

**Comment by jubishop** [comment]
yeah, it's a bit scuffed.  i'll just add a quick fix with an `else` block in `loadWorkspace` for now.
