### ISSUE TITLE
The  example  blockly-vue run error  

### ISSUE THREAD

**Issue by guojs** [rachel-fenichel/blockly-samples#1548]
![image](https://user-images.githubusercontent.com/13706435/217258020-ed70c005-d911-445f-a756-036badc441ca.png)

**Comment by mikebarr24** [comment]
I think in stocks.js blockly/core is imported and the javascript generator is not included. 
I think I've fixed this by importing it separately from blockly/javascript. 

Should I go ahead and create a PR for this?

**Comment by BeksOmega** [comment]
> I think in stocks.js blockly/core is imported and the javascript generator is not included. I think I've fixed this by importing it separately from blockly/javascript.
> 
> Should I go ahead and create a PR for this?

Hearing your description, that sounds like a resonable solution! I think uploading a PR so we can take a look is great next step =) Thank you for looking into this!
