### ISSUE TITLE
Logical error in description of Statement blocks

### ISSUE THREAD

**Issue by lexander** [rachel-fenichel/blockly-samples#1582]
```
Statement blocks represent code that does not return a value.

A statement block's generator simply returns a string.
```
Q: Does it return nothing or does it return a string value?
A: Statement blocks return a string representation of code that should be executed in the target language. E.g. a statement block generator that should invoke the `turnLeft` method would look like: 
```javascript
sampleGenerator['left_turn_block'] = function(block) {
  return 'turnLeft()';
}
```

**Comment by rachel-fenichel** [comment]
Hi @lexander, are you requesting a change to a specific bit of documentation/codelab? We're open to pull requests to fix issues. 

However, the descriptions above are correct: running a statement block doesn't result in a usable value (e.g. `turnLeft()` usually doesn't return anything). 

The *generator* is different from the block itself, and returns a string (but no operator precedence). By contrast, the generator for a value block is a list with two values: the code and the precedence. For more information, check out the documentation on [operator precedence](https://developers.google.com/blockly/guides/create-custom-blocks/operator-precedence).
