### ISSUE TITLE
 Cannot set properties of undefined (setting 'stock_buy_simple')

### ISSUE THREAD

**Issue by zhubin123** [rachel-fenichel/blockly-samples#1594]
I try to run the blockly-vue3 example, npm i & npm run start, but the web page is blank.
The console show the error message " Cannot set properties of undefined (setting 'stock_buy_simple')"
So I check it, found the "Blockly.JavaScript" is undefined, So what can I do now, thanks for help!
![2](https://user-images.githubusercontent.com/17978537/221764576-4030797c-be50-40e2-9014-0048ff95579e.jpg)

**Comment by maribethb** [comment]
Hello,

This is because in blockly v9 `Blockly.JavaScript` became 

```js
import {javascriptGenerator} from 'blockly/javascript';
javaScriptGenerator[stock_buy_simple] = // ...
```

Here's an example where we fixed other demos: #1454 

We would accept a PR if you would like to fix the example. Thanks!

**Comment by mikebarr24** [comment]
@maribethb If no one has taken this, could I submit a PR for this?

**Comment by BeksOmega** [comment]
@mikebarr24 Go for it =)
