### ISSUE TITLE
Provide generators for block-dynamic-connections

### ISSUE THREAD

**Issue by maribethb** [rachel-fenichel/blockly-samples#1622]
**Category**

 - Plugins

**Component**

block-dynamic-connections

**Is your feature request related to a problem? Please describe.**

The plugin doesn't provide generators for the blocks, and they are not compatible with the built-in generators (i.e. I tried to set `javascriptGenerator['dynamic_if'] = javascriptGenerator['controls_if']` but that doesn't work)

**Describe the solution you'd like**

Plugin provides generators for all blocks, or plugin is made to be compatible with the generator for the built-in blocks they are designed to replace

**Describe alternatives you've considered**

**Additional context**

**Comment by BeksOmega** [comment]
My guess is that this is related to the different input naming scheme? If so, then it would be really difficult to make that compatible without breaking existing saves (iirc).
