### ISSUE TITLE
Provide better documentation for suggested-blocks

### ISSUE THREAD

**Issue by maribethb** [rachel-fenichel/blockly-samples#1625]
🚧⚠️🚧 This issue is being saved for **Grace Hopper Open Source Day**. 🚧⚠️🚧 An event we're running to help girls and non-binary technologists make their first contributions to open source! Please see our list of [help wanted issues](https://github.com/google/blockly-samples/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22+-label%3A%22ghc-osd%22) if you'd like to contribute! 

---

**Category**

 - Plugins

**Component**

suggested-blocks

**Is your feature request related to a problem? Please describe.**

The README example is slicing into a toolbox XML string. That is not a good idea. There's a comment saying it's not a good idea, but still, we shouldn't model this for people. Also, we should use JSON.

**Describe the solution you'd like**

Replace the existing [usage documentation](https://github.com/google/blockly-samples/tree/master/plugins/suggested-blocks#usage) with the following:
```js
import * as Blockly from 'blockly';
import * as SuggestedBlocks from '@blockly/suggested-blocks';

const toolbox = {
  "kind": "categoryToolbox",
  "contents": [
    {
      "kind": "category",
      "name": "My Category",
      "contents": [ /* your category contents */ ]
    },
    {
      'kind': 'category',
      'name': 'Frequently Used',
      'custom': 'MOST_USED',
      'categorystyle': 'frequently_used_category',
    },
    {
      'kind': 'category',
      'name': 'Recently Used',
      'custom': 'RECENTLY_USED',
      'categorystyle': 'recently_used_category',
    },
  ]
};

// Inject Blockly.
const workspace = Blockly.inject('blocklyDiv', {
  toolbox: toolbox,
});

// Initialize the plugin
SuggestedBlocks.init(workspace);
```

**Describe alternatives you've considered**

N/A

**Additional context**

https://google.github.io/blockly-samples/plugins/suggested-blocks/README

**Comment by martinyis** [comment]
Hey, I have a solution that might be helpful. Could you assign it to me?

**Comment by maribethb** [comment]
Thanks, @martinyis, all yours!

**Comment by saymedgm** [comment]
@maribethb can you explain me this issue little bit would love to contribute in this

**Comment by BeksOmega** [comment]
> @maribethb can you explain me this issue little bit would love to contribute in this

Same reply as [here](https://github.com/google/blockly/issues/7253#issuecomment-1708675257)!

**Comment by divziv** [comment]
Would love to know more and contribute!

**Comment by BeksOmega** [comment]
Sweet @divziv ! Do you have any specific questions?

**Comment by divziv** [comment]
I am a beginner, 0 experience in TypeScript- what is it that I could do in order to begin?

**Comment by SYJONES16** [comment]
I am a beginner, but would love to watch what you are doing? is that okay for me to join?
