### ISSUE TITLE
@blockly/block-shareable-procedures isn't available on NPM or Yarn.

### ISSUE THREAD

**Issue by Njinx** [rachel-fenichel/blockly-samples#1639]
**Category**

Plugins

**Component**

block-shareable-procedures

**Describe the bug**

@blockly/block-shareable-procedures is not available in the Yarn package registry. 

**To Reproduce**

1) `yarn add @blockly/block-shareable-procedures`
2) Yarn will be unable to locate the package

**Expected behavior**

I expected the package to install correctly.

**Comment by BeksOmega** [comment]
Hello! The plugin is currently private, but it's planned to go out next week =) I'll try to remember to ping back here when it's out!

**Comment by Njinx** [comment]
Sounds good to me, but was the plugin always private?
