### ISSUE TITLE
 If i save, reload the workspace and then delete the block, the procedure in other workspaces will not be cleared correctly

### ISSUE THREAD

**Issue by githubalvin** [rachel-fenichel/blockly-samples#1655]
**Category**

Plugins

**Component**

blockl-shareable-procedures

**Describe the bug**

The mixin model_.id is regenerated every time the block is created, If i save, reload the workspace and then delete the block, the procedure in other workspaces will not be cleared correctly.

**Screenshots**

![impicture_20230404_205350](https://user-images.githubusercontent.com/13799840/229798532-995420ba-597f-440d-85e7-7fff25cb38b0.png)

**Comment by BeksOmega** [comment]
Hello! Thank you for reporting this! But sadly, I don't seem to be able to reproduce it on the [demo page](https://google.github.io/blockly-samples/plugins/block-shareable-procedures/test/) :/

[Screen recording 2023-04-04 11.10.16 AM.webm](https://user-images.githubusercontent.com/25440652/229881695-86ac1aaf-c589-408f-8214-fdc7dcf948ae.webm)

Here are the steps I followed:
1) Drag a procedure definition block into the workspace.
2) Drag a procedure caller block into the other workspace
3) Hit the "Reload" button to serialize to JSON and deserialize back into the workspaces
4) Delete the procedure definition block
5) Observe how the procedure caller block is also deleted.

Could you provide some alternative reproduction steps that recreate this issue? Hopefully with a bit more info we can get this fixed :D

**Comment by BeksOmega** [comment]
Closing as cannot reproduce.
