### ISSUE TITLE
Starter code for create-package with typescript does not compile

### ISSUE THREAD

**Issue by rachel-fenichel** [rachel-fenichel/blockly-samples#1670]
**Category**

 - Plugins

**Component**

`create-package`

**Describe the bug**

I created a new plugin with `npx @blockly/create-package plugin horizontal-flyout --type plugin --typescript`. Once I worked around #1669, I ran `npm build` and got these errors:

```
> blockly-horizontal-flyout@0.0.0 build
> blockly-scripts build

Running production build for blockly-horizontal-flyout
Failed to compile.

Module Error (from ./node_modules/eslint-loader/dist/cjs.js):

/home/fenichel/Documents/blockly-samples/plugins/horizontal-flyout/src/index.ts
  19:13  error    Class Property name `workspace_` must match one of the following formats: camelCase, PascalCase  @typescript-eslint/naming-convention
  22:0   warning  Types are not permitted on @param                                                                jsdoc/no-types

✖ 2 problems (1 error, 1 warning)
  0 errors and 1 warning potentially fixable with the `--fix` option.
```

The relevant starter code looks like this:
```
  /** The workspace. */
  protected workspace_: Blockly.WorkspaceSvg;
  /**
   * Constructor for ...
   * @param {!Blockly.WorkspaceSvg} workspace The workspace that the plugin will
   *     be added to.
   */
  constructor(workspace: Blockly.WorkspaceSvg) {
    this.workspace_ = workspace;
  }
```

**To Reproduce**

Create a new plugin using the typescript flag.
**Expected behavior**

No errors when building the starter code.

**Comment by maribethb** [comment]
Interestingly, I can't reproduce this on build. I don't know why, since lint is part of the build pipeline. But nevertheless there are lint errors/warnings with the template code which I'm opening a PR for
