### ISSUE TITLE
`npm run test` does not delete unused files in `dist`

### ISSUE THREAD

**Issue by NeilFraser** [rachel-fenichel/blockly-samples#1675]
When rerunning tests, if a source file was deleted, its copy in `dist` is not removed.  No apparent command will delete this file.

It's probable that this applies to any build, not just tests.  This might also affect Blockly, not just Blockly Samples.  Haven't checked either.

Proposal: Rather than create a new 'clean' command that we have to remember when things get wonky, I'd propose that any build would first clear out the build directory.  Though this might undermine the principle of progressive compilation.  Maybe undermining is not a problem for Blockly Samples which are quite small (discounting node modules).

Background: a rogue file in the dist directory was making all tests pass, regardless of the contents of the sources.  Lost a day trying to figure out what was happening.

**Comment by maribethb** [comment]
There's a parameter we can use in the webpack config to have it clear the old build before starting a new one.
