### ISSUE TITLE
plugin-workspace-search use centerOnBlock for scrollToVisible_

### ISSUE THREAD

**Issue by mrkprdo** [rachel-fenichel/blockly-samples#1677]
Can we use this to move the block to the center of the workspace:
https://developers.google.com/blockly/reference/js/blockly.workspacesvg_class.centeronblock_1_method.md
For the scrollToVisible() call:
https://github.com/google/blockly-samples/blob/master/plugins/workspace-search/src/WorkspaceSearch.js#L634

**Comment by BeksOmega** [comment]
Hello @mrkprdo , thanks for filing this :D Is this a feature request to center blocks when navigating to them via workspace search? or is this a bug with the current implementation, and blocks aren't getting scrolled into the workspace?

Just wondering because if it's a feature request we might want to provide it as a config option rather than centering by default!

**Comment by mrkprdo** [comment]
Hi @BeksOmega,
Not totally sure on this since i just recently use this plugin. But the current workflow is that after searching blocks is done, navigating to those blocks does not show up in the center of the workspace but rather it shows up on the edge somewhere an really hard to notice.
I have made PR #1678 on this that somehow satisfies the "found" blocks to be in the center when navigating thru them.

**Comment by BeksOmega** [comment]
Sweet! I've added the `triage` label to this so the peeps who make the product decisions can take a look at this next week and get back to you =)

**Comment by maribethb** [comment]
We think it's fine to just change the logic to center on the block without needing to provide a config option. It would also let us delete a bunch of code that we already have logic for in core. I don't feel too strongly about this though if you disagree Beka.

**Comment by BeksOmega** [comment]
Nope that sgtm! Just wanted to make sure it didn't fall into the same category of behavioral change as having the backpack indicate if it contains blocks or not.
