### ISSUE TITLE
share procedure plugin use with cross tab copy paste plugin together make a demo?

### ISSUE THREAD

**Issue by mlzboy** [rachel-fenichel/blockly-samples#1690]
**Category**:
 - Examples

**Component**

share procedure plugin 
cross tab copy paste plugin

**Is your feature request related to a problem? Please describe.**

share procedure plugin there is a test demo show at ‘plugin’ folder,it give us a demo how to use share procedure in two workspace,
at same page,but most time we use share procedure is cross multiple page workspace,so the cross tab copy paste plugin is very useful,but I tested if i copy the call function block in one workspace and paste it to another workspace,it will paste the definiation
block to new workspace either. 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by BeksOmega** [comment]
Hello, thank you for your question :D Currently copying and pasting procedures between workspaces does not work :/ see https://github.com/google/blockly/issues/6846 for details. I'm going go ahead and close this issue so we can keep the conversation centralized over https://github.com/google/blockly/issues/6846 ! Thank you again =)
