### ISSUE TITLE
Add configurable serializer behavior for backpack

### ISSUE THREAD

**Issue by maribethb** [rachel-fenichel/blockly-samples#1826]
**Category**

 - Plugins

**Component**

workspace-backpack

**Describe the bug**

Not everyone wants the backpack to be serialized alongside the workspace. The plugin should provide an option to skip registering the serializer.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

https://groups.google.com/g/blockly/c/VucAkiCGnHE

**Comment by johnnyoshika** [comment]
Would be happy to contribute a PR for this. Can you help me identify where the configurable hook would be? I can't use backpackOptions](https://github.com/google/blockly-samples/blob/54a6ee64ff03b6cb11e070d130a88d656aeced22/plugins/workspace-backpack/src/backpack.js#L32), as it gets passed into the constructor of Backpack and the [backpack serializer](https://github.com/google/blockly-samples/blob/54a6ee64ff03b6cb11e070d130a88d656aeced22/plugins/workspace-backpack/src/backpack.js#L893-L895) will already be registered by then. Would I need to set an option before the backpack plugin is imported?

**Comment by maribethb** [comment]
Thanks, Johnny, that would be great. I think instead of registering it at the bottom of `backpack.js` you can register it in the constructor unless some option is set. The default should be that it is registered unless an option says not to, so we can avoid (another) breaking change.

Since registering serializers is global but the backpack might be initialized multiple times (for multiple workspaces) you can check if it has already been registered with `Blockly.registry.hasItem(Blockly.registry.Type.SERIALIZER, 'backpack')` before registering.

**Comment by johnnyoshika** [comment]
Thanks @maribethb! How about an option called `skipSerializerRegistration`? Default will be `false`.

For multiple backpack instances, what should the behavior be if different values of `skipSerializerRegistration` are set for the different instances?

Example:

```
const backpack1 = new Backpack(workspace1, {skipSerializerRegistration: false});
const backpack2 = new Backpack(workspace2, {skipSerializerRegistration: true});
const backpack3 = new Backpack(workspace3, {skipSerializerRegistration: false});
```

Should we make it so the last one wins? i.e. in the example above, the serializer will be registered, then unregistered, then registered again. So the final outcome will be a registered serializer.

**Comment by johnnyoshika** [comment]
Upon thinking about this further, if we decide to use the name `skipSerializerRegistration`, I think it should only ever skip registration and never unregister. In other words, if `skipSerializerRegistration` is ever `false` (whether in the first instance of Backpack or last), the serializer should be registered.

Example:

```
const backpack1 = new Backpack(workspace1, {skipSerializerRegistration: false}); // Serializer gets registered here
const backpack2 = new Backpack(workspace2, {skipSerializerRegistration: true});
const backpack3 = new Backpack(workspace3, {skipSerializerRegistration: true});
```

The final outcome is a registered serializer. Let me know what you think.

**Comment by maribethb** [comment]
Yes, we should never unregister the serializer. Someone may want to register their own serializer under the same name, and we shouldn't get in the way of that. Just register it if the option is false or not provided, and do nothing if it is true.

**Comment by johnnyoshika** [comment]
@maribethb I wrote the code for this enhancement but I'm having trouble testing it with `npm link`. I believe the problem is the peer dependency of blockly. When I don't use `npm link`, workspace-backpack picks up the same blockly@10.0.2 as the host project and everything works as expected. When I use `npm link`, workspace-backpack uses a different blockly instance (version 10.0.0) and the backpack doesn't work. Even when I try to match version numbers, it still seems like workspace-backpack is using its own instance of blockly.

As a result of multiple blockly instances running, this condition is always false when I use `npm link`, whereas it's true on drag enter when I don't use `npm link`:

https://github.com/google/blockly-samples/blob/0222d035135cb3425fc8d75ad9266b8951bed6c7/plugins/workspace-backpack/src/backpack.js#L714

Here are my outputs for `npm ls blockly`:

`npm ls blockly` without npm link:

![image](https://github.com/google/blockly-samples/assets/504505/13007138-614a-47f4-aede-3ad604e7060c)

`npm ls blockly` with npm link:

![image](https://github.com/google/blockly-samples/assets/504505/e7027cf7-9990-4eba-83fa-a80f0fe56023)

This problem may be exacerbated by the fact that I'm testing inside a large monorepo. If you don't immediately see a solution to this, I'll test it in a small simple project instead in hopes that npm link will honor the peer dependency.

**Comment by maribethb** [comment]
So you could maybe test this adequately with just using the plugin's test page and not trying to link it into another project. You can modify the `test/index.js` and run that with `npm run start`

Otherwise, the way we've gotten around this in the past is to trick npm's module resolution algorithm. Link the plugin to your project. Install blockly in a parent directory that contains both the plugin and the test repo (doesn't have to be a direct parent, just some common ancestor of both directories). Then manually delete blockly out of the plugin's `node_modules` and out of the test repo's `node_modules`. That way when npm is searching for the `blockly` resolution it only finds the one in the parent directory.

If you're not using the test page for the plugin, you could also try just removing the devDependency on `@blockly/dev-tools` which is probably the package bringing in the extra copy of blockly.

**Comment by johnnyoshika** [comment]
Thanks @maribethb, I'll try `test/index.js` - it's good to know about that option.

I was able to find a fix to my problem and I'll leave my solution here so I can reference it in the future...

Source of the problem (excerpt from https://stackoverflow.com/a/31170775/188740):

> This issue usually arises when using npm link. A linked module will resolve its dependencies in its own module tree, which is different from the one of the module that required it. As such, the npm link command installs peerDependencies as well as dependencies.

I'm using Vite when testing, so I was able to force `workspace-backpack` to use the host `blockly` package by creating an alias in vite.config.ts.

```
resolve: {
  alias: {
    blockly: path.resolve('./node_modules/blockly'),
  },
},
```

or in my case, I'm testing inside a monorepo, so it's:

```
resolve: {
  alias: {
    blockly: path.resolve('../../node_modules/blockly'),
  },
},
```

**Comment by maribethb** [comment]
Awesome, glad you figured out a saner way to get the npm module resolution to do what you wanted! I'll take a look at your PR shortly. Thanks!
