### ISSUE TITLE
backpack plugin incompatible with existing xml data

### ISSUE THREAD

**Issue by maribethb** [rachel-fenichel/blockly-samples#1827]
**Category**

 - Plugins

**Component**

workspace-backpack

**Describe the bug**

The backpack plugin was recently updated to save its contents in json instead of xml. We correctly marked this as a breaking change, but we didn't provide any help for developers who were already using xml and manually loading it in using `setContents`. There is no clear upgrade path for anyone who was using the old version of the backpack.

**To Reproduce**

Try to use the backpack v5 with old xml data.

**Expected behavior**

The backpack can deserialize old xml and convert it to json.

**Screenshots**

**Additional context**

https://groups.google.com/g/blockly/c/VS_UBEFkPsM

**Comment by johnnyoshika** [comment]
@maribethb I can contribute a PR. What would be the desired behavior if XML is used to hydrate the backpack?

For example, I can update [setContents()](https://github.com/google/blockly-samples/blob/871a5a1e9cd12b59755e11a02a11733f6ddf95e0/plugins/workspace-backpack/src/backpack.js#L552-L556) to detect XML and convert to JSON using the technique [here](https://groups.google.com/g/blockly/c/VS_UBEFkPsM/m/fBuaXCd2AAAJ) before setting `this.contents_`. Will it be OK if [getContents()](https://github.com/google/blockly-samples/blob/871a5a1e9cd12b59755e11a02a11733f6ddf95e0/plugins/workspace-backpack/src/backpack.js#L426-L429) returns JSON even if XML was used to hydrate the backpack?

**Comment by maribethb** [comment]
@BeksOmega Do you have thoughts on this? My first thought was that `setContents` should work like `flyout.show` works in core, where you can hand it json or xml and it handles either. But if we did that we'd have to keep around the logic that was removed that dealt with merging duplicates in xml, in addition to the new functions in json. Maybe a one time conversion from xml to json is cleaner.

I do think it's fine if `getContents` returns JSON even if xml was provided originally. The main goal is to support folks using an earlier version of the plugin to migrate to the current version, rather than focusing on allowing xml as a fully supported option. Since the xml data in the backpack already was not serialized by blockly, it would be fine if e.g. someone is still using xml serialization for the workspace data, and then separately saving the backpack data as json.

**Comment by BeksOmega** [comment]
I agree that the goal is to support folks migrating, rather than making XML a fully supported serialization format! So I think supporting inputting XML or JSON, but only outputting JSON is a good approach =)

**Comment by johnnyoshika** [comment]
@maribethb This can be closed now, as the issue has been fixed here: https://github.com/google/blockly-samples/pull/1835
