### ISSUE TITLE
Backpack plugin uses opposite scrollbars for position method

### ISSUE THREAD

**Issue by cesarades** [rachel-fenichel/blockly-samples#1828]
**Category**
Plugin

**Component**
Backpack

**Describe the bug**
The following code uses the horizontal method for the vertical scrollbar and vice versa. It also does not account for if the scrollbar is visible or not. For example it should also check for ```this.primaryWorkspace.scrollbar.isVisible()```
```
const hasVerticalScrollbars = this.primaryWorkspace.scrollbar &&
      this.primaryWorkspace.scrollbar.canScrollHorizontally();
const hasHorizontalScrollbars = this.primaryWorkspace.scrollbar &&
      this.primaryWorkspace.scrollbar.canScrollVertically();
```

**To Reproduce**
Set the vertical scrollbar to false. 
When positioning the backpack it still offsets as if it is there.

**Expected behavior**
If there is no vertical bar, the backpack should not account for it. Same with the horizontal one.

**Screenshots**

**Additional context**
This was solved similarly in the minimap plugin #1824

**Comment by maribethb** [comment]
@cesarades you up for fixing this one when you have time since you fixed it in the minimap already? Maybe want to wait a week since someone else is also poking the backpack plugin right now. Thanks!

**Comment by cesarades** [comment]
Yes, I most definitely could. I'll do it at the end of next week then.
