### ISSUE TITLE
Make the dynamic connections plugin serialize to the same format as blocks in core

### ISSUE THREAD

**Issue by BeksOmega** [rachel-fenichel/blockly-samples#1843]
**Category**

 - Plugins

**Component**

block-dynamic-connections

**Is your feature request related to a problem? Please describe.**

Currently the dynamic connections plugin serializes to a format that is not compatible with the blocks in core. This means that if you start using the dynamic connections plugin, you can never pull it out and go back to the default way of handling mutations.

**Describe the solution you'd like**

Have the dynamic connections plugin serialize to the same save format as blocks in core.

**Describe alternatives you've considered**

N/A

**Additional context**

App Inventor want to use this plugin, but they want to be able to quickly and easily roll it back if anything breaks. Plus they have a lot of analysis tools tha trely on the current save format. This would break those.

**Comment by maribethb** [comment]
This is reasonable, but the plugin needs to be able to continue deserializing from its old format too, so that folks already using it are not broken.
