### ISSUE TITLE
Webpack libraryTarget config option is deprecated

### ISSUE THREAD

**Issue by mark-friedman** [rachel-fenichel/blockly-samples#1849]
**Category**

Plugins

**Component**

dev-scripts

**Describe the bug**

This is just a heads-up that it seems that webpack has deprecated the `output.libraryTarget` config option in favor of the `output.library.type` option.  You can see the deprecation warning in their config file documentation [here](https://webpack.js.org/configuration/output/#outputlibrarytarget).  The dev-scripts code that needs to be fixed is in [dev-scripts/config/webpack.config.js](../blob/master/plugins/dev-scripts/config/webpack.config.js#L79).  It looks like the fix is to replace:
```
      libraryTarget: 'umd',
```
with
```
      library: {
        type: 'umd',
      },
```

**Comment by rachel-fenichel** [comment]
Looking into this: the option we're using will be deprecated, but has not yet been removed.

I can't tell if the correct change is to 
```
      library: {
        type: 'umd',
      },
```

or 

```
      library: {
        name: 'Blockly',
        type: 'umd',
      },
```

[This part of the documentation](https://webpack.js.org/configuration/output/#type-umd) says that there is a meaningful difference between the two.
