### ISSUE TITLE
Deprecate renderer-inline-row-separators

### ISSUE THREAD

**Issue by johnnesky** [rachel-fenichel/blockly-samples#1854]
**Category**
Plugins

**Component**
https://github.com/google/blockly-samples/tree/master/plugins/renderer-inline-row-separators

**Describe the bug**
It will be obsolete and should be deprecated after https://github.com/google/blockly/pull/6944 is published!

**Comment by maribethb** [comment]
@johnnesky can you update the README for the plugin with instructions on how to use the new feature? I don't think you'll have permissions to actually run the deprecate command but one of us can handle that.

**Comment by BeksOmega** [comment]
Done with v10.2!
