### ISSUE TITLE
Make it easier to subclass `ObservableParameterModel`

### ISSUE THREAD

**Issue by maribethb** [rachel-fenichel/blockly-samples#1861]
**Category**
 - Plugins

**Component**

block-shareable-procedures

**Is your feature request related to a problem? Please describe.**

It's difficult to add support for typed parameter models. Part of the problem is in core, but part of the problem is that the constructor for `ObservableParameterModel` always creates an untyped variable. Even after we fix https://github.com/google/blockly/issues/7397 you still wouldn't be able to subclass the `ObservableParameterModel` due to the requirement of calling `super` in the constructor, which would create an untyped variable. This is a pretty useful class and we should make it easy for developers to subclass it.

**Describe the solution you'd like**

Move the [part of the constructor that creates a variable](https://github.com/google/blockly-samples/blob/cd570706cb21d31c6bbf64f3b6597402565a1330/plugins/block-shareable-procedures/src/observable_parameter_model.ts#L44) to a protected method called `createBackingVariable` (or similar). This method can be overridden by subclasses so that a typed variable could be created instead of untyped.

**Describe alternatives you've considered**

**Additional context**

**Comment by BeksOmega** [comment]
@thebedigupta could you comment here so I can assign you to this issue?

**Comment by thebedigupta** [comment]
hey @BeksOmega I want to solve this problem

**Comment by shivalipatel6** [comment]
Hi can I take this on?

**Comment by BeksOmega** [comment]
@shivalipatel6 Go for it =)

**Comment by shivalipatel6** [comment]
@BeksOmega Hi, I have started to work on this issue when I realized I am not exactly sure how to test my changes. I am pretty sure I have correctly implemented createBackingVariable, but I am not exactly sure what I am supposed to be testing for when I run the tests in blockSharableProcedure. When I run the test files I get this: 
![createBackingVariableTest](https://github.com/google/blockly-samples/assets/56765670/a9423cac-d339-49b0-bd07-7ea516812bdd)
So I know I haven't made a breaking change. Would you mind passing along some advice on testing this? Thanks!

**Comment by BeksOmega** [comment]
This change probably doesn't need much testing =) Could you put up a PR so I can give it a look? If it needs manual or automated tests from there I'll let you know!
