### ISSUE TITLE
Build a custom generator is codelab is broken

### ISSUE THREAD

**Issue by BenWhite-Price** [rachel-fenichel/blockly-samples#1866]
**Category**
 - Codelabs

**Component**

**Describe the bug**
The instructions given in [this codelab](https://blocklycodelabs.dev/codelabs/custom-generator/index.html) lead to code that won't run, specifically in the generator json.js file. 

**To Reproduce**

1. Begin the codelab
2. Follow along until Step 6: Member blocks
3. Run the code with developer tools open
4. See error in console 

**Expected behavior**

I expect the tutorial to work. 

**Screenshots**
![image](https://github.com/google/blockly-samples/assets/112510675/339b9c1a-a3fa-4d3c-9d27-44e413430137)

**Additional context**
I was able to fix this through trial and error. 
To get the block generators to work, I changed 
```
jsonGenerator.forBlock['logic_boolean'] = function(block) {
  const code = (block.getFieldValue('BOOL') === 'TRUE') ? 'true' : 'false';
  return [code, Order.ATOMIC];
};
```
To be 
```
jsonGenerator['logic_boolean'] = function(block) {
    const code = (block.getFieldValue('BOOL') === 'TRUE') ? 'true' : 'false';
    return [code, Order.ATOMIC];
};
```

I also had to change the ones with `generator` as an argument, from this:
```
jsonGenerator.forBlock['member'] = function(block, generator) {
  const name = block.getFieldValue('MEMBER_NAME');
  const value = generator.valueToCode(
      block, 'MEMBER_VALUE', Order.ATOMIC);
  const code = `"${name}": ${value}`;
  return code;
};
```
to this:
```
jsonGenerator['member'] = function(block) {
    const name = block.getFieldValue('MEMBER_NAME');
    const value = jsonGenerator.valueToCode(block, 'MEMBER_VALUE', Order.ATOMIC);
    const code = `"${name}": ${value}`;
    return code;
};
```

With those changes applied across all the generator functions, my code works. 

Please update the codelab for future users

**Comment by maribethb** [comment]
Hello, what version of Blockly are you running with the codelab? The codelab is updated to work with Blockly v10, which would not throw this error, and should be the version installed with the latest version of the `create-package` script.

**Comment by rzl** [comment]
i have same problem.  
> update Blockly v10, forBlock property work well

```bash
C:\Users\11200>node -v
v14.19.3

C:\Users\11200>npm -v
6.14.17

C:\Users\11200>npx -v
6.14.17
```
 
1 Run npx @blockly/create-package app custom-generator-codelab

2 see package.json file ，（It should be a version issue，version 9 generator don't has a property called forBlock, ）

```json
 "dependencies": {
    "blockly": "^9.2.0"
  }
```

3 source file custom-generator-codelab\src\generators\javascript.js 
```javascript
import {javascriptGenerator} from 'blockly/javascript';

// Export all the code generators for our custom blocks,
// but don't register them with Blockly yet.
// This file has no side effects!
export const generator = Object.create(null);

generator['add_text'] = function(block) {
  const text = javascriptGenerator.valueToCode(block, 'TEXT',
      javascriptGenerator.ORDER_NONE) || '\'\'';
  const color = javascriptGenerator.valueToCode(block, 'COLOR',
      javascriptGenerator.ORDER_ATOMIC) || '\'#ffffff\'';

  const addText = javascriptGenerator.provideFunction_(
      'addText',
      ['function ' + javascriptGenerator.FUNCTION_NAME_PLACEHOLDER_ +
          '(text, color) {',
      '  // Add text to the output area.',
      '  const outputDiv = document.getElementById(\'output\');',
      '  const textEl = document.createElement(\'p\');',
      '  textEl.innerText = text;',
      '  textEl.style.color = color;',
      '  outputDiv.appendChild(textEl);',
      '}']);
    // Generate the function call for this block.
  const code = `${addText}(${text}, ${color});\n`;
  return code;
};
```

4 source file index.js

```javascript
import {javascriptGenerator} from 'blockly/javascript';
......
Object.assign(javascriptGenerator, generator);
......
```

**Comment by gonfunko** [comment]
The create-package tool has been updated to use Blockly 10, so this should now be resolved. You may need to clear the npx cache first though, since the old version of create-package may be cached.
