### ISSUE TITLE
How does one use plugins from unpkg?

### ISSUE THREAD

**Issue by Nolram12345** [rachel-fenichel/blockly-samples#1870]
Hello,
I am currently trying to use blockly in an NPM-less setup. Using NPM is not an option, and therefore I have opted to use the unpkg hosted files as per the documentation. 
However, I am struggling to figure out how to use plugins like this; and specifically the [@blockly/block-shareable-procedures](https://unpkg.com/browse/@blockly/block-shareable-procedures@3.0.3/) plugin. 

Any guidance would be appreciated.

**Comment by maribethb** [comment]
Hello,

Apologies for the delay in response. We are not set up to answer questions on GitHub Issues and only use it for issue tracking. Could you please follow up with this question on our [developer support forum](https://groups.google.com/g/blockly)?  If you post on the forum, someone will get back to you within 2 business days.

To answer your question: if you load a package with unpkg then anything exported in the `src/index.js` file will be loaded into the global scope. So once you load, e.g.

`<script src="https://unpkg.com/@blockly/block-shareable-procedures@3.0.3"></script>` onto your page, you now have access to anything in the API e.g. `unregisterProcedureBlocks` in the global scope and can be used. For the API, you can refer to the README of a plugin for more detailed instructions.

If you have follow up questions, please do post them in the forum, as they will likely be missed if you respond to this issue. Thanks!
