### ISSUE TITLE
Normalize tsconfig.json files

### ISSUE THREAD

**Issue by gonfunko** [rachel-fenichel/blockly-samples#1871]
We use a variety of settings in the tsconfig.json files in the plugins. We should standardize these to be consistent across all the plugins and consistent with our browser support goals. In particular the newer plugins (toolbox-search, some that have been converted to TS) use more modern settings than older plugins.

**Comment by BeksOmega** [comment]
The tsconfig in the dev-create templates should also be updated. In addition to normalizing the existing config parameters, we should add:
```
"declaration": true,
"declarationMap": true,
```

And update the package.json files to include:
```
"types": "./dist/index.d.ts"
```

**Comment by alicialics** [comment]
I looked at one particular plugin: [workspace-backpack](https://github.com/google/blockly-samples/blob/master/plugins/workspace-backpack/tsconfig.json) and there are a couple of issues.
- The `outDir` in `tsconfig.json` set to `build`.  This is important as it affects where `d.ts` files are generated.  I don't see `build` being included in the [npm package](https://unpkg.com/browse/@blockly/workspace-backpack@5.2.2/) as the `package.json`'s `files` property only includes `["src", "dist"]` (`src` can probably be removed).  In any case `outDir` should probably be standardized to `dist`
- In `package.json` setting `"types": "./dist/index.d.ts"` is still incorrect.  The declarations are being generated in a subdirectory under `outdir`: ie ` "./dist/src/index.d.ts"`

I took a glance and it seems most typescript plugins does not have the correct settings mentioned above.  cc @maribethb

**Comment by alicialics** [comment]
Also I would recommend extending a base tsconfig.json for plugin development so it should be consistent with all plugins published by blockly team: https://www.typescriptlang.org/tsconfig#extends

**Comment by BeksOmega** [comment]
Hiya thanks for digging into this! We realized last Friday as we were testing the OSD branch that there were still a lot of things wrong with the tsconfig (e.g. the `outDir` being wrong) and Maribeth is working on a bulk fix!

I'll leave it to her to give you more details if she has any, but just wanted to say thank you for the comment and let you know we're investigating =)

**Comment by BeksOmega** [comment]
Just noticed that Zoey linked this from a forum post about the workspace backpack plugin not loading. Seems the misconfigurations she listed are blocking people from ~installing~ using the plugins: https://groups.google.com/g/blockly/c/tOSs0AT5-xY/m/UydAvLV3AQAJ
