### ISSUE TITLE
Minimap focus region not updated on refresh

### ISSUE THREAD

**Issue by BeksOmega** [rachel-fenichel/blockly-samples#1878]
**Category**

 - Plugins

**Component**

workspace-minimap

**Describe the bug**

When you reload a page with the minimap on it, the content of the minimap matches the main workspace, but the focus region is not updated to show the actual focused region.

**To Reproduce**

1. Go to the minimap demo.
2. Add some blocks to the workspace such that you can see the focused region.
3. Refresh the page.
4. Observed how the focused region is not updated.

**Expected behavior**

The focused region should be updated.

**Screenshots**

N/A

**Additional context**

I think something is up with the minimap's scale? I did some debugging and it didn't seem to be acurrate durring loading.

**Comment by maribethb** [comment]
@cesarades if you're interested in a follow up bug!

**Comment by cesarades** [comment]
Fixed it in this PR #1890
