### ISSUE TITLE
continuous-toolbox

### ISSUE THREAD

**Issue by CaffeMrDe** [rachel-fenichel/blockly-samples#1881]
**Category**

**Component**

Set blocklyFlyoutBackground to a fixed length and the block in the toolbox does not change with the size of the workspace.
In the current situation, scrolling the mouse will make the scale of the workspace larger or smaller, and the block larger or smaller. As a result, blocklyFlyoutBackground can also become larger or smaller

**Describe the solution you'd like**

Provides an externally configured interface

![image](https://github.com/google/blockly-samples/assets/35086726/41aed853-345c-4146-be1f-2ca18d40fdbc)

**Describe alternatives you've considered**

**Additional context**

**Comment by maribethb** [comment]
Hello,

I think you are asking for the ability to make the flyout zoom level independent of the workspace zoom level? By default, the zoom level for the flyout matches the workspace. If you want to change that, you can use a custom flyout class and override the `getFlyoutScale` [method](https://developers.google.com/blockly/reference/js/blockly.flyout_class.getflyoutscale_1_method.md) to return the zoom level you want. To use that with the continuous toolbox, you could subclass the flyout class provided in the plugin.

Does that answer your question? I'm not sure what you mean by setting the flyout background to a fixed length. If that doesn't address your question, could you please clarify or restate your feature request? Thanks!

**Comment by CaffeMrDe** [comment]
Thank you so much! I followed your method to really get the desired effect I wanted. I do want the Flyouty Toolbox to be independent of the workspace.
