### ISSUE TITLE
How do I generate the code I want in /plugins/block-plus-minus?

### ISSUE THREAD

**Issue by AdwardWong** [rachel-fenichel/blockly-samples#1882]
**Category**
 - Plugins

**Component**
block plus-minus

**Describe the bug**

How do I generate the code I want in /plugins/block-plus-minus?, as shown in the image below.

<img width="696" alt="截屏2023-08-30 17 31 57" src="https://github.com/google/blockly-samples/assets/13374858/5832e175-a3d9-4f26-a825-c2d2e854007a">

**To Reproduce**

1. install "block plus-minus"
2. run "/plugins/block plus-minus"
3. try to generate custom format code.
4.The relevant API could not be found.

<img width="1082" alt="截屏2023-08-30 17 36 40" src="https://github.com/google/blockly-samples/assets/13374858/bb61748e-1bea-4067-a65e-2a1c169272ed">

**Expected behavior**
“block-plus-minus” can generate custom formatted code.

**Comment by maribethb** [comment]
Hello! 

I am not sure how to answer your question. It looks like you are using the blocks-plus-minus plugin and it is generating code for the `if` statement correctly. And separately, you have defined a block called `stock_fetch_price`, but I'm not sure what that has to do with the blocks-plus-minus plugin. Would you like to use a similar UI with plus and minus buttons in your custom block?

Could you please follow up with this question on our [developer support forum](https://groups.google.com/g/blockly)? We are not set up to answer questions on GitHub Issues and only use it for issue tracking. If you post on the forum, someone will get back to you within 2 business days.

Thank you!
