### ISSUE TITLE
Undoing delete of procedure def causes crash when caller exists

### ISSUE THREAD

**Issue by laurensvalk** [rachel-fenichel/blockly-samples#1891]
**Category**

 - Plugins

**Component**

`block-shareable-procedures` `3.0.5`

**Describe the bug**

Deleting a procedure definition when a caller is present leads to a crash when undoing the delete.

**To Reproduce**

The easiest way is to add `block-shareable-procedures` to the playground.

(This bug not happen in the `block-shareable-procedures` demo where undo actions are set to 0.)

Steps:

```
cd plugins/dev-tools
npm install
npm add "@blockly/block-shareable-procedures"
```

Activate plugin in playground:
```diff
diff --git a/plugins/dev-tools/test/index.js b/plugins/dev-tools/test/index.js
index 15c40817..2a0ea1bd 100644
--- a/plugins/dev-tools/test/index.js
+++ b/plugins/dev-tools/test/index.js
@@ -12,6 +12,17 @@
 import * as Blockly from 'blockly';
 import {createPlayground, toolboxCategories} from '../src/index';
 
+const {
+  blocks,
+  unregisterProcedureBlocks,
+  registerProcedureSerializer,
+} = require('@blockly/block-shareable-procedures');
+
+unregisterProcedureBlocks();
+Blockly.common.defineBlocks(blocks);
+
+registerProcedureSerializer();
+
 /**
  * Create a workspace.
  * @param {HTMLElement} blocklyDiv The blockly container div.
```

See video below for the reproduction steps:
- Create a procedure with some arguments.
- Add a caller to the workspace.
- Delete the procedure definition (which will also delete caller)
- Press undo
- There is one error immediately, and more pup up each time it tries to access the missing procedure model.

**Expected behavior**

Restore procedure def/caller/model without crashing.

**Screenshots**

https://github.com/google/blockly-samples/assets/12326241/2f7027b1-0c30-4acf-97d3-c1bda5132ee7

**Additional context**

It appears that `destroy()` in one of the mixins will call `this.workspace.getProcedureMap().delete(this.getProcedureModel().getId());`, but it doesn't get restored on undo. (Or perhaps it is restored, but not in the right order?)

**Comment by rachel-fenichel** [comment]
@BeksOmega since this is related to procedures, can you take a look and decide if it's fixable this quarter?

**Comment by BeksOmega** [comment]
Caused by https://github.com/google/blockly-samples/pull/1874. I disabled recording undo at the events_procedure_base level when I should have just disabled it at the event_procedure_parameter_base level. Fix incoming!

**Comment by laurensvalk** [comment]
Thanks!
