### ISSUE TITLE
Publish `.d.ts` TypeScript declaration files for plugins

### ISSUE THREAD

**Issue by cpcallen** [rachel-fenichel/blockly-samples#1892]
**Category**

 - Plugins

**Component**

All—at least all that are written in TypeScript—most probably via modifications to `dev-scripts`.

**Is your feature request related to a problem? Please describe.**

Users in the forum [report issues with their editors and/or builds complaining about missing type declarations](https://groups.google.com/g/blockly/c/8MxXhpFAR8c/m/2vwOsY17AgAJ?utm_medium=email&utm_source=footer).

**Describe the solution you'd like**

For the plugins that are built from TypeScript source, we should generate a `dist/index.d.ts` file and ensure it is included in the published NPM package.

**Describe alternatives you've considered**

* We could… just not.  But it seems like it should be easy to do and be helpful to developers using plugins from TypeScript.
* On the other hand we could autogenerate `.d.ts` files for TS-sourced plugins _and_ hand roll `.d.ts` files or try to use tsickle to translate Closure type declarations for those that are still written in JS—but that seems like a lot of work that might better be spent on porting those plugins to TypeScript.

**Additional context**

It's not immediately obvious whether this can be done merely by modifying `plugins/dev-scripts/config/webpack.config.js` or whether we will additionally have to update all of the `plugins/*/tsconfig.json` files (plus `dev-create/templates/typescript-*/template/tsconfig.json`).

**Comment by laurensvalk** [comment]
This would be very useful.

I wonder if it is sufficient to set `"declaration": true` for the `tsconfig.json` files of the ts-based plugins. With the following patch, running `build`  will produce the `d.ts` files in the `src` output.

```diff
diff --git a/plugins/block-shareable-procedures/package.json b/plugins/block-shareable-procedures/package.json
index 06f56f7d..02e6f13e 100644
--- a/plugins/block-shareable-procedures/package.json
+++ b/plugins/block-shareable-procedures/package.json
@@ -15,6 +15,7 @@
   "main": "./dist/index.js",
   "module": "./src/index.js",
   "unpkg": "./dist/index.js",
+  "types": "./src/index.d.ts",
   "author": "Blockly Team",
   "keywords": [
     "blockly",
diff --git a/plugins/block-shareable-procedures/tsconfig.json b/plugins/block-shareable-procedures/tsconfig.json
index 6e26e186..42844cb6 100644
--- a/plugins/block-shareable-procedures/tsconfig.json
+++ b/plugins/block-shareable-procedures/tsconfig.json
@@ -5,7 +5,8 @@
     "allowJs": true,
     "sourceMap": true,
     "lib": ["es6", "dom"],
-    "moduleResolution": "node"
+    "moduleResolution": "node",
+    "declaration": true,
   },
   "include": [
     "src", "test"
```


```
cd plugins/block-shareable-procedures
npm run build
```

**Comment by BeksOmega** [comment]
I discussed this briefly with Maribeth last Thursday after seeing the forum post. We decided to split this into individual issues for osd, but I didn't follow up with it because I was doing docs Friday.

So I'm going to close this issue and split it up by plugin.

**Comment by BeksOmega** [comment]
Added a comment to https://github.com/google/blockly-samples/issues/1871 for tracking dev-create updates.
