### ISSUE TITLE
Caller inputs disconnect on reload if caller serialized above definition

### ISSUE THREAD

**Issue by laurensvalk** [rachel-fenichel/blockly-samples#1893]
**Category**

 - Plugins

**Component**

`block-shareable-procedures` `3.0.5` with Blockly `10.1.3`.

I think this did not occur with Blockly 10, but I have only verified 

**Describe the bug**

Loading a project will disconnect and bump caller inputs if it is serialized above the definition.

I think this might only affect the JSON case where the order is based on appending instead of workspace placement.

**To Reproduce**

The easiest way is to add `block-shareable-procedures` to the playground.

Steps:

```
cd plugins/dev-tools
npm install
npm add "@blockly/block-shareable-procedures"   # Also note versions above just in case
```

Activate plugin in playground:
```diff
diff --git a/plugins/dev-tools/test/index.js b/plugins/dev-tools/test/index.js
index 15c40817..2a0ea1bd 100644
--- a/plugins/dev-tools/test/index.js
+++ b/plugins/dev-tools/test/index.js
@@ -12,6 +12,17 @@
 import * as Blockly from 'blockly';
 import {createPlayground, toolboxCategories} from '../src/index';
 
+const {
+  blocks,
+  unregisterProcedureBlocks,
+  registerProcedureSerializer,
+} = require('@blockly/block-shareable-procedures');
+
+unregisterProcedureBlocks();
+Blockly.common.defineBlocks(blocks);
+
+registerProcedureSerializer();
+
 /**
  * Create a workspace.
  * @param {HTMLElement} blocklyDiv The blockly container div.
```

See video below for the reproduction steps:
- **Start** with any statement block, e.g. repeat.
- Create a procedure with some arguments.
- Add a caller to the workspace, attach it to previously mentioned statement. (JSON should now have it _above_ procedure def)
- Attach some input blocks
- Press refresh to reload
- The input block will disconnect

**Expected behavior**

Not disconnect inputs.

**Screenshots**

https://github.com/google/blockly-samples/assets/12326241/dd016a80-36ec-4af1-95ac-20a683b2ddec

**Comment by rachel-fenichel** [comment]
@BeksOmega since this is related to procedures, can you take a look and decide if it's fixable this quarter?

**Comment by BeksOmega** [comment]
I think this is probably actually https://github.com/google/blockly-samples/issues/1049. The advanced playground uses XML on reload, which doesn't include the procedure models.

@laurensvalk if you try this with JSON serialization, does it still reproduce? You can create a button in your test page that serializes to and loads back in JSON. [Edit: or just test it in the browser console]

**Comment by laurensvalk** [comment]
Thanks @BeksOmega. This appears to happen with JSON serialization too. 

I first noticed this in my own application, which does something like #1049 already because I use some features that are not supported by the XML loader.

**Comment by BeksOmega** [comment]
Ah ok, I wasn't seeing the issue reproduce because I was only adding a single parameter to the procedure. Now able to reproduce!

Root caused to https://github.com/google/blockly-samples/pull/1865 which was fixing https://github.com/google/blockly-samples/issues/1859
