### ISSUE TITLE
Public demo of field-colour-hsv-sliders does not launch

### ISSUE THREAD

**Issue by laurensvalk** [rachel-fenichel/blockly-samples#1894]
**Category**

 - Plugins

**Component**

`field-colour-hsv-sliders`

**Describe the bug**

The public demo has `Uncaught Error: Cannot find module '@blockly/field-colour'` and does not launch the demo.

**To Reproduce**

Open https://google.github.io/blockly-samples/plugins/field-colour-hsv-sliders/test/index.html

**Expected behavior**

Working demo.

**Screenshots**

![image](https://github.com/google/blockly-samples/assets/12326241/11f430d9-4918-40c1-a441-00ec64b01b63)

**Additional context**

Possibly related to imports as in https://github.com/google/blockly-samples/issues/1892

**Comment by rachel-fenichel** [comment]
@johnnesky can you take a look this Friday?

**Comment by johnnesky** [comment]
Sure, I can take a look.

**Comment by johnnesky** [comment]
The field-colour-hsv-sliders plugin depends on the field-colour plugin. Both plugins are published on npm with a dist/ folder. 

However, in local testing, the hsv plugin's node_modules folder contains an alias pointing to field-colour in my copy of the repo, not the one published on npm, and my version doesn't contain the dist/ folder by default. If I navigate to field-colour and run `npm run build`, then back to field-colour-hsv-sliders and run `npm run start`, it succeeds.

Beka pointed out that the public demos are published by running `npm run test:ghpages` at root. This runs `npm run predeploy` on each of the plugins. It alphabetically handles field-colour first, which adds a dist/ folder containing declaration files but no index.js file, and then runs predeploy on field-colour-hsv-sliders, which reports "`Can't resolve '@blockly/field-colour'`". If I manually build field-colour, that adds the index.js file to dist/, after which I can run predeploy in field-colour-hsv-sliders without any problem. 

Apparently predeploy does not add index.js files to dist/ folders. Another consideration is that we may be relying on the plugins being predeployed in a certain order.

May also be related to: https://github.com/google/blockly-samples/issues/1877

**Comment by BeksOmega** [comment]
This needs to be reassigned to a member of the core team.

**Comment by maribethb** [comment]
The demo is fixed now due to #1992 against the master branch.
