### ISSUE TITLE
Publish types for block-dynamic-connection plugin

### ISSUE THREAD

**Issue by BeksOmega** [rachel-fenichel/blockly-samples#1896]
🚧⚠️🚧 This issue is being saved for **Grace Hopper Open Source Day**. 🚧⚠️🚧 An event we're running to help girls and non-binary technologists make their first contributions to open source! Please see our list of [help wanted issues](https://github.com/google/blockly-samples/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22+-label%3A%22ghc-osd%22) if you'd like to contribute! 

---

**Category**

 - Plugins
 
**Component**

block-dynamic-connection

**Is your feature request related to a problem? Please describe.**

Currently types for this plugin are not being exported :/

**Describe the solution you'd like**

1) Add the following property to the package.json next to the "main" property:
```
"types": "./dist/index.d.ts"
```

Note that type declaration files are already being generated by the compiler, they're just not being included in the npm package. So we just need to include them =)

**Additional context**

Related to: https://github.com/google/blockly-samples/issues/1892

**Comment by eldu** [comment]
I'd like to take on this issue !

**Comment by sunnydreamer** [comment]
I would love to work on this issue @BeksOmega

**Comment by BeksOmega** [comment]
Hiya @eldu Got you assigned =)

Sorry @sunnydreamer Looks like @eldu got here first :/ If you comment on a different issue I can get you assigned!
