### ISSUE TITLE
Publish types for block-shareable-procedures

### ISSUE THREAD

**Issue by BeksOmega** [rachel-fenichel/blockly-samples#1897]
🚧⚠️🚧 This issue is being saved for **Grace Hopper Open Source Day**. 🚧⚠️🚧 An event we're running to help girls and non-binary technologists make their first contributions to open source! Please see our list of [help wanted issues](https://github.com/google/blockly-samples/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22+-label%3A%22ghc-osd%22) if you'd like to contribute! 

---

**Category**

 - Plugins
 
**Component**

block-shareable-procedure

**Is your feature request related to a problem? Please describe.**

Currently types for this plugin are not being generated or exported :/

**Describe the solution you'd like**

1) Add the following config options to the "compilerOptions" section of the tsconfig.json
```
"declaration": true,
"declarationMap": true,
```
2) Add the following property to the package.json next to the "main" property:
```
"types": "./dist/index.d.ts"
```

**Additional context**

Related to: https://github.com/google/blockly-samples/issues/1892

**Comment by Daphne-wu** [comment]
Hello! I am interested in this

**Comment by rldhanush** [comment]
@BeksOmega I am interested in working on this, thanks !!

**Comment by BeksOmega** [comment]
Hiya @Daphne-wu Go for it!

@rl-dhanush Looks like @Daphne-wu got here first =) If you comment on a different issue I can get you assigned!
