### ISSUE TITLE
Publish types for field-angle

### ISSUE THREAD

**Issue by BeksOmega** [rachel-fenichel/blockly-samples#1899]
🚧⚠️🚧 This issue is being saved for **Grace Hopper Open Source Day**. 🚧⚠️🚧 An event we're running to help girls and non-binary technologists make their first contributions to open source! Please see our list of [help wanted issues](https://github.com/google/blockly-samples/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22+-label%3A%22ghc-osd%22) if you'd like to contribute! 

---

**Category**

 - Plugins
 
**Component**

field-angle

**Is your feature request related to a problem? Please describe.**

Currently types for this plugin are not being exported :/

**Describe the solution you'd like**

1) Add the following property to the package.json next to the "main" property:
```
"types": "./dist/index.d.ts"
```

**Additional context**

Related to: https://github.com/google/blockly-samples/issues/1892

**Comment by sunnydreamer** [comment]
I would love to work on this

**Comment by apatte** [comment]
Interested in working on this @BeksOmega

**Comment by sirishak-tw** [comment]
Would love working on this, @BeksOmega

**Comment by BeksOmega** [comment]
Hiya @sunnydreamer Go for it =)

@apatte and @sirihak-tw Looks like @sunnydreamer already got here, but if you comment on a different issue I can get you assigned!

**Comment by Navyashr4** [comment]
Interested @BeksOmega

**Comment by johnnesky** [comment]
This was resolved by https://github.com/google/blockly-samples/pull/1956

Thanks!
