### ISSUE TITLE
Publish types for field-colour

### ISSUE THREAD

**Issue by BeksOmega** [rachel-fenichel/blockly-samples#1900]
🚧⚠️🚧 This issue is being saved for **Grace Hopper Open Source Day**. 🚧⚠️🚧 An event we're running to help girls and non-binary technologists make their first contributions to open source! Please see our list of [help wanted issues](https://github.com/google/blockly-samples/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22+-label%3A%22ghc-osd%22) if you'd like to contribute! 

---

**Category**

 - Plugins
 
**Component**

field-colour

**Is your feature request related to a problem? Please describe.**

Currently types for this plugin are not being exported :/

**Describe the solution you'd like**

1) Add the following property to the package.json next to the "main" property:
```
"types": "./dist/index.d.ts"
```

**Additional context**

Related to: https://github.com/google/blockly-samples/issues/1892

**Comment by sashrikakaur** [comment]
Would love to pick this up as my first issue. Can I be assigned to this?

**Comment by Rea-Mammen** [comment]
Could I be assigned to this too!

**Comment by nishmashakya** [comment]
i would like to work on this

**Comment by Sushmadeegoju** [comment]
I will try to work on this one.

**Comment by SYJONES16** [comment]
Please add me to this one

**Comment by RadhikaRJ** [comment]
Hello, I'd like to work on this issue.

**Comment by divziv** [comment]
Interested! Would love to work on this.

**Comment by BeksOmega** [comment]
Hiya @sashrikakaur Go for it!

@Rea-Mammen, @nishma-s , @Sushmadeegoju , @SYJONES16 , @RadhikaRJ , @divziv Looks lik3 @sashrikakaur Got here first! If you comment on a different issue I can get you =)

**Comment by spiterwoman** [comment]
Hi! I am interested in working on this issue.

**Comment by spiterwoman** [comment]
Hi :) If i just want to practice, would that be possible?

**Comment by mishra016** [comment]
Hi, I am interested in working on this!
