### ISSUE TITLE
Publish types for field-colour-hsv-sliders

### ISSUE THREAD

**Issue by BeksOmega** [rachel-fenichel/blockly-samples#1901]
**Category**

 - Plugins
 
**Component**

field-colour-hsv-sliders

**Is your feature request related to a problem? Please describe.**

Currently types for this plugin are not being exported :/

**Describe the solution you'd like**

1) Add the following property to the package.json next to the "main" property:
```
"types": "./dist/index.d.ts"
```

**Additional context**

Related to: https://github.com/google/blockly-samples/issues/1892

**Comment by Sushmadeegoju** [comment]
@BeksOmega  Can I take up this issue?

**Comment by AbhinanduReddy** [comment]
@BeksOmega can you please assign this to me. If it's not assigned to anyone yet?

**Comment by BeksOmega** [comment]
@AbhinanduReddy Go for it =) If you have any questions don't hesitate to ask!
