### ISSUE TITLE
Publish types for field-date

### ISSUE THREAD

**Issue by BeksOmega** [rachel-fenichel/blockly-samples#1902]
**Category**

 - Plugins
 
**Component**

field-date

**Is your feature request related to a problem? Please describe.**

Currently types for this plugin are not being exported :/

**Describe the solution you'd like**

1) Add the following property to the package.json next to the "main" property:
```
"types": "./dist/index.d.ts"
```

**Additional context**

Related to: https://github.com/google/blockly-samples/issues/1892

**Comment by nikitapola** [comment]
Hi! I am interested in getting started on this issue for my first open source contribution!

**Comment by BeksOmega** [comment]
Go for it @nikitapola

**Comment by barkhaaroraa** [comment]
could i work on this

**Comment by BeksOmega** [comment]
Go for it @barkhaaroraa =) Let us know if you have any questions!

**Comment by BeksOmega** [comment]
Closed by #2049
