### ISSUE TITLE
Publish types for field-dependent-dropdown

### ISSUE THREAD

**Issue by BeksOmega** [rachel-fenichel/blockly-samples#1903]
🚧⚠️🚧 This issue is being saved for **Grace Hopper Open Source Day**. 🚧⚠️🚧 An event we're running to help girls and non-binary technologists make their first contributions to open source! Please see our list of [help wanted issues](https://github.com/google/blockly-samples/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22+-label%3A%22ghc-osd%22) if you'd like to contribute! 

---

**Category**

 - Plugins
 
**Component**

field-dependent-dropdown

**Is your feature request related to a problem? Please describe.**

Currently types for this plugin are not being exported :/

**Describe the solution you'd like**

1) Add the following property to the package.json next to the "main" property:
```
"types": "./dist/index.d.ts"
```

**Additional context**

Related to: https://github.com/google/blockly-samples/issues/1892

**Comment by bhsingla** [comment]
Hello team, I would love to pick this as my first task. Thanks

**Comment by nilishalu** [comment]
I would like to work on this

**Comment by PrayagCodes** [comment]
@BeksOmega

**Comment by PrayagCodes** [comment]
@BeksOmega I would like to work on these issue

**Comment by BeksOmega** [comment]
Hiya @bhsingla Go for it =)

**Comment by nhitran26197** [comment]
I would like to work on this issue please

**Comment by RadhikaRJ** [comment]
Hello @BeksOmega , I'd like to contribute to this issue.
