### ISSUE TITLE
Publish types for field-grid-dropdown

### ISSUE THREAD

**Issue by BeksOmega** [rachel-fenichel/blockly-samples#1904]
🚧⚠️🚧 This issue is being saved for **Grace Hopper Open Source Day**. 🚧⚠️🚧 An event we're running to help girls and non-binary technologists make their first contributions to open source! Please see our list of [help wanted issues](https://github.com/google/blockly-samples/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22+-label%3A%22ghc-osd%22) if you'd like to contribute! 

---

**Category**

 - Plugins
 
**Component**

field-grid-dropdown

**Is your feature request related to a problem? Please describe.**

Currently types for this plugin are not being exported :/

**Describe the solution you'd like**

1) Add the following property to the package.json next to the "main" property:
```
"types": "./dist/index.d.ts"
```

**Additional context**

Related to: https://github.com/google/blockly-samples/issues/1892

**Comment by shivalipatel6** [comment]
I would like to work on this one!

**Comment by goldenkairos** [comment]
I'd like to work on this issue please

**Comment by PrayagCodes** [comment]
@BeksOmega I would like work on this issue

**Comment by divziv** [comment]
Would love to contribute to this issue!

**Comment by ajita86** [comment]
I would love to contribute to this

**Comment by BeksOmega** [comment]
Hiya @shivalipatel6 Go for it =)
