### ISSUE TITLE
Publish types for field-multiline

### ISSUE THREAD

**Issue by BeksOmega** [rachel-fenichel/blockly-samples#1905]
🚧⚠️🚧 This issue is being saved for **Grace Hopper Open Source Day**. 🚧⚠️🚧 An event we're running to help girls and non-binary technologists make their first contributions to open source! Please see our list of [help wanted issues](https://github.com/google/blockly-samples/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22+-label%3A%22ghc-osd%22) if you'd like to contribute! 

---

**Category**

 - Plugins
 
**Component**

field-multiline

**Is your feature request related to a problem? Please describe.**

Currently types for this plugin are not being exported :/

**Describe the solution you'd like**

1) Add the following property to the package.json next to the "main" property:
```
"types": "./dist/index.d.ts"
```

**Additional context**

Related to: https://github.com/google/blockly-samples/issues/1892

**Comment by rachel-fenichel** [comment]
@BeksOmega is this also an open source day issue?

**Comment by CCLOAS-2** [comment]
@BeksOmega I'd like to contribute to this!

**Comment by BeksOmega** [comment]
Go for it @CCLOAS-2

**Comment by hwanyaur** [comment]
@BeksOmega Sorry, that was my work github account.... Could I be assigned to it with this one?

**Comment by BeksOmega** [comment]
@hwanyaur done =)

**Comment by PrathiPuthran** [comment]
@BeksOmega I would like to pair program on this issue, thanks
