### ISSUE TITLE
Publish types for field-slider

### ISSUE THREAD

**Issue by BeksOmega** [rachel-fenichel/blockly-samples#1906]
🚧⚠️🚧 This issue is being saved for **Grace Hopper Open Source Day**. 🚧⚠️🚧 An event we're running to help girls and non-binary technologists make their first contributions to open source! Please see our list of [help wanted issues](https://github.com/google/blockly-samples/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22+-label%3A%22ghc-osd%22) if you'd like to contribute! 

---

**Category**

 - Plugins
 
**Component**

field-slider

**Is your feature request related to a problem? Please describe.**

Currently types for this plugin are not being exported :/

**Describe the solution you'd like**

1) Add the following property to the package.json next to the "main" property:
```
"types": "./dist/index.d.ts"
```

**Additional context**

Related to: https://github.com/google/blockly-samples/issues/1892

**Comment by justjess246** [comment]
Hi! Could I get assigned to this task?

**Comment by rldhanush** [comment]
@BeksOmega I am interested in working on this, thanks !!

**Comment by Rea-Mammen** [comment]
Could I work on this!

**Comment by RadhikaRJ** [comment]
Hello, I'd like to work on this issue.

**Comment by spiterwoman** [comment]
Hi! I am interested in working on this issue.

**Comment by sakshirdkar** [comment]
I would like to work on this.

**Comment by BeksOmega** [comment]
Hiya @justjess246 Go for it!
