### ISSUE TITLE
Publish types for shadow-block-converter

### ISSUE THREAD

**Issue by BeksOmega** [rachel-fenichel/blockly-samples#1907]
🚧⚠️🚧 This issue is being saved for **Grace Hopper Open Source Day**. 🚧⚠️🚧 An event we're running to help girls and non-binary technologists make their first contributions to open source! Please see our list of [help wanted issues](https://github.com/google/blockly-samples/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22+-label%3A%22ghc-osd%22) if you'd like to contribute! 

---

**Category**

 - Plugins
 
**Component**

shadow-block-converter

**Is your feature request related to a problem? Please describe.**

Currently types for this plugin are not being exported :/

**Describe the solution you'd like**

1) Add the following property to the package.json next to the "main" property:
```
"types": "./dist/index.d.ts"
```

**Additional context**

Related to: https://github.com/google/blockly-samples/issues/1892

**Comment by humera811** [comment]
happy to take this

**Comment by RongjingH** [comment]
@BeksOmega I'd like to work on this.

**Comment by rldhanush** [comment]
@BeksOmega I am interested in working on this, thanks !!

**Comment by BeksOmega** [comment]
Hiya @humera811 Go for it!
