### ISSUE TITLE
Publish types for toolbox-search

### ISSUE THREAD

**Issue by BeksOmega** [rachel-fenichel/blockly-samples#1908]
🚧⚠️🚧 This issue is being saved for **Grace Hopper Open Source Day**. 🚧⚠️🚧 An event we're running to help girls and non-binary technologists make their first contributions to open source! Please see our list of [help wanted issues](https://github.com/google/blockly-samples/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22+-label%3A%22ghc-osd%22) if you'd like to contribute! 

---

**Category**

 - Plugins
 
**Component**

toolbox-search

**Is your feature request related to a problem? Please describe.**

Currently types for this plugin are not being generated or exported :/

**Describe the solution you'd like**

1) Add the following config options to the "compilerOptions" section of the tsconfig.json
```
"declaration": true,
"declarationMap": true,
```
2) Add the following property to the package.json next to the "main" property:
```
"types": "./dist/index.d.ts"
```

**Additional context**

Related to: https://github.com/google/blockly-samples/issues/1892

**Comment by zhangjuliet** [comment]
Hi, I'd like to work on this!

**Comment by parul16101** [comment]
Interested

**Comment by nilishalu** [comment]
Hai, I would like to work on this.

**Comment by midolake** [comment]
can I work on this please?

**Comment by spiterwoman** [comment]
Hi! I am interested in working on this issue.

**Comment by RadhikaRJ** [comment]
Hello, I'd like to contribute to this issue.

**Comment by BeksOmega** [comment]
Hiya @zhangjuliet Go for it!
