### ISSUE TITLE
Publish types for workspace-minimap

### ISSUE THREAD

**Issue by BeksOmega** [rachel-fenichel/blockly-samples#1909]
**Category**

 - Plugins
 
**Component**

workspace-minimap

**Is your feature request related to a problem? Please describe.**

Currently types for this plugin are not being generated or exported :/

**Describe the solution you'd like**

1) Add the following config options to the "compilerOptions" section of the tsconfig.json
```
"declaration": true,
"declarationMap": true,
```
2) Add the following property to the package.json next to the "main" property:
```
"types": "./dist/index.d.ts"
```

**Additional context**

Related to: https://github.com/google/blockly-samples/issues/1892

**Comment by scoopstroop92** [comment]
I would like to work on this
@BeksOmega

**Comment by apatte** [comment]
Interested in working on this @BeksOmega

**Comment by YashviDesaii** [comment]
I would like to work on this @BeksOmega

**Comment by RadhikaRJ** [comment]
Hello, I'd like to contribute to this issue.

**Comment by spiterwoman** [comment]
Hi! I am interested in working on this issue.

**Comment by BeksOmega** [comment]
Hiya @ramyaram2092 Go for it =)

**Comment by vprerana** [comment]
I would like to work on this

**Comment by Annysah** [comment]
Hi I am interested in working on this issue

**Comment by PrayagCodes** [comment]
@BeksOmega please assign me thses issue

**Comment by vprerana** [comment]
Hey, I would like to work on this issue.

**Comment by kapooraryan** [comment]
@BeksOmega Could I work on this?

**Comment by BeksOmega** [comment]
Go for it @kapooraryan !
