### ISSUE TITLE
Publish types for workspace-search

### ISSUE THREAD

**Issue by BeksOmega** [rachel-fenichel/blockly-samples#1910]
🚧⚠️🚧 This issue is being saved for **Grace Hopper Open Source Day**. 🚧⚠️🚧 An event we're running to help girls and non-binary technologists make their first contributions to open source! Please see our list of [help wanted issues](https://github.com/google/blockly-samples/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22+-label%3A%22ghc-osd%22) if you'd like to contribute! 

---

**Category**

 - Plugins
 
**Component**

workspace-search

**Is your feature request related to a problem? Please describe.**

Currently types for this plugin are not being generated or exported :/

**Describe the solution you'd like**

1) Add the following config options to the "compilerOptions" section of the tsconfig.json
```
"declaration": true,
"declarationMap": true,
```
2) Add the following property to the package.json next to the "main" property:
```
"types": "./dist/index.d.ts"
```

**Additional context**

Related to: https://github.com/google/blockly-samples/issues/1892

**Comment by Yalagach** [comment]
I would like to work on this

**Comment by RongjingH** [comment]
Hi @BeksOmega , I'd like to work on this issue

**Comment by RadhikaRJ** [comment]
Hello, I'd like to contribute to this issue.

**Comment by ChTiSh** [comment]
I would love to contribute to this issue as well

**Comment by spiterwoman** [comment]
Hi! I am interested in working on this issue.

**Comment by nhitran26197** [comment]
I would like to work on this issue

**Comment by vprerana** [comment]
I would like to work on this.

**Comment by BeksOmega** [comment]
Hiya @Yalagach Go for it =)

**Comment by PrayagCodes** [comment]
@BeksOmega I would like to work on these issue

**Comment by coolcoder03** [comment]
I am interested to work on this.

**Comment by Yalagach** [comment]
@BeksOmega I have completed the issue and committed the changes.
