### ISSUE TITLE
Publish types for zoom-to-fit

### ISSUE THREAD

**Issue by BeksOmega** [rachel-fenichel/blockly-samples#1911]
🚧⚠️🚧 This issue is being saved for **Grace Hopper Open Source Day**. 🚧⚠️🚧 An event we're running to help girls and non-binary technologists make their first contributions to open source! Please see our list of [help wanted issues](https://github.com/google/blockly-samples/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22+-label%3A%22ghc-osd%22) if you'd like to contribute! 

---

**Category**

 - Plugins
 
**Component**

zoom-to-fit

**Is your feature request related to a problem? Please describe.**

Currently types for this plugin are not being generated or exported :/

**Describe the solution you'd like**

1) Add the following config options to the "compilerOptions" section of the tsconfig.json
```
"declaration": true,
"declarationMap": true,
```
2) Add the following property to the package.json next to the "main" property:
```
"types": "./dist/index.d.ts"
```

**Additional context**

Related to: https://github.com/google/blockly-samples/issues/1892

**Comment by juhithaVd** [comment]
I want to work on this, how do I get this assigned?

**Comment by RongjingH** [comment]
@BeksOmega Could I work on this?

**Comment by juhithaVd** [comment]
I have no problem working together as well

**Comment by nidhidanayak** [comment]
I would also like to work on this

**Comment by apatte** [comment]
Interested in working on this @BeksOmega

**Comment by SYJONES16** [comment]
Is this one available?

**Comment by sakshirdkar** [comment]
Interested to work on this.

**Comment by RadhikaRJ** [comment]
Hello, I'd like to work on this issue.

**Comment by PrathiPuthran** [comment]
@BeksOmega i would like to work on this

**Comment by BeksOmega** [comment]
Hiya @juhithaVd Go for it!

**Comment by juhithaVd** [comment]
Thank you @BeksOmega
