### ISSUE TITLE
Have field-bitmap fire intermediate change events

### ISSUE THREAD

**Issue by BeksOmega** [rachel-fenichel/blockly-samples#1912]
🚧⚠️🚧 This issue is being saved for **Grace Hopper Open Source Day**. 🚧⚠️🚧 An event we're running to help girls and non-binary technologists make their first contributions to open source! Please see our list of [help wanted issues](https://github.com/google/blockly-samples/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22+-label%3A%22ghc-osd%22) if you'd like to contribute! 

---

**Category**

 - Plugins

**Component**

field-bitmap

**Is your feature request related to a problem? Please describe.**

The bitmap field fires undoable `BlockChange` events for every square that gets painted. This makes undoing a change time consuming.

**To reproduce**

1) `cd` into `plugins/field-bitmap`.
2) Run `npm run start` to open the playground.
3) In the right nav bar under "Actions" check "Log Events". Then open your browser console so you can see the logged events.
4) Drag a bitmap field onto the workspace.
5) Open the editor and edit the bitmap.
6) Observe how `BlockChange` events are fired for every change.
7) Undo the action using `ctrl + z` (or `cmd + z`), and observe how only one pixel is changed. Ideally the whole action should be undone.

**Describe the solution you'd like**

Instead it should fire `IntermediateFieldChange` events for these changes, and only fire a `BlockChange` event when its editor is closed.

## To Fix

1) Run the reproduction steps and make sure you can reproduce the issue.
2) Add a property in the [constructor](https://github.com/google/blockly-samples/blob/11e2600f4b8391b82a67cb14dcf4f1c5e4c0466d/plugins/field-bitmap/src/field-bitmap.js#L34) that records what the value of the field is at the start of an edit.
3) Modify the [dropdownCreate](https://github.com/google/blockly-samples/blob/11e2600f4b8391b82a67cb14dcf4f1c5e4c0466d/plugins/field-bitmap/src/field-bitmap.js#L234) method to store the value of the field at the start of the edit.
4) Modify the [setPixel](https://github.com/google/blockly-samples/blob/11e2600f4b8391b82a67cb14dcf4f1c5e4c0466d/plugins/field-bitmap/src/field-bitmap.js#L461) method to fire `BLOCK_FIELD_INTERMEDIATE_CHANGE` events. Make sure to call `setValue` still, but pass `false` for the second parameter.
```js
if (this.getSourceBlock()) {
      Blockly.Events.fire(
          new (Blockly.Events.get(
              Blockly.Events.BLOCK_FIELD_INTERMEDIATE_CHANGE))(
              this.sourceBlock_,
              this.name || null,
              oldValue,
             this.value_
          )
      );
    }
```
5) Do the same for the `randomizePixels` and the `clearPixels` methods.
5) Modify the [dropdownDispose](https://github.com/google/blockly-samples/blob/11e2600f4b8391b82a67cb14dcf4f1c5e4c0466d/plugins/field-bitmap/src/field-bitmap.js#L367) method to fire a `BLOCK_CHANGE` event. It will look very similar to how you fired the other event, but it will use the property for the value at the start of the edit.
6) Run the reproduction steps again and make sure you can't reproduce the behavior.

**Comment by johnnesky** [comment]
This will be a little more complex than https://github.com/google/blockly-samples/issues/1914 or https://github.com/google/blockly-samples/pull/1933 because `FieldBitmap` does not extend `Blockly.FieldInput` or `Blockly.FieldNumber`, so you will need to reimplement the part that tracks the original value of the field and fire a change event when the editor is closed. The code for that will be similar to the code added to field_input.ts in: https://github.com/google/blockly/pull/7151/files#diff-6e809b7c830fc095183f413ca9bf0b89fdaeaffa92c189d758597b368ff1b1a1

**Comment by RongjingH** [comment]
I'm interested in it

**Comment by wich229** [comment]
I'm interested in this one

**Comment by Patty8122** [comment]
@BeksOmega Could you assign this to me?

**Comment by nithyabach11** [comment]
I'm interested in this!

**Comment by ajita86** [comment]
Can this be assigned to me?

**Comment by miss1** [comment]
I would like to work on this issue, thanks!

**Comment by PrathiPuthran** [comment]
I would like to work in this

**Comment by coolcoder03** [comment]
I am interested to take this.

**Comment by PrathiPuthran** [comment]
@BeksOmega i would like to work on this

**Comment by RadhikaRJ** [comment]
Hello, I'd like to work on this issue.

**Comment by PrayagCodes** [comment]
@BeksOmega I would like to work on this issue

**Comment by BeksOmega** [comment]
Hiya @wich229 Go for it!
