### ISSUE TITLE
Have field-slider fire intermediate change events

### ISSUE THREAD

**Issue by BeksOmega** [rachel-fenichel/blockly-samples#1914]
🚧⚠️🚧 This issue is being saved for **Grace Hopper Open Source Day**. 🚧⚠️🚧 An event we're running to help girls and non-binary technologists make their first contributions to open source! Please see our list of [help wanted issues](https://github.com/google/blockly-samples/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22+-label%3A%22ghc-osd%22) if you'd like to contribute! 

---

**Category**

 - Plugins

**Component**

field-slider

**Is your feature request related to a problem? Please describe.**

The slider field fires a `BlockChange` events for every tick the slider is moved. People may want to ignore intermediate changes, so they should fire a different event.

**To reproduce**

1) `cd` into `plugins/field-slider`.
2) Run `npm run start` to open the playground.
3) In the right nav bar under "Actions" check "Log Events". Then open your browser console so you can see the logged events.
4) Drag a slider field onto the workspace.
5) Open the editor and slide the slider.
6) Observe how `BlockChange` events are fired for every change.

**Describe the solution you'd like**

Instead it should fire `IntermediateFieldChange` events for these changes, and only fire a `BlockChange` event when its editor is closed.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

## To Fix

1) Run the reproduction steps and make sure you can reproduce the issue.
2) Modify the [onSliderChange](https://github.com/google/blockly-samples/blob/11e2600f4b8391b82a67cb14dcf4f1c5e4c0466d/plugins/field-slider/src/field_slider.ts#L162) method to fire `BLOCK_FIELD_INTERMEDIATE_CHANGE` events. Make sure to call `setEditorValue` still, but pass `false` for the second parameter to inhibit firing the regular event.
```js
    // Intermediate value changes from user input are not confirmed until the
    // user closes the editor, and may be numerous. Inhibit reporting these as
    // normal block change events, and instead report them as special
    // intermediate changes that do not get recorded in undo history.
    const oldValue = this.value_;
    this.setEditorValue_(this.sliderInput?.value, false);
    if (this.getSourceBlock()) {
      Blockly.Events.fire(
          new (Blockly.Events.get(
              Blockly.Events.BLOCK_FIELD_INTERMEDIATE_CHANGE))(
              this.sourceBlock_,
              this.name || null,
              oldValue,
             this.value_
          )
      );
    }
```
3) Run the reproduction steps again and make sure you can't reproduce the behavior.

**Comment by johnnesky** [comment]
This should be similar to the changes to `FieldAngle` in https://github.com/google/blockly-samples/pull/1933 since `FieldAngle` and `FieldSlider` both extend `Blockly.FieldNumber`.

**Comment by joycexfang** [comment]
@BeksOmega hi! may i work on this issue?

**Comment by BeksOmega** [comment]
Sweet @joycexfang Go for it!
