### ISSUE TITLE
Minimap comments can be opened

### ISSUE THREAD

**Issue by BeksOmega** [rachel-fenichel/blockly-samples#1923]
**Category**

 - Plugins

**Component**

workspace-minimap

**Describe the bug**

If you click on a comment icon in the minimap, it will open (but it will be a readonly comment). We probably don't want people to be able to open comments at all because then the minimap won't match the main workspace.

**To Reproduce**

1. Run `npm run start` in the minimap directory.
2. Drag out a block and readd a comment. The comment will not be added to the block in the minimap because of https://github.com/google/blockly/issues/7480
3. Refresh the page so the minimap does get the comment.
4. Click on the comment icon in the minimap. Observe how the comment opens in read-only mode.

**Expected behavior**

Either:
1) Comments are never added.
2) Comments are not openable.

**Additional context**

See the original forum post: https://groups.google.com/g/blockly/c/8MxXhpFAR8c/m/3K4crVg6AgAJ

## To Fix

1) Run the reproduction steps to make sure you can reproduce the error.
2) Modify the minimap workspace config to set `comments: false`.
3) Rerun the reproduct steps. The comment icon should not be mirrored to the minimap workspace.

**Comment by rachel-fenichel** [comment]
@cesarades because minimap

**Comment by BeksOmega** [comment]
I think this is actually a bug that needs more discussion. The minimap is set to `readonly` mode which makes it mostly non-interactive. But comments are still interactable because the initial use-case for `readonly` mode was teachers/applications making sample projects. We may want to add a setting in core to disable opening comments.

Other options would be:
  1) Adding a div over the minimap workspace to eat events. We may have to reimplement dragging if we do this.
  2) Adding a way to override built-in icons (which we currently don't support). Then we could provide a different implementation of the `comment` icon that doesn't open if `isEditable` is `false`.
  3) Adding a listener for any `BubbleOpen` events that closes the bubble immediately. This would look glitchy.
  4) Setting `comments` to `false` in the minimap workspace config. This would mean the minimap isn't a perfect mirror, but it currently isn't anyway :P (Also I'm assuming this wouldn't break event mirroring, but it would need to be tested)

**Comment by rachel-fenichel** [comment]
Out of the options presented, I like turning off comments the best. I think that matches with the idea of slightly reducing fidelity because it's a smaller view.

**Comment by sdthaker** [comment]
Hi there! I'd like to work on this issue! Could you please assign the issue to me? 

However, I'd need more information on what this means -> `Modify the minimap workspace config to set comments: false.`. I looked into the `workspace-minimap` plugin but I couldn't find a config file that sets the `comments` property to true or false. At least that's what my assumption was after reading the instructions on this issue. Please let me know where to look to fix this issue. Thanks!

**Comment by BeksOmega** [comment]
> Hi there! I'd like to work on this issue! Could you please assign the issue to me?
> 
> However, I'd need more information on what this means -> `Modify the minimap workspace config to set comments: false.`. I looked into the `workspace-minimap` plugin but I couldn't find a config file that sets the `comments` property to true or false. At least that's what my assumption was after reading the instructions on this issue. Please let me know where to look to fix this issue. Thanks!

Hello :D The config is a [workspace config](https://developers.google.com/blockly/guides/configure/web/configuration_struct), which lives [here](https://github.com/google/blockly-samples/blob/b8e613741957eb6a3bf783872a42ff5069506785/plugins/workspace-minimap/src/minimap.ts#L63). 

If you have any further questions don't hesitate to ask!

**Comment by sdthaker** [comment]
> > Hi there! I'd like to work on this issue! Could you please assign the issue to me?
> > However, I'd need more information on what this means -> `Modify the minimap workspace config to set comments: false.`. I looked into the `workspace-minimap` plugin but I couldn't find a config file that sets the `comments` property to true or false. At least that's what my assumption was after reading the instructions on this issue. Please let me know where to look to fix this issue. Thanks!
> 
> Hello :D The config is a [workspace config](https://developers.google.com/blockly/guides/configure/web/configuration_struct), which lives [here](https://github.com/google/blockly-samples/blob/b8e613741957eb6a3bf783872a42ff5069506785/plugins/workspace-minimap/src/minimap.ts#L63).
> 
> If you have any further questions don't hesitate to ask!

I tried adding `comments: false` as part of the minimap workspace config options and I'm still able to click and open the comments in the minimap. Am I missing something?

Video Explanation:
https://github.com/google/blockly-samples/assets/71615163/93e2c41c-f653-46b6-94c9-cee7a65438d3

**Comment by BeksOmega** [comment]
> > > Hi there! I'd like to work on this issue! Could you please assign the issue to me?
> > > However, I'd need more information on what this means -> `Modify the minimap workspace config to set comments: false.`. I looked into the `workspace-minimap` plugin but I couldn't find a config file that sets the `comments` property to true or false. At least that's what my assumption was after reading the instructions on this issue. Please let me know where to look to fix this issue. Thanks!
> > 
> > 
> > Hello :D The config is a [workspace config](https://developers.google.com/blockly/guides/configure/web/configuration_struct), which lives [here](https://github.com/google/blockly-samples/blob/b8e613741957eb6a3bf783872a42ff5069506785/plugins/workspace-minimap/src/minimap.ts#L63).
> > If you have any further questions don't hesitate to ask!
> 
> I tried adding `comments: false` as part of the minimap workspace config options and I'm still able to click and open the comments in the minimap. Am I missing something?
> 
> Video Explanation: https://github.com/google/blockly-samples/assets/71615163/93e2c41c-f653-46b6-94c9-cee7a65438d3

Hmm ok my bad, I thought setting `comments` to `false` would disable comments from being constructed programmatically, but looks like it just disables users creating them. I'm going to pass this back to the triage team to look at again!

Thank you for investigating this solution for us :D

**Comment by sdthaker** [comment]
No worries! Thanks! :)

**Comment by sdthaker** [comment]
> > > > Hi there! I'd like to work on this issue! Could you please assign the issue to me?
> > > > However, I'd need more information on what this means -> `Modify the minimap workspace config to set comments: false.`. I looked into the `workspace-minimap` plugin but I couldn't find a config file that sets the `comments` property to true or false. At least that's what my assumption was after reading the instructions on this issue. Please let me know where to look to fix this issue. Thanks!
> > > 
> > > 
> > > Hello :D The config is a [workspace config](https://developers.google.com/blockly/guides/configure/web/configuration_struct), which lives [here](https://github.com/google/blockly-samples/blob/b8e613741957eb6a3bf783872a42ff5069506785/plugins/workspace-minimap/src/minimap.ts#L63).
> > > If you have any further questions don't hesitate to ask!
> > 
> > 
> > I tried adding `comments: false` as part of the minimap workspace config options and I'm still able to click and open the comments in the minimap. Am I missing something?
> > Video Explanation: https://github.com/google/blockly-samples/assets/71615163/93e2c41c-f653-46b6-94c9-cee7a65438d3
> 
> Hmm ok my bad, I thought setting `comments` to `false` would disable comments from being constructed programmatically, but looks like it just disables users creating them. I'm going to pass this back to the triage team to look at again!
> 
> Thank you for investigating this solution for us :D

No worries! Thanks! :)

**Comment by maribethb** [comment]
Still an issue we should fix, but probably not a good first issue anymore

**Comment by maribethb** [comment]
@johnnesky any interest in picking this up next? There's some previous discussion about design ideas and why the obvious approach doesn't work.

**Comment by johnnesky** [comment]
@maribethb Sure, I'd be happy to take a look!
