### ISSUE TITLE
Toolbox search doesn't work with XML toolboxes due to case sensitivity

### ISSUE THREAD

**Issue by BeksOmega** [rachel-fenichel/blockly-samples#1925]
**Category**

 - Plugins

**Component**

toolbox-search

**Describe the bug**

The toolbox search plugin doesn't work if the 'kind' is upper case (which occurs when using XML toolboxes).

**To Reproduce**

1. Go to the [toolbox search playground](https://github.com/google/blockly-samples/blob/master/plugins/toolbox-search/test/index.ts) file.
2. Replace the `DOMContentLoaded` listener with the below code:
```js
document.addEventListener('DOMContentLoaded', function() {
  const toolbox = {
    'kind': 'categoryToolbox',
    'contents': [
      {
        'kind': 'category',
        'name': 'Control',
        'contents': [
          {
            'kind': 'BLOCK',
            'type': 'controls_if',
          },
        ],
      },
      {
        'kind': 'category',
        'name': 'Logic',
        'contents': [
          {
            'kind': 'BLOCK',
            'type': 'logic_compare',
          },
          {
            'kind': 'BLOCK',
            'type': 'logic_operation',
          },
          {
            'kind': 'BLOCK',
            'type': 'logic_boolean',
          },
        ],
      },
      {
        'kind': 'search',
        'name': 'Search',
        'contents': [],
      },
    ],
  };
  const defaultOptions: Blockly.BlocklyOptions = {
    toolbox,
  };
  createPlayground(
      document.getElementById('root'), createWorkspace, defaultOptions);
});
```
4. Run `npm run start` from the toolbox-search directory to open the playground.
5. Type 'if' into the search.
6. Observe how no blocks appear in the flyout.

**Expected behavior**

Blocks should appear.

## To Fix

1) Run through the reproduction steps and make sure you can reproduce the error.
2) Modify [`getAvailableBlocks`](https://github.com/google/blockly-samples/blob/f06f64f8ab2785f587dda1875d5b2b194ed7e7f3/plugins/toolbox-search/src/toolbox_search.ts#L106) to be case insensitive. You probably want to use [toUpperCase](https://www.w3schools.com/jsref/jsref_touppercase.asp).
3) Run the reproduction steps again to make sure the error doesn't reproduce.

**Comment by thebedigupta** [comment]
Will you explain the issue in more detail actually I am contributing first time so I need to know your problem in more detail @BeksOmega 
![image](https://github.com/google/blockly-samples/assets/133202831/4b06894b-ab75-491d-9af8-8c553f55b6c7)
here everything seems to be working

**Comment by BeksOmega** [comment]
Hello! Thanks for your question :D It looks like you need to retry the reproduction steps. If they were done correctly, your toolbox should have a "Control" category, a "Logic" category and the Search category.

To further clarify: the case-sensitivity is a problem with what you search, but it is a problem with how the toolbox is defined. If you have `'kind': 'BLOCK'` instead of `'kind: 'block'` it breaks!

I hope that helps! If you have any further questions please reply :D Thank you for taking an interest in this issue!

**Comment by BeksOmega** [comment]
Oh actually @thebedigupta It looks like @prasium has grabbed this issue in https://github.com/google/blockly-samples/pull/1930

@thebedigupta If you'd still like to work on an issue let me know and I can recommend one!

@prasium in the future please comment on an issue if you're working on it so we don't get conflicts! We really appreciate you working on this, but don't want other folks to duplicate work =)

**Comment by prasium** [comment]
Okay sure @BeksOmega :D

**Comment by thebedigupta** [comment]
Yeah sure I would love to know if you have any begginer friendly issue assign me one @BeksOmega

**Comment by BeksOmega** [comment]
Hiya @thebedigupta would you be interested in https://github.com/google/blockly-samples/issues/1861 ? If so, comment on that issue and I'll get it assigned to you! Otherwise, reply here and I'll look for something else =)

**Comment by thebedigupta** [comment]
yeah I would love to work on that thank you @BeksOmega
