### ISSUE TITLE
Minimap should use the renderer of the main workspace

### ISSUE THREAD

**Issue by BeksOmega** [rachel-fenichel/blockly-samples#1926]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Component

workspace-minimap

### Description

The minimap does not use the renderer of the main workspace.

### Reproduction steps

1. CD into the workspace-minimap directory.
2. Run `npm run start`
3. In the right options pallet under Options > renderer switch the dropdown to "zelos".
4. Drag some blocks into the workspace.
5. Observe how the main workspace uses the Zelos renderer, but the minimap uses the Geras one.

### Additional Info

Originally reported here: https://groups.google.com/g/blockly/c/Xt8pD_ST1B0/m/40NPAV8jAwAJ

## To Fix

1) Run the reproduction steps and make sure you can reproduce the issue.
2) Modify the [minimap inject call](https://github.com/google/blockly-samples/blob/e45ad05b9f5f6cb717b8337c60df09fa0128e06b/plugins/workspace-minimap/src/minimap.ts#L64) to copy the renderer from the `primaryWorkspace`.
2) Run the reproduction steps and make sure you can't reproduce the issue.

**Comment by thexeromin** [comment]
The [`name`](https://github.com/google/blockly/blob/e7030a18a62da1c8425fa23d781de1917d575eac/core/renderers/common/renderer.ts#L37)  property in  `Renderer` class is protected. But there is a method called [`getClassName`](https://github.com/google/blockly/blob/e7030a18a62da1c8425fa23d781de1917d575eac/core/renderers/common/renderer.ts#L56) which returns  renderer name with **-renderer** text at the end (e.g., zelos-renderer). We can remove the  **-renderer** text from the string and use it. Let me know what's your thought on this.

**Comment by BeksOmega** [comment]
Hello @itsfloki I think you can access the name of the renderer from the workspace options like [we do for mutators](https://github.com/google/blockly/blob/e7030a18a62da1c8425fa23d781de1917d575eac/core/icons/mutator_icon.ts#L203)!

Would you like to be assigned to this issue?

**Comment by thexeromin** [comment]
Yaa sure. I would love to take this up.
