### ISSUE TITLE
Remove the `lint` script from `blockly-scripts`

### ISSUE THREAD

**Issue by maribethb** [rachel-fenichel/blockly-samples#1976]
### Check for duplicates

- [x] I have searched for similar issues before opening a new one.

### Component

dev-scripts

### Problem

The lint script in dev-scripts runs eslint through the JS API. After https://github.com/google/blockly-samples/pull/1946 is merged, we'll no longer need this script because eslint can be invoked directly on the command line from any level of blockly-samples. This is an improvement because the eslint cli has better formatted output (especially when run at the entire repository level) and the flat config is easier to use and make changes to.

### Request

Remove the `lint` script from dev-scripts. This is a breaking change for the plugin. The lint script already logs a deprecation warning when run. I hope that nobody is using this script outside of blockly-samples.

### Additional context

If you are currently using `blockly-scripts lint`, switch to invoking eslint through its cli or write your own script that uses the eslint js api. Also, it would help us if you commented on this issue with your use case.

**Comment by shivalipatel6** [comment]
Hi I would like to be assigned to this issue! This would be my second contribution to Blockly-samples, my first being through the Grace Hopper Conference.

**Comment by BeksOmega** [comment]
Hello @shivalipatel6 Thanks for your interest and coming back to the project :D I can assign you to the issue, but just so you know we'll have to hold your fix until after #1946 is merged.

**Comment by shivalipatel6** [comment]
@BeksOmega Okay! I'll wait until #1946 is merged! I noticed that most of the good first issue projects were connected to that so I'm willing to wait. Just to make sure the fix is asking me to delete lint.js script after the #1946 issue is merged?

**Comment by BeksOmega** [comment]
> Just to make sure the fix is asking me to delete lint.js script after the #1946 issue is merged?

Hello again :D It is asking you to:
  1) Do that - delete the `lint.js` script.
  2) Delete any references to the lint script. So anywhere it says `"lint": "blockly-scripts lint",` in the `package.json` of a plugin.

**Comment by maribethb** [comment]
Hi @shivalipatel6, one small correction to what Beka said. You won't need to touch the `package.json` files of every plugin, because I will have already updated them to use the new eslint config. You will need to delete the `lint.js` script, remove it from the "available scripts" in `dev-scripts/bin/blockly-scripts.js`, and remove it from the README of dev-scripts.  That should be it!

**Comment by shivalipatel6** [comment]
I have a question: 
I just noticed that https://developers.google.com/blockly/guides/contribute/samples#making_and_verifying_a_change tells users learning how to verify a change that you need to run npm run lint, is that a problem now that I have deleted the lint.js script? I think that because eslint will be able to be run from the command line from any level of blockly samples that this should be fine, but I am trying to expand my understanding of blockly-samples so I figured I should just ask.

**Comment by maribethb** [comment]
Hi @shivalipatel6, this won't be a problem as each plugin still contains a script for linting so that you can run `npm run lint` from within each plugin (or from the root of blockly-samples). The script used to be `blockly-scripts lint` which would run the script you deleted in your PR. Now, the script is `eslint .` which just runs the eslint command line directly. You can find this information in the `package.json` for any plugin.

I hope that helps! I'll be reviewing your PR later today. Let me know if you have any other questions. Thanks!
