### ISSUE TITLE
Add a GitHub Action that runs the formatter

### ISSUE THREAD

**Issue by maribethb** [rachel-fenichel/blockly-samples#1977]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Component

entire repo

### Request

After https://github.com/google/blockly-samples/pull/1946 is submitted, we'll have a new top-level script that can automatically format the entire repository. On every pull request, we should run `npm run format:check` which will run the formatter in a mode that reports if any file needs formatting still. We have a similar action in core blockly [here](https://github.com/google/blockly/blob/fd873507eba5c2e587bc2156398edc09e88b84d1/.github/workflows/build.yml#L70). We should add a similar job to our existing build/lint action in blockly-samples.

**Comment by sdthaker** [comment]
Hi there! Can you please assign this to me? I'd like to work on this issue. Currently working on # 1978, will get to this one once I'm done with that. Thanks!
