### ISSUE TITLE
Fix lint warnings in blockly-samples

### ISSUE THREAD

**Issue by maribethb** [rachel-fenichel/blockly-samples#1978]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Component

multiple

### Description

After https://github.com/google/blockly-samples/pull/1946 is submitted:

There are several lint warnings in blockly-samples that we should fix or ignore the linter. Run the linter and fix the warnings shown.

Note that several of the warnings are about missing JsDoc comments, so you may need to write small amounts of documentation to fix this issue.

`unexpected any` warnings may need refactorings to avoid the `any` type, or may need to just add an ignore statement to silence the warning, if the use of `any` is appropriate.

### Reproduction steps

1. Run `npm run lint` from the root of blockly-samples
2. Note the multiple lint warnings

**Comment by sdthaker** [comment]
Hi there! Could you please assign this to me? I'd like to work on this issue! Thanks!

**Comment by BeksOmega** [comment]
Go for it @sdthaker =) If you have any questions don't hesitate to ask!

**Comment by sdthaker** [comment]
I'd want to test the plugin `field-dependent-dropdown` since [L150](https://github.com/google/blockly-samples/blob/master/plugins/field-dependent-dropdown/src/dependent_dropdown_options_change.ts#L150) has a warning about unexpected any usage in variable `event`. How can I test this plugin? I'm looking to console.log the type of the variable and assign it a proper type by running the plugin as a server or something but the readme doesn't mention anything about this. Also, is there a better way to test the variable type other than what I suggested in this comment? Thanks

**Comment by sdthaker** [comment]
> I'd want to test the plugin `field-dependent-dropdown` since [L150](https://github.com/google/blockly-samples/blob/master/plugins/field-dependent-dropdown/src/dependent_dropdown_options_change.ts#L150) has a warning about unexpected any usage in variable `event`. How can I test this plugin? I'm looking to console.log the type of the variable and assign it a proper type by running the plugin as a server or something but the readme doesn't mention anything about this. Also, is there a better way to test the variable type other than what I suggested in this comment? Thanks

I was looking into this warning and seems like the `any` type assignment is done on purpose as explained [here](https://github.com/google/blockly/blob/develop/core/events/events_block_base.ts#L65). So I'll be adding the rule `/* eslint-disable-next-line @typescript-eslint/no-explicit-any */` above [L150](https://github.com/google/blockly-samples/blob/master/plugins/field-dependent-dropdown/src/dependent_dropdown_options_change.ts#L15) to silence the warning. Please let me know if I should be doing it otherwise.

**Comment by BeksOmega** [comment]
> > I'd want to test the plugin `field-dependent-dropdown` since [L150](https://github.com/google/blockly-samples/blob/master/plugins/field-dependent-dropdown/src/dependent_dropdown_options_change.ts#L150) has a warning about unexpected any usage in variable `event`. How can I test this plugin? I'm looking to console.log the type of the variable and assign it a proper type by running the plugin as a server or something but the readme doesn't mention anything about this. Also, is there a better way to test the variable type other than what I suggested in this comment? Thanks
> 
> I was looking into this warning and seems like the `any` type assignment is done on purpose as explained [here](https://github.com/google/blockly/blob/develop/core/events/events_block_base.ts#L65). So I'll be adding the rule `/* eslint-disable-next-line @typescript-eslint/no-explicit-any */` above [L150](https://github.com/google/blockly-samples/blob/master/plugins/field-dependent-dropdown/src/dependent_dropdown_options_change.ts#L15) to silence the warning. Please let me know if I should be doing it otherwise.

Yes that sounds perfect!

> I'd want to test the plugin `field-dependent-dropdown` since [L150](https://github.com/google/blockly-samples/blob/master/plugins/field-dependent-dropdown/src/dependent_dropdown_options_change.ts#L150) has a warning about unexpected any usage in variable `event`. How can I test this plugin? I'm looking to console.log the type of the variable and assign it a proper type by running the plugin as a server or something but the readme doesn't mention anything about this. Also, is there a better way to test the variable type other than what I suggested in this comment? Thanks

You can do `npm run start` from the field-dependent-dropdown directory to run the test page. If the plugin has tests, you can also do `npm run test` from the directory to run them.

**Comment by sdthaker** [comment]
One of the warnings that I'm dealing with is somewhat ambiguous since it doesn't say exactly what's the issue with the type definition. The warning is coming from [L50](https://github.com/google/blockly-samples/blob/master/plugins/migration/bin/fix-imports.js#L50).

Warning:
```javascript
warning  Syntax error in type: {
  import: string,
  oldIdentifier?: string,
  newIdentifier: string,
  newImport: string,
  newRequire: string,
}  jsdoc/valid-types
```

Currently trying to fix it, any help would be appreciated! Thanks!

**Comment by BeksOmega** [comment]
> One of the warnings that I'm dealing with is somewhat ambiguous since it doesn't say exactly what's the issue with the type definition. The warning is coming from [L50](https://github.com/google/blockly-samples/blob/master/plugins/migration/bin/fix-imports.js#L50).
> 
> Warning:
> 
> ```js
> warning  Syntax error in type: {
>   import: string,
>   oldIdentifier?: string,
>   newIdentifier: string,
>   newImport: string,
>   newRequire: string,
> }  jsdoc/valid-types
> ```
> 
> Currently trying to fix it, any help would be appreciated! Thanks!

Hmm is that the full text of the error or is there other information? My guess is that it might be a problem with the `oldIdentifier?:`. Could you try changing it to `oldIdentifier: string|undefined,`? But I'm not sure!

**Comment by sdthaker** [comment]
> > One of the warnings that I'm dealing with is somewhat ambiguous since it doesn't say exactly what's the issue with the type definition. The warning is coming from [L50](https://github.com/google/blockly-samples/blob/master/plugins/migration/bin/fix-imports.js#L50).
> > Warning:
> > ```js
> > warning  Syntax error in type: {
> >   import: string,
> >   oldIdentifier?: string,
> >   newIdentifier: string,
> >   newImport: string,
> >   newRequire: string,
> > }  jsdoc/valid-types
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Currently trying to fix it, any help would be appreciated! Thanks!
> 
> Hmm is that the full text of the error or is there other information? My guess is that it might be a problem with the `oldIdentifier?:`. Could you try changing it to `oldIdentifier: string|undefined,`? But I'm not sure!

### Proposed code changes
![image](https://github.com/google/blockly-samples/assets/71615163/553882cc-6f02-43d2-b463-f871b314273f)

### Warning post adding proposed changes
![image](https://github.com/google/blockly-samples/assets/71615163/1de53fd5-2831-45bb-a49c-3bffc4629597)

### TS Error post adding proposed changes
![image](https://github.com/google/blockly-samples/assets/71615163/60dabb81-aa4b-493e-b2b7-ac662b59bf1f)

**Comment by maribethb** [comment]
My wild guess is it's the trailing comma after `newRequire: string`

The `?` is allowed under Closure syntax, so that should be fine. You can find more info about this rule here https://github.com/gajus/eslint-plugin-jsdoc/blob/main/docs/rules/valid-types.md#readme

and valid closure types [here](https://github.com/google/closure-compiler/wiki/Types-in-the-Closure-Type-System)

**Comment by sdthaker** [comment]
> My wild guess is it's the trailing comma after `newRequire: string`
> 
> The `?` is allowed under Closure syntax, so that should be fine. You can find more info about this rule here https://github.com/gajus/eslint-plugin-jsdoc/blob/main/docs/rules/valid-types.md#readme
> 
> and valid closure types [here](https://github.com/google/closure-compiler/wiki/Types-in-the-Closure-Type-System)

I did try removing the trailing comma and I still received the warning! :)

**Comment by BeksOmega** [comment]
@sdthaker I think the easiest thing to do now is to put up a PR with what you've got, then I can pull it down and figure out what's up with this specific type =)

**Comment by sdthaker** [comment]
> @sdthaker I think the easiest thing to do now is to put up a PR with what you've got, then I can pull it down and figure out what's up with this specific type =)

I was actually thinking of doing that today! LOL! Perfect, so I’d silence the warning through an ESLint rule for that piece if code and we can take it up later if the code changes needs to be removed based on your feedback!

**Comment by maribethb** [comment]
You can also just leave it un-silenced. Warnings don't block the CI or anything, and this is one we should probably actually resolve if there's really an invalid type, so it's fine to not be silenced. Thanks for looking into this, Beka!
