### ISSUE TITLE
Re-enable the `jsdoc/tag-lines` eslint rule

### ISSUE THREAD

**Issue by maribethb** [rachel-fenichel/blockly-samples#1979]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Component

all

### Problem

In https://github.com/google/blockly-samples/pull/1946, we adjusted the way linting works in the repo and had to disable some rules. One of them is the `jsdoc/tag-lines` rule, which controls how many empty lines should be present between the description paragraph and any tags present.

In the `eslint.config.js` file, find the commented out line for `jsdoc/tag-lines` in the section of rules that applies to TypeScript file. Uncomment the line and remove the TODO comment.

### Request

To close this issue:

- Wait for https://github.com/google/blockly-samples/pull/1946 to be submitted
- In the `eslint.config.js` file, find the commented out line for `jsdoc/tag-lines` in the section of rules that applies to TypeScript file. Uncomment the line and remove the TODO comment.
- Run `npm run lint:fix` from the root of blockly-samples to automatically fix all of the issues related to this eslint rule
- Open a PR with the changes

**Comment by jaas666** [comment]
I can help with this if needed once #1946 gets merged

**Comment by barkhaaroraa** [comment]
could i work on this?

**Comment by BeksOmega** [comment]
@jaas666 were you still interested in working on this?

**Comment by jaas666** [comment]
Sorry, no bandwidth at the moment.
You can assign to @barkhaaroraa

**Comment by sdthaker** [comment]
Let me know if this is still up for grabs, might be related to #1978, since running `npm run lint:fix` shows 16 warnings in total which I'm fixing in 1978. Would like to work on this issue! Thanks!

**Comment by BeksOmega** [comment]
Done @sdthaker ! I'll get you feedback on your other PRs/issues this morning =)
