### ISSUE TITLE
Update prettier config for quoted object properties

### ISSUE THREAD

**Issue by maribethb** [rachel-fenichel/blockly-samples#1980]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Component

all

### Problem

In the prettier config in https://github.com/google/blockly-samples/pull/1946, we set the `quoteProps` rule to "preserve". This was necessary in blockly core as we have some properties that must remain quoted due to the closure compiler. Since we don't use closure compiler in samples, we don't need to keep this setting. We can set the rule to `consistent` meaning only add quotations to properties that must be quoted, and then if any property in an object is quoted, all of them will be to remain consistent.

### Request

To close this issue:

1. Wait for https://github.com/google/blockly-samples/pull/1946 to be submitted
2. Set the `quoteProps` rule to `consistent` in the `.prettierrc.js` file
3. Run `npm run format` to automatically fix all properties.

**Comment by barkhaaroraa** [comment]
i'd like to work on this

**Comment by BeksOmega** [comment]
Go for it @barkhaaroraa =) If you have any questions don't hesitate to ask!

**Comment by shivalipatel6** [comment]
Hi can I take this one on?

**Comment by BeksOmega** [comment]
Go for it @shivalipatel6 =)
