### ISSUE TITLE
"Hacker mode" theme

### ISSUE THREAD

**Issue by rachel-fenichel** [rachel-fenichel/blockly-samples#1988]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Component

New theme plugin.

### Problem

I think code looks cooler in black and green.

### Request

Create a theme with:
- black background
- black block fill for all block types
- white outline for all block types
- green text for all block types
- dark toolbox
- dark flyout
- monospace text

Starter image of what I'm thinking about:
![image](https://github.com/google/blockly-samples/assets/13686399/25a38ce4-56a7-46cb-9162-47625c5f3ad7)

### Additional context

An all-white mode with monospace text would also be fun.

## To Fix

1) Run the `@blockly/create-package` script to create a new theme plugin.
2) Create the theme. You can check out our [theme docs](https://developers.google.com/blockly/guides/configure/web/appearance/themes) for help.
3) Run `npm run start` to test that your theme looks correct.

**Comment by shivalipatel6** [comment]
Hi! would you mind assigning me this issue? I'm pretty new at this but I have been reading the other theme plug ins, so I think I am ready to take it on!

**Comment by BeksOmega** [comment]
Go for it @shivalipatel6 ! If you have any questions, don't hestitate to ask =)

**Comment by BeksOmega** [comment]
Heya @shivalipatel6 Are you still interested in working on this issue?

**Comment by shivalipatel6** [comment]
Yes! I am, I just got a little caught up these past couple of days

**Comment by shivalipatel6** [comment]
Hi @BeksOmega I have been having some trouble running the create-package script to get started on this theme. I've been looking through the blockly pages to see if I messed up somewhere but I can't figure out what's going on. I attached a picture of my terminal below. Could you pass along some pointers?
<img width="366" alt="hacker-mode issue" src="https://github.com/google/blockly-samples/assets/56765670/b5940dbe-5788-4e2b-80a3-ed88aafe506a">

**Comment by BeksOmega** [comment]
> Hi @BeksOmega I have been having some trouble running the create-package script to get started on this theme. I've been looking through the blockly pages to see if I messed up somewhere but I can't figure out what's going on. I attached a picture of my terminal below. Could you pass along some pointers? <img alt="hacker-mode issue" width="366" src="https://user-images.githubusercontent.com/56765670/281529462-b5940dbe-5788-4e2b-80a3-ed88aafe506a.PNG">

Hello! Are you using the latest version of npm and node? I would try using node v20 and npm v9!

**Comment by shivalipatel6** [comment]
I am not using the latest version, It seems that my system is still in node v12 and npm v8. I am still trying to figure out how to fix that since my systems since I am using Ubuntu and those seem to be the highest versions that works with Ubuntu. Thanks for the help!

**Comment by BeksOmega** [comment]
> I am not using the latest version, It seems that my system is still in node v12 and npm v8. I am still trying to figure out how to fix that since my systems since I am using Ubuntu and those seem to be the highest versions that works with Ubuntu. Thanks for the help!

As far as I know the higher versions should work on ubuntu, it just comes preinstalled with node v12. You should be able to download the latest lts (long term support) version [here](https://nodejs.org/en)!

**Comment by shivalipatel6** [comment]
Hi @BeksOmega thanks for the help earlier! I figured it out! I was wondering if you could help me locate the part of the blockly code that interacts with the font. I have been trying to figure out how to change the font color, but I am unsure how since there wasn't anything that mentioned how to do that in the Themes section of the documentation.

**Comment by BeksOmega** [comment]
> Hi @BeksOmega thanks for the help earlier! I figured it out! I was wondering if you could help me locate the part of the blockly code that interacts with the font. I have been trying to figure out how to change the font color, but I am unsure how since there wasn't anything that mentioned how to do that in the Themes section of the documentation.

You can set the font as part of a theme as documented [here](https://developers.google.com/blockly/guides/configure/web/appearance/themes#font_styles)! If you have any further questions let me know =)

**Comment by shivalipatel6** [comment]
> > Hi @BeksOmega thanks for the help earlier! I figured it out! I was wondering if you could help me locate the part of the blockly code that interacts with the font. I have been trying to figure out how to change the font color, but I am unsure how since there wasn't anything that mentioned how to do that in the Themes section of the documentation.
> 
> You can set the font as part of a theme as documented [here](https://developers.google.com/blockly/guides/configure/web/appearance/themes#font_styles)! If you have any further questions let me know =)

Hi @BeksOmega  =I have already checked this, the documentation says that the object only includes family, weight and size. I have tried to change the font color in there but when I do so my IDE says that the object only accepts these  3 parameters.

**Comment by BeksOmega** [comment]
> > > Hi @BeksOmega thanks for the help earlier! I figured it out! I was wondering if you could help me locate the part of the blockly code that interacts with the font. I have been trying to figure out how to change the font color, but I am unsure how since there wasn't anything that mentioned how to do that in the Themes section of the documentation.
> > 
> > 
> > You can set the font as part of a theme as documented [here](https://developers.google.com/blockly/guides/configure/web/appearance/themes#font_styles)! If you have any further questions let me know =)
> 
> Hi @BeksOmega =I have already checked this, the documentation says that the object only includes family, weight and size. I have tried to change the font color in there but when I do so my IDE says that the object only accepts these 3 parameters.

Heya @shivalipatel6 Sorry I missed that you were specifically asking about font color. I dug into this a bit and I don't think we have a good way of doing this at the moment because of how our css rules are structured :/ But I'm planning to dig into that more soon!

Could you put up a PR with what you have so far? We can leave the plugin as private for now and fix the font color once we've determined the best way to handle it.
