### ISSUE TITLE
Normalize plugins name based on the action, and npm name

### ISSUE THREAD

**Issue by SebCanet** [rachel-fenichel/blockly-samples#2000]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Component

Various plugins have name which does not indicate what it's working on, and should be changed:

- content-highlight -> workspace-content-highlight
- continuous-toolbox -> toolbox-continuous-categories
- cross-tab-copy-paste named "plugin-cross-tab-copy-paste", and "plugin" should be used for everything else thant block nor workspace
- dev-create named "create-package" -> dev-plugin-creation-package-tool ; and "dev" should be used when it's tools useful for developping but with no impact on workspace, blocks, or backoffice like "plugins" one
- disable-top-blocks -> block-disable-top-blocks
- field-angle -> block-field-angle
- field-something -> let it like that or maybe rename in "block-field-something"?
- keyboard-navigation -> workspace-keyboard-navigation
- migration which is also named "migrate" -> dev-migration-tool?
- modal, also named "plugin-modal" -> plugin-modal
- scroll-options, also named "plugin-scroll-options" -> workspace-scroll-options
- serialize-disabled-interactions, also named "plugin-serialize-disabled-interactions" and should keep it
- shadow-block-converter -> block-shadow-block-converter
- strict-connection-checker, also named "plugin-strict-connection-checker" -> block-strict-connection-checker
- suggested-blocks -> workspace-suggested-blocks
- theme seem ok
- typed-variable-modal, also named "plugin-typed-variable-modal" and should keep it.
- workspace-search, also named "plugin-workspace-search" but should keep "workspace-search"
- zoom-to-fit -> workspace-zoom-to-fit

### Description

Several plugins have a name that doesn't indicate what they're doing. For example, we have "**block**-plus-minus", which acts on blocks, but "content-highlight" has a name that doesn't indicate that it acts on workspace.
In the same way, the npm name does not match the common name, for example the "content-highlight" is installed via the npm command which searches for "**workspace**-content-highlight".
Ideally, the name via npm should be the same as the "user friendly" name of the plugin, also the github folder, and should include the object on which it acts (block, workspace, etc).

### Reproduction steps

1. verify in github repo
2. verify name in npm
3 .verify the field action of the plugin

**Comment by rachel-fenichel** [comment]
We don't want to rename things on npm given that we have already published things under their current names and they are in use in other people's apps. We're making an effort to be more consistent going forward.
