### ISSUE TITLE
ContinuousToolbox is not re-enabled after deleting blocks from workspace with maxBlocks option

### ISSUE THREAD

**Issue by rodrigorgs** [rachel-fenichel/blockly-samples#2002]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Component

ContinuousToolbox

### Description

I'm creating a workspace with the `ContinuousToolbox`, and limiting the maximum number of blocks (`maxBlocks`):

```js
    var workspace = Blockly.inject('blocklyDiv', {
        toolbox: getToolboxJSON(window.workspaceConfig?.toolbox?.blocks),
        trashcan: true,
        renderer: 'zelos',
        maxBlocks: 10,
        plugins: {
            'toolbox': ContinuousToolbox,
            'flyoutsVerticalToolbox': ContinuousFlyout,
            'metricsManager': ContinuousMetrics,
        },  
    });
```

As expected, the toolbox is disabled when the number of blocks in the workspace reaches the maximum, but it is not re-enabled when blocks are deleted.

When I use the original toolbox, by removing the `plugins:` key, the toolbox works as expected.

### Reproduction steps

1. Add blocks to the workspace until `maxBlocks` is reached. The blocks in the toolbox are disabled, as expected.
2. Remove one block from the workspace. The blocks remain disabled; it should be expected that they are re-enabled.

**Comment by gonfunko** [comment]
I wasn't able to repro this - are you using built-in blocks, or a set of custom ones?

**Comment by BeksOmega** [comment]
I'm having a similar issue with `maxInstances` where the block is never disabled:
![Screen recording 2023-10-06 11 42 05 AM](https://github.com/google/blockly-samples/assets/25440652/792960b2-14a9-4b1b-bc42-b2e25721d4b3)

**Comment by rodrigorgs** [comment]
> I wasn't able to repro this - are you using built-in blocks, or a set of custom ones?

I'm using custom blocks, the `zelos` theme, and a resizable workspace.

However, I wasn't able to reproduce the problem with a minimum example.

The full repository of the project I'm working on is at <https://github.com/rodrigorgs/blocomp>, but I've evolved the code base so it may not be trivial to get back to the state in which the problem manifests itself.

As a workaround, I introduced a change listener:

```typescript
    const maxBlocks = 2; // for instance
    workspace.addChangeListener((event) => {
        const blocks = workspace.getAllBlocks(false).filter(b => b.type !== 'comment');
        const blocksCount = blocks.length;
        const toolbox = workspace.getToolbox() as ContinuousToolbox;
        const flyout = toolbox.getFlyout();
        if (event.type == Blockly.Events.CREATE) {
            if (blocksCount > maxBlocks) {
                Toast.fire({
                    icon: 'error',
                    title: `You cannot add more than ${maxBlocks} blocks`
                });
                workspace.undo(false);
            }
        } else if (blocksCount == maxBlocks) {
            flyout.workspace_.getTopBlocks(false).forEach((block: any) => {
                block.setEnabled(false);
            });
        }
    });
```

**Comment by BeksOmega** [comment]
@alicialics when you have a min could you comment here so I can assign you to this issue? Just want to make sure no one else grabs it! So I've temporarily assigned myself =)

**Comment by alicialics** [comment]
comment!
