### ISSUE TITLE
Enable strict mode for content-highlight

### ISSUE THREAD

**Issue by maribethb** [rachel-fenichel/blockly-samples#2028]
### Check for duplicates

- [ ] I have searched for similar issues before opening a new one.

### Component

content-highlight

### Request

The content-highlight plugin does not have "[strict mode](https://www.typescriptlang.org/tsconfig#strict)" enabled for TypeScript. We should enable it to have better type checking for our plugins, but doing so may show some TypeScript errors that need to be fixed first.

This would be a good first issue for anyone experienced with working in TypeScript. You may need to adjust types, add checks for null or undefined, or make other fixes. If you have questions, feel free to ask here! In general, the team prefers avoiding casts and using `!` to coerce non-null types, and instead adding appropriate checks.

To work on this issue:

1. Run `npm install` at the root of Blockly samples to set up dependencies.
2. Navigate to the plugin's directory
1. Change `strict: false` to `strict: true` in the plugin's tsconfig.json
2. Run `npm run build` and see if there are any TypeScript errors.
3. Resolve any TypeScript errors, if present. If not, then we got lucky and accidentally wrote strict code! Yay!
4. Run `npm run build` again to make sure there are no TypeScript errors.
5. Run `npm run start` and play with the plugin in the playground to make sure the plugin still behaves as expected.
6. Run `npm run test` to run any automated tests.
7. Run `npm run lint` to make sure there are no formatting errors.
8. Open a PR with your changes!

**Comment by kapooraryan** [comment]
@BeksOmega Could I give this a try?

**Comment by BeksOmega** [comment]
@kapooraryan Go for it!

**Comment by kapooraryan** [comment]
@BeksOmega Thanks! Also unrelated but had a doubt as to whether the blockly library will be included as a part of this year's GSoC?

**Comment by kapooraryan** [comment]
Hey, @BeksOmega I am not sure how to go about resolving the below error. I have fixed the others that were occurring. Is there any reference I could look into for the same?
![CH_TS_One](https://github.com/google/blockly-samples/assets/69362333/d4a1db9b-c455-4ff0-ba98-0bd38dc811d3)

**Comment by BeksOmega** [comment]
> @BeksOmega Thanks! Also unrelated but had a doubt as to whether the blockly library will be included as a part of this year's GSoC?

At the moment we're not planning on participating in GSoC! But App Inventor (which uses Blockly) usually participates =)

> Hey, @BeksOmega I am not sure how to go about resolving the below error. I have fixed the others that were occurring. Is there any reference I could look into for the same?

I'm not sure what line is causing the error exactly! But generally if something is possibly null and you want to make sure it's not, you can use an early return to make the compiler happy.

```
if (!myPossiblyNullThing) return;
```

**Comment by kapooraryan** [comment]
> > @BeksOmega Thanks! Also unrelated but had a doubt as to whether the blockly library will be included as a part of this year's GSoC?
> 
> At the moment we're not planning on participating in GSoC! But App Inventor (which uses Blockly) usually participates =)
> 
> > Hey, @BeksOmega I am not sure how to go about resolving the below error. I have fixed the others that were occurring. Is there any reference I could look into for the same?
> 
> I'm not sure what line is causing the error exactly! But generally if something is possibly null and you want to make sure it's not, you can use an early return to make the compiler happy.
> 
> ```
> if (!myPossiblyNullThing) return;
> ```

Thanks, that seems to solve the issue. I'll look into the MIT App Inventor Org as suggested as I wanted to contribute on a more serious basis if possible :)!
