### ISSUE TITLE
Enable strict mode for workspace-search

### ISSUE THREAD

**Issue by maribethb** [rachel-fenichel/blockly-samples#2032]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Component

workspace-search

### Request

The workspace-search plugin does not have "[strict mode](https://www.typescriptlang.org/tsconfig#strict)" enabled for TypeScript. We should enable it to have better type checking for our plugins, but doing so may show some TypeScript errors that need to be fixed first.

This would be a good first issue for anyone experienced with working in TypeScript. You may need to adjust types, add checks for null or undefined, or make other fixes. If you have questions, feel free to ask here! In general, the team prefers avoiding casts and using `!` to coerce non-null types, and instead adding appropriate checks.

To work on this issue:

1. Run `npm install` at the root of Blockly samples to set up dependencies.
2. Navigate to the plugin's directory
1. Change `strict: false` to `strict: true` in the plugin's tsconfig.json
2. Run `npm run build` and see if there are any TypeScript errors.
3. Resolve any TypeScript errors, if present. If not, then we got lucky and accidentally wrote strict code! Yay!
4. Run `npm run build` again to make sure there are no TypeScript errors.
5. Run `npm run start` and play with the plugin in the playground to make sure the plugin still behaves as expected.
6. Run `npm run test` to run any automated tests.
7. Run `npm run lint` to make sure there are no formatting errors.
8. Open a PR with your changes!

**Comment by ghoshvidip26** [comment]
Please assign this issue to me.

**Comment by BeksOmega** [comment]
Go for it @Vidip-Ghosh If you have any questions, don't hesitate to reach out here!

**Comment by ghoshvidip26** [comment]
<img width="1130" alt="Screenshot 2023-10-30 at 22 33 04" src="https://github.com/google/blockly-samples/assets/91741581/8f638f8f-0514-4a23-bd66-940768866204">
Its a `jsconfig` file instead of `tsconfig`. So should I update this?

**Comment by maribethb** [comment]
Hi @Vidip-Ghosh , you are looking at the file `plugins/jsconfig.json`. You need to look at `plugins/workspace-search/tsconfig.json`. I hope that helps! Let us know if you have further questions.

**Comment by ghoshvidip26** [comment]
> Hi @Vidip-Ghosh , you are looking at the file `plugins/jsconfig.json`. You need to look at `plugins/workspace-search/tsconfig.json`. I hope that helps! Let us know if you have further questions.

Okay, I got it thank you 👍

**Comment by ghoshvidip26** [comment]
<img width="1680" alt="Screenshot 2023-10-31 at 15 31 09" src="https://github.com/google/blockly-samples/assets/91741581/42e7bf97-0b36-44f0-8b44-e5e7c1e715da">
I got this error. How can I solve?

**Comment by sdthaker** [comment]
Hi, again @BeksOmega! I'd like to work on this issue if it is up for grabs. Thanks!
