### ISSUE TITLE
Fix text for the disable top blocks plugin on the demo page

### ISSUE THREAD

**Issue by BeksOmega** [rachel-fenichel/blockly-samples#2081]
### Check for duplicates

- [x] I have searched for similar issues before opening a new one.

### Component

https://github.com/google/blockly-samples/blob/a9ac5cb292620932128299d91a148f1be1f5a8b7/gh-pages/_index.html#L318

### Description

The current text states that the plugin disables top blocks, which is does not do. That behavior is handled by a change listener that is exported from core and can be optionally registered.

## To Fix

Replace the current text with `A plugin that hides the 'Enable' context menu option for orphan blocks. Works with the <code>Blockly.Events.disableOrphans</code> change listener in core.`

**Comment by shivalipatel6** [comment]
Hi Could I take this on?

**Comment by BeksOmega** [comment]
Go for it @shivalipatel6 =)
