### ISSUE TITLE
Field multiline rendering incorrectly for long inputs.

### ISSUE THREAD

**Issue by BeksOmega** [rachel-fenichel/blockly-samples#2095]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Component

field-multilineinput

### Description

When you type a bunch of letters into the multiinline iput field, they kind of appear to start a newline.

### Reproduction steps

1. Run `npm run start` in the field-multilineinput directory.
2. Drag out a multiline input block.
3. Type a bunch of letters into the field (no newlines).
4. Observe how the rendering is weird

### Screenshots

[Screen recording 2023-12-05 3.24.46 PM.webm](https://github.com/google/blockly-samples/assets/25440652/b0228508-05ae-49cf-940c-71a41f30bb4a)

**Comment by BeksOmega** [comment]
Looks like this only happens when the window is zoomed.

**Comment by maribethb** [comment]
https://github.com/google/blockly-samples/issues/2235 same issue in core
