### ISSUE TITLE
Can't  add 'dummy input field' in /plugins/block-plus-minus !

### ISSUE THREAD

**Issue by AdwardWong** [rachel-fenichel/blockly-samples#2120]
### Check for duplicates

- [x] I have searched for similar issues before opening a new one.

### how to make the 'value input field' into 'dummy input field' ,like the right's block as beblow.
<img width="408" alt="截屏2023-12-15 10 02 20" src="https://github.com/google/blockly-samples/assets/13374858/a62e296f-779e-4ad2-91de-5bce04187c2a">

### Reproduction steps

1. open the  "blockly-samples-master"
2. run the "/plugins/block-plus-minus" project.
3. can't the "dummy input field" into it.

### Screenshots

<img width="408" alt="截屏2023-12-15 10 02 20" src="https://github.com/google/blockly-samples/assets/13374858/562b1dfc-49d2-4664-bbf9-8ccdcc2f4458">

**Comment by maribethb** [comment]
Hello,

I'm not quite sure what you're asking for. This plugin provides specific blocks. If you want different blocks to also have a +/- button, you would have to implement those blocks yourself. You can follow the code in the plugin as an example for how to do so.

If that doesn't answer your question, please add more information and reopen this issue. It would also help us if you could translate the text on your blocks for us. Thank you!
