### ISSUE TITLE
Forbidden non-null assertion in workspace-minimap/src/positioned_minimap.ts

### ISSUE THREAD

**Issue by kapooraryan** [rachel-fenichel/blockly-samples#2123]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Component

The workspace-minimap plugin.

### Description

Since strict mode has been enabled for this plugin, this lint error should not occur. Note: The code may be correct as this is just a warning.

### Reproduction steps

1. Run npm run lint on the workspace-minimap plugin.

### Screenshots

![image](https://github.com/google/blockly-samples/assets/69362333/52db5761-bdd9-43e8-bf3d-b90ee480696b)

**Comment by BeksOmega** [comment]
@kapooraryan did you want to be assigned to this?

**Comment by kapooraryan** [comment]
> @kapooraryan did you want to be assigned to this?

Hey yes, I'd like to fix the warning

**Comment by BeksOmega** [comment]
> > @kapooraryan did you want to be assigned to this?
> 
> Hey yes, I'd like to fix the warning

Sweet, go for it :D Thank you for your interest!
