### ISSUE TITLE
minimap shows comments different than in the main window

### ISSUE THREAD

**Issue by koenvanwijk** [rachel-fenichel/blockly-samples#2129]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Component

workspace-minimap

### Description

When a comment is open it show a differnent rendering than the main windows. 
![image](https://github.com/google/blockly-samples/assets/8227977/38da88b8-8b46-401b-a1e6-daec5fec0162)

### Reproduction steps

1. Add a comment to block
2. Resuze the comment
3. Look at the minimap

**Comment by maribethb** [comment]
This is working as intended on our end - the minimap is a readonly workspace and that's what readonly comments look like.
