### ISSUE TITLE
Minimap does not respect the dark-theme

### ISSUE THREAD

**Issue by koenvanwijk** [rachel-fenichel/blockly-samples#2130]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Component

workspace-minimap

### Description

When a minimap is opened on a dark-theme, it still uses the 'normal' theme for colouring.
![image](https://github.com/google/blockly-samples/assets/8227977/48488875-2147-432f-ab85-34d6a56df76b)

### Reproduction steps

1. Open a minimap in a workspace with dark-theme

**Comment by maribethb** [comment]
Hi @koenvanwijk I can't reproduce this on the [test page](https://google.github.io/blockly-samples/plugins/workspace-minimap/test/index.html#theme=dark&debugEnabled=false). Is it possible there is conflicting css on your page? Or can you provide more in depth reproduction steps? Thanks!

**Comment by maribethb** [comment]
Hi @koenvanwijk feel free to reopen if you can provide more detailed reproduction steps. Thanks!

**Comment by koenvanwijk** [comment]
Indeed it looks find on the playground, sorry for the confusion.
________________________________
