### ISSUE TITLE
Issue with workspace-back type export

### ISSUE THREAD

**Issue by ktaicoder** [rachel-fenichel/blockly-samples#2135]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Component

workspace backpack

### Description

I am using workspace-back and encountering the following error during the build process:

```
Type error: Re-exporting a type when 'isolatedModules' is enabled requires using 'export type'.
   7 | export {Backpack} from './backpack';
   8 | export * from './ui_events';
>  9 | export {BackpackOptions, BackpackContextMenuOptions} from './options';
```

The build succeeds when I make the following modification:
```js
export type {BackpackOptions, BackpackContextMenuOptions} from './options';
```

Is there any alternative solution to resolve this issue, other than the mentioned approach?

### Reproduction steps

1. 
2. 
3.

### Screenshots

![image](https://github.com/google/blockly-samples/assets/91987855/fea896b5-59f0-42ea-8caa-45a8b2daeb2d)

**Comment by maribethb** [comment]
Hi @ktaicoder thanks for opening this issue. I believe your suggested solution is correct. We would accept a PR for this if you'd like to make one! That will help us ensure the issue is fixed faster.

**Comment by ktaicoder** [comment]
I have created a pull request for this content.
PR #2148
