### ISSUE TITLE
Cleanup after deleting blocks and fields from core

### ISSUE THREAD

**Issue by rachel-fenichel** [rachel-fenichel/blockly-samples#2194]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Component

Angle, colour, and multiline input fields.

### Description

After #2162 there will be multiple pieces of code in field plugins that compensate for the blocks and fields already being installed as part of the core library. Once the fields are removed form core (https://github.com/google/blockly/issues/7226), the plugins will need to be updated.

Examples include
- In test pages, deleting blocks and generators for blocks provided by the plugin.
- In field registration functions, unregistering existing fields before registering the new ones.

**Comment by BeksOmega** [comment]
Is this release blocking? If so, might be good to bump the priority. I think we might not get to some of the P1s this Q, and I don't want this to get lost.

**Comment by rachel-fenichel** [comment]
No, this isn't release blocking. These are only changes in samples, and the existing code will not break when the fields are deleted from core--it'll just be useless clutter.

**Comment by rachel-fenichel** [comment]
To find the remaining work, search for `TODO(2194)` in the codebase.
