### ISSUE TITLE
Continuous toolbox doesn't include padding above category labels when scrolling to them

### ISSUE THREAD

**Issue by BeksOmega** [rachel-fenichel/blockly-samples#2207]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Component

continuous-toolbox

### Description

When you click on a category icon to scroll to it, it puts the label for the category directly at the top of the flyout instead of including padding.

### Reproduction steps

1. Load up the continuous toolbox demo.
2. Click on one of the categories to scroll to it.
3. Observe how the labels are directly at the top of the flyout.

### Screenshots

![image](https://github.com/google/blockly-samples/assets/25440652/80f06883-59c5-4714-9407-85151d554307)

### Additional Info

We need this fix for scratch.

**Comment by maribethb** [comment]
@gonfunko interested in fixing this?

**Comment by gonfunko** [comment]
Sure!
