### ISSUE TITLE
Disposing of a procedure definition disposes caller *and* next blocks

### ISSUE THREAD

**Issue by BeksOmega** [rachel-fenichel/blockly-samples#2217]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Component

block-sharable-procedures

### Description

When you dispose of a procedure definition, it disposes of the callers (this is correct). However, it also disposes of the callers next blocks, which is not correct.

### Reproduction steps

1. Create the following arrangement in the sharable procedures demo
![image](https://github.com/google/blockly-samples/assets/25440652/b442bd5b-dda2-4636-9fd7-e85d86db320e)

3. Delete the procedure definition block
4. Observe how only the top level if block remains. Instead the two if blocks should be connected in a stack.

## To fix

1. Pass `true` [here](https://github.com/google/blockly-samples/blob/770d03dfdfb3bccf49bc74bf986b25f6bf4d32c3/plugins/block-shareable-procedures/src/blocks.ts#L1068). 
2. Repeat the reproduction steps and ensure only the procedure call block is deleted, not all of its children
3. Add a unit test as part of [this suite](https://github.com/google/blockly-samples/blob/770d03dfdfb3bccf49bc74bf986b25f6bf4d32c3/plugins/block-shareable-procedures/test/procedure_blocks.mocha.js#L1280) that tests to ensure the child blocks of the caller are not deleted.

The `dispose` function takes an optional parameter that controls whether to "heal" the stack of blocks when one is deleted. If true, only the one block will be deleted and the child blocks of it will be connected to the deleted block's parent, if possible. If false (or unset, as here) the block and its children will be deleted.

If you'd like to work on this issue and you're new to Blockly / blockly-samples, there are some guidelines [here](https://developers.google.com/blockly/guides/contribute/samples). Comment on this issue if you'd like to work on it so we can assign it to you.

**Comment by sancodes** [comment]
Hello, 

If this is still open, maybe I'll try to take on this issue. :)

**Comment by BeksOmega** [comment]
@sancodes Go for it =) Let us know if you have any questions!

**Comment by sancodes** [comment]
Hello @BeksOmega, 

I tried the testing logic, and tried to be descriptive of my approach, and not sure, if the test was correct. 
Let me know what needs fix :)
