### ISSUE TITLE
shareable procedure plugin only support json format lost xml way,hope support it again

### ISSUE THREAD

**Issue by mlzboy** [rachel-fenichel/blockly-samples#2231]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Component

shareable procedure plugin 

### Problem

currently i'm using v9.2.1 version blockly,and found most of plugin support the newest version of blockly when we use in project could not alwalys follow the update step,hope back support like ubuntu Long Time Support Version

### Request

shareable procedure plugin only support json format lost xml way

**Comment by maribethb** [comment]
Hi! The shareable procedures plugin can't support XML. It relies on a new feature, custom serializers, that only exists in the JSON serialization system. 

If you're interested in updating to JSON from XML, we recommend you check out [this guide](https://docs.google.com/document/d/1wv5ORrO4icVHeU15FLSn37mdNLyJpQbMTo7mmTqsGl0/edit) and post on the forum to get support. Thanks!
