### ISSUE TITLE
Update field colour readme to explain that the developer must load a message file/set a locale

### ISSUE THREAD

**Issue by rachel-fenichel** [rachel-fenichel/blockly-samples#2238]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Request

Some of the blocks in the field-colour plugin have text on the blocks, which means they rely on message files being loaded. This is done correctly in the playground and tests, but is not noted in the readme. The resulting error is hard to debug without context.

**Comment by BeksOmega** [comment]
Might also be helpful to update the error, what does it currently say?

**Comment by rachel-fenichel** [comment]
If the message files aren't loaded the blocks look like this. It's not different from other cases without messages.
![image](https://github.com/google/blockly-samples/assets/13686399/8abc4d98-733f-46e0-b787-d32490b9d261)
