### ISSUE TITLE
Merge `blocks_for_fields` into `master`

### ISSUE THREAD

**Issue by rachel-fenichel** [rachel-fenichel/blockly-samples#2243]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Request

The `blocks_for_fields` branch add blocks to some of the plugins and also makes breaking changes to how they are installed (requires explicit installation of the blocks and fields, instead of doing it on file load).

This requires a TS change that went live in the most recent version of `blockly`, and it does not need to wait until v11.

**Comment by maribethb** [comment]
@rachel-fenichel can we close this / mark as done or is there still more to do for this task?
