### ISSUE TITLE
typed-variable-modal plugin is not on plugins index page

### ISSUE THREAD

**Issue by maribethb** [rachel-fenichel/blockly-samples#2333]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Component

typed-variable-modal

### Description

The [typed-variable-modal plugin](https://google.github.io/blockly-samples/plugins/typed-variable-modal/test/index.html) is not listed on the [plugins demo page](https://google.github.io/blockly-samples/), making it harder to discover

To fix this issue, follow these steps. Keep in mind the [basics of contributing to blockly-samples](https://developers.google.com/blockly/guides/contribute/samples) as well.

1. In the `gh-pages` directory, locate the `_index.html` file. This is where you'll make the changes.
2. Add an entry for the Typed Variable Modal plugin that follows the same format as the other plugins. This plugin should go in the "Toolbox" section.
3. Take a screenshot of the plugin with the modal open on the [test page](https://google.github.io/blockly-samples/plugins/typed-variable-modal/test/index.html), upload the screenshot to the `gh-pages/media` folder, and use that image in the entry for this plugin

### Reproduction steps

1. 
2. 
3.

**Comment by ashmichheda** [comment]
Hi @maribethb, I would love to contribute to this issue. Can you kindly assign it to me? Thanks!

**Comment by BeksOmega** [comment]
Go for it @ashmichheda ! Let us know if you have any questions =)

**Comment by ashmichheda** [comment]
@BeksOmega I am trying to push my local branch but I am getting permission denied error. Can you kindly help?

<img width="833" alt="push_error" src="https://github.com/google/blockly-samples/assets/31774401/ad333445-a765-49b8-b1d8-55a7ec91e724">

**Comment by maribethb** [comment]
Hi @ashmichheda,

In order to contribute to blockly-samples, you will need to create a Pull Request rather than pushing directly to this repo. You will push to your own fork of the repo, then open a PR to merge your changes into our repo. That way, your changes can be reviewed before they get merged in. You can read more about the process in our documentation [here](https://developers.google.com/blockly/guides/contribute/get-started#step_by_step), and that has links to more information in the GitHub docs as well.

**Comment by ashmichheda** [comment]
> Hi @ashmichheda,
> 
> In order to contribute to blockly-samples, you will need to create a Pull Request rather than pushing directly to this repo. You will push to your own fork of the repo, then open a PR to merge your changes into our repo. That way, your changes can be reviewed before they get merged in. You can read more about the process in our documentation [here](https://developers.google.com/blockly/guides/contribute/get-started#step_by_step), and that has links to more information in the GitHub docs as well.

Yes, that's exactly what I have done. I have forked this repo, created my PR branch, and now trying to push my PR branch which is on my local computer to remote.

**Comment by ashmichheda** [comment]
I'll re-try and open a PR. I think I may have missed forking it.

**Comment by maribethb** [comment]
The error message shows you are trying to push to `google/blockly-samples` but you need to push to your fork which is probably `ashmichheda/blockly-samples` unless you renamed it when you forked.

You can see which remotes you have on your computer by running `git remote -vv` which will list all of them and their names.

**Comment by ashmichheda** [comment]
PR up here: https://github.com/google/blockly-samples/pull/2335
