### ISSUE TITLE
`dev-tools` references exports deleted in Blockly v11

### ISSUE THREAD

**Issue by cpcallen** [rachel-fenichel/blockly-samples#2345]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Component

`plugins/dev-tools`

### Description

Building against a version of Blockly v11 with "import" conditional exports for `blockly/core`, I noted a number of webpack warnings for non-existent exports from `blockly/core`, mostly due to fields and other functionality that had been moved into plugins:

* [ ] `Blockly.FieldAngle`
* [ ] `Blockly.FieldColour`
* [ ] `Blockly.FieldAngle`
* [ ] `Blockly.navigation`
* [ ] `Blockly.prompt`—renamed `Blockly.dialog.prompt` in v7.20211209.0
  * #2344

These should be fixed by either adding a dependency on the required plugin or by removing the relevant functionality from this plugin.

* [ ] Check other plugins for similar issues.

### Reproduction steps

1.  Prepare `blockly` repository:
    1.  Check out `blockly` branch `tmp/samples-bug-2345`
    2.  In `blockly/` run:
        ```
        npm ci
        npm run package
        ```
0.  Prepare `blockly-samples` repository and link it against `blockly/dist`:
    1.  Check out  branch `rc/v11.0.0`
    0.  In `blockly-samples/` run:
        ```
        rm -rf plugins/*/node_modules
        npm ci
        cd plugins
        for d in * ; do (cd "$d" && [[ -d node_modules/blockly  ]] && rm -rf node_modules/blockly && ln -s ../../../../blockly/dist node_modules/blockly  ); done
        ```
0. In `blockly-samples/plugins/dev-tools`, run `npm start`.
0. Observe warnings as quoted below.

### Warnings

Some example errors (edited for length):
```
WARNING in ../block-test/src/fields/validators.js 144:23-41
export 'FieldAngle' (imported as 'Blockly') was not found in 'blockly/core' (possible exports: ASTNode, BasicCursor, … utils, zelos)

WARNING in ../block-test/src/fields/validators.js 222:28-47
export 'FieldColour' (imported as 'Blockly') was not found in 'blockly/core' (possible exports: ASTNode, BasicCursor, … utils, zelos)

WARNING in ../block-test/src/fields/validators.js 788:4-18
export 'prompt' (imported as 'Blockly') was not found in 'blockly/core' (possible exports: ASTNode, BasicCursor, … utils, zelos)

WARNING in ./src/playground/options.js 1089:8-54
export 'navigation' (imported as 'Blockly') was not found in 'blockly/core' (possible exports: ASTNode, BasicCursor, … utils, zelos)
```

**Comment by maribethb** [comment]
@cpcallen where are you seeing these compilation errors? I don't see them when running `npm start`

Though I didn't link to a local build of blockly. The `rc/v11` branch of samples is already set up to use the latest beta version, where the fields have already been removed. I don't think that should matter in that case.

Edit: I missed the part of your instructions where you have a specific branch of blockly to check out.

**Comment by maribethb** [comment]
These were all fixed and don't have warnings anymore
