### ISSUE TITLE
Typed variable model attepts to append to the widget div, which does not exist

### ISSUE THREAD

**Issue by BeksOmega** [rachel-fenichel/blockly-samples#2355]
### Check for duplicates

- [ ] I have searched for similar issues before opening a new one.

### Component

typed-variable-modal

### Description

See title

### Reproduction steps

1. Open the [test page](https://rachel-fenichel.github.io/blockly-samples/plugins/typed-variable-modal/test/index.html).
3. Open the console.
4. Open the Typed Variables category of the toolbox.
5. Click the “Create Typed Variable” button. Notice error in console and lack of modal.

### Stack trace

```shell
index.js:153 Uncaught TypeError: Cannot read properties of undefined (reading 'appendChild')
    at TypedVariableModal.widgetCreate_ (index.js:153:1)
    at TypedVariableModal.show (index.js:111:1)
    at eval (TypedVariableModal.js:122:1)
    at FlyoutButton$$module$build$src$core$flyout_button.onMouseUp (blockly_compressed.js:1014:179)
    at SVGGElement.f (blockly_compressed.js:85:149)
```

**Comment by maribethb** [comment]
This is due to there being multiple copies of blockly in the default setup for testing plugins. I "manually hoisted" the blockly dependency to force there to only be one, and the plugin works correctly. In other words, nothing is wrong with the plugin, only with the samples monorepo.
