### ISSUE TITLE
custom blocks were removed from sample-app

### ISSUE THREAD

**Issue by maribethb** [rachel-fenichel/blockly-samples#2366]
### Check for duplicates

- [ ] I have searched for similar issues before opening a new one.

### Component

sample-app
sample-ts-app

### Description

In https://github.com/google/blockly-samples/pull/2302 the custom blocks were removed from the toolboxes of the sample apps because they referenced the colour fields. However, demonstrating how to create custom blocks and add them to the toolbox is an essential part of the sample app. The apps should be updated to use the custom blocks, and the blocks just shouldn't use the colour field anymore.

### Reproduction steps

1. 
2. 
3.

**Comment by BeksOmega** [comment]
Would it actually be helpful to have them use the colour field in samples? Then we can show the sample app using a plugin (assuming it doesn't do that already)

**Comment by maribethb** [comment]
Yes, it would, but it's kind of a pain to keep examples updated as plugins are updated, and the stakes are higher if we break the sample app as opposed to breaking the react sample, so I'm conflicted on it.
