### ISSUE TITLE
remove references to `Blockly.FieldColour` from keyboard-navigation

### ISSUE THREAD

**Issue by maribethb** [rachel-fenichel/blockly-samples#2382]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Component

keyboard-navigation

### Description

The keyboard navigation attempts to patch `Blockly.FieldColour`. That field no longer exists, so even referencing it causes webpack warnings.

### To fix

1. In `navigation_controller.ts`, remove the lines that attempt to add or remove the `onShortcut` handler to `Blockly.FieldColour`.
2. In the same file, remove the now-unused `fieldColourHandler` function.

If you'd like to work on this issue see also our [contributing docs](https://developers.google.com/blockly/guides/contribute/samples) and comment here saying that you'd like to work on this.

### Reproduction steps

1. Run `npm run build` in `plugins/keyboard-navigation`
2. Notice warnings about how `Blockly.FieldColour` doesn't exist

**Comment by sancodes** [comment]
Hello, I can try to tackle this :)

**Comment by Vishesh-Paliwal** [comment]
hey @BeksOmega  , Can I get assigned for this issue . I would love to work on it

**Comment by BeksOmega** [comment]
Go for it @Vishesh-Paliwal =) Let me know if you have any questions!

**Comment by Vishesh-Paliwal** [comment]
Thanks @BeksOmega  for assigning . Raised a PR for the same :)
