### ISSUE TITLE
Suggested blocks based on a problem description

### ISSUE THREAD

**Issue by jschanker** [rachel-fenichel/blockly-samples#2386]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Component

workspace/toolbox: blocks are ranked based on a problem description (AI driven workspace search)

### Problem

Users may need help choosing the blocks to use when trying to solve a problem, particularly if the number of them is large.

### Request

* Developers provide examples of problem descriptions and the block types that would be used (training data).
* Include a text input where users can enter the problem description.
* Include a suggested blocks category in the toolbox where the blocks most likely to be needed are listed first. The developer selects the machine learning algorithm to use for this. One option would be a naive Bayes classifier algorithm to rank blocks by highest probability of being used to solve the problem. Here, the data points would be the problem descriptions and the labels would be the blocks.

### Implementation Questions (in progress)
Ideally, this could be a first-party plugin.
* How should we handle adding an input for which a user could enter a description? Would we define a new function that adds it in the supplied container and then creates a child div which could be passed to `Blockly.inject` (https://github.com/google/blockly/blob/5881ce32c1c1ebccedab7a31e31722093265004f/core/inject.ts#L29-L83) for creating the workspace.
* When there are toolbox categories, we can create an additional category called Recommended blocks which lists them from most likely to be used to least likely. What about when the blocks are listed without categories? 
* Should we provide a variety of machine learning algorithms as part of the plug-in? Can simple ones like the naive Bayes classifier be implemented from scratch (for student practice), or should we be using built-in modules even for these ones?
 

### Additional context

I'm running a class in the fall where the objective for the students is to create a functioning Blockly plugin, so could this be assigned to me so I could have them work on it? And hi again Blockly team, it's been a while. Hope you're all doing well! :-)

**Comment by cpcallen** [comment]
See [discussion in the Blockly forum](https://groups.google.com/g/blockly/c/U25u2macb00).  We'll continue discussion on that thread to keep it in one location.

**Comment by maribethb** [comment]
This could be a cool third-party plugin but not something we'd want to adopt as first-party, so I'm going to close this issue. But it would still be really cool if your class published it!
