### ISSUE TITLE
README is wrong for plugins/field-multilineinput

### ISSUE THREAD

**Issue by MikeJDeck** [rachel-fenichel/blockly-samples#2393]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Component

field-multilineinput plugin

### Description

I think this is just a documentation problem. If you try to create a block with a field as described in the field-multilineinput README, it won't work. You will get a "field not registered" error.

### Diagnosis:
In https://github.com/google/blockly-samples/blob/master/plugins/field-multilineinput/README.md
the JSON sample includes a field with:
` "type": "field_multilineinput",`
 
 But https://github.com/google/blockly-samples/blob/master/plugins/field-multilineinput/src/field_multilineinput.ts
 includes the line:
 `Blockly.fieldRegistry.register('field_multilinetext', FieldMultilineInput);`
 
 And https://github.com/google/blockly-samples/blob/master/plugins/field-multilineinput/test/index.ts
 includes a block definition with the line:
` type: 'field_multilinetext',`

### Reproduction steps

See description.

**Comment by maribethb** [comment]
Thanks for reporting! I've opened a PR and this will be fixed shortly.
