### ISSUE TITLE
Backpack Plugin Update HoverStyle not compatible with multiselect plugin

### ISSUE THREAD

**Issue by changminbark** [rachel-fenichel/blockly-samples#2420]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Component

Workspace backpack plugin

### Description

I was able to create a toFlyoutInfo() method for the multiselectDraggable class to make it compatible with the backpack plugin. However, it does not visually update the backpack when we hover over the backpack because the backpack plugin only checks whether the object being dragged is a BlockSvg. 

![image](https://github.com/user-attachments/assets/fe539631-bbea-4fb9-8b2c-44b5789386d0)

### Reproduction steps

1. 
2. 
3.

**Comment by changminbark** [comment]
I would like to take this on. But to make it more future-proof (by allowing other types of objects that can be added to the backpack and be dragged), what check should I do? Do you think instanceof Blockly.IDraggable or something along those lines would work?

**Comment by BeksOmega** [comment]
Yay thanks for your interest in taking this! I think you should check if it implements `Backpackable`, to indicate that the thing being dragged can be added to the backpack =)
