### ISSUE TITLE
Obtain reference to backpack from outside

### ISSUE THREAD

**Issue by JonasFocke01** [rachel-fenichel/blockly-samples#2432]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Component

plugins-backpack

### Problem

I need to obtain a reference to the backpack in the main workspace from another component. I can get the `workspace` by calling `Blockly.getMainWorkspace()`, but i do not understand from the docs, how i can get to the backpack from there.

### Request

It would be really handy, if it would be possible to just call `Blockly.getMainWorkspace().getBackpack()` or something similar. 

### Alternatives considered

In my case it would be possible, but not very convenient, to refactor my application to create the workspace + backpack in the top level.

### Additional context

Maybe there is something already, but i was unable to find it.

**Comment by cpcallen** [comment]
We might need more information about why you are making this feature request.  [The documentation for the backpack plugin](https://github.com/google/blockly-samples/tree/master/plugins/workspace-backpack) has the developer constructing their own `Backpack` instance.  Why can you not just save that instance and make it available to any other code in your app which needs it?

I'm going to close this for now but we will certainly consider reopening if a sufficiently compelling reason becomes known.
