### ISSUE TITLE
Copy buttons not working in Blockly Developer Tools

### ISSUE THREAD

**Issue by UCYT5040** [rachel-fenichel/blockly-samples#2433]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Component

[Blockly Developer Tools](https://google.github.io/blockly-samples/examples/developer-tools/index.html)

### Description

Clicking on the copy for each generated code block does not work. Occurs on latest Firefox and Chrome.

### Reproduction steps

1. Visit the Blockly Developer Tools page
2. Try to copy the generated code blocks
Happens regardless of whether you change the block

### Screenshots

![image](https://github.com/user-attachments/assets/c8a73c37-5a09-4c32-ba89-8884f4c368af)

**Comment by jenish-thapa** [comment]
Hey @UCYT5040,

I would like to work on this issue. Can you please assign it to me?

**Comment by UCYT5040** [comment]
Hi @jenish-thapa,

I'm sorry but I'm not a maintainer of this repository. You'll have to wait for one of the maintainers to assign you, as I don't have the permission to do so.

**Comment by jenish-thapa** [comment]
Hey @rachel-fenichel, 

I would like to work on this issue. Can you please assign it to me?

**Comment by cpcallen** [comment]
Hi @jenish-thapa.  Thanks for your interest.  Please feel free to try to fix this issue!

**Comment by jenish-thapa** [comment]
Thanks, @cpcallen, for assigning this issue to me! I've just raised a PR for it. Whenever you get a chance, could you please review it? Your feedback would be much appreciated! : )
