### ISSUE TITLE
Workspace search doesn't behave like a browser search box

### ISSUE THREAD

**Issue by riknoll** [rachel-fenichel/blockly-samples#2438]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Component

Workspace search plugin

### Problem

The workspace search plugin is missing two behaviors that are present in pretty much every ctrl+f search box I can think of:

1. When the search box is opened, whatever text is currently in the text input element should be selected
2. Pressing Shift + Enter while moving between search results should move _backwards_ in the search list

Both of these behaviors are present in the search boxes in Chrome, Firefox, Safari, Edge, and VS Code.

### Request

Select the text within the HTMLTextInput when opening the search box and extend the keydown handling such that pressing shift + enter moves backwards.

I am happy to open a PR that does both of these things! I've already implemented it in a somewhat roundabout way in MakeCode:

https://github.com/microsoft/pxt/pull/10070

**Comment by BeksOmega** [comment]
Heya @riknoll, we'd happily accept a PR for this =)
