### ISSUE TITLE
import * as zh-hans from 'blockly/msg/zh-hans'    Expected "from" but found "-"

### ISSUE THREAD

**Issue by RowgerGo** [rachel-fenichel/blockly-samples#2445]
### Check for duplicates

- [ ] I have searched for similar issues before opening a new one.

### Component

<script setup>
/**
 * @license
 * Copyright 2022 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @fileoverview Blockly Vue Component.
 * @author dcoodien@gmail.com (Dylan Coodien)
 */

import {onMounted, ref, shallowRef} from 'vue';
import * as Blockly from 'blockly/core';

import * as zh-hans from 'blockly/msg/zh-hans';

import 'blockly/blocks';

const props = defineProps(['options']);
const blocklyToolbox = ref();
const blocklyDiv = ref(); 
const workspace = shallowRef();

defineExpose({workspace});

onMounted(() => {
  Blockly.setLocale(zhcn);
  const options = props.options || {};
  if (!options.toolbox) {
    options.toolbox = blocklyToolbox.value;
  }
  workspace.value = Blockly.inject(blocklyDiv.value, options);
});
</script>

<template>
  <div>
    <div class="blocklyDiv" ref="blocklyDiv"></div>
    <xml ref="blocklyToolbox" style="display: none">
      <slot></slot>
    </xml>
  </div>
</template>

<style scoped>
.blocklyDiv {
  height: 100%;
  width: 100%;
  text-align: left;
}
</style>

### Description

when I use   `import * as zh-hans from 'blockly/msg/zh-hans'`  ，then   cmd  reports error  
```

```

### Reproduction steps

1. run the project "blockly-vue3"
2. ,and  use  `import * as zh-hans from 'blockly/msg/zh-hans';`
3. 

### Stack trace

```shell
[vite-plugin-static-copy] No items found.
X [ERROR] Expected "from" but found "-"

    node_modules/blockly/msg/zh-hans.mjs:1:9:
      1 │ import zh-hans from './zh-hans.js';
        │          ^
        ╵          from

16:39:18 [vite] error while updating dependencies:
Error: Build failed with 1 error:
node_modules/blockly/msg/zh-hans.mjs:1:9: ERROR: Expected "from" but found "-"
    at failureErrorWithLog (D:\workplace\huashi_project\blockly-samples\examples\blockly-vue3\node_modules\esbuild\lib\main.js:1605:15)
    at D:\workplace\huashi_project\blockly-samples\examples\blockly-vue3\node_modules\esbuild\lib\main.js:1251:28
    at runOnEndCallbacks (D:\workplace\huashi_project\blockly-samples\examples\blockly-vue3\node_modules\esbuild\lib\main.js:1034:63)
    at buildResponseToResult (D:\workplace\huashi_project\blockly-samples\examples\blockly-vue3\node_modules\esbuild\lib\main.js:1249:7)
    at D:\workplace\huashi_project\blockly-samples\examples\blockly-vue3\node_modules\esbuild\lib\main.js:1358:14
    at D:\workplace\huashi_project\blockly-samples\examples\blockly-vue3\node_modules\esbuild\lib\main.js:666:9
    at handleIncomingPacket (D:\workplace\huashi_project\blockly-samples\examples\blockly-vue3\node_modules\esbuild\lib\main.js:763:9)
    at Socket.readFromStdout (D:\workplace\huashi_project\blockly-samples\examples\blockly-vue3\node_modules\esbuild\lib\main.js:632:7)
    at Socket.emit (node:events:517:28)
    at addChunk (node:internal/streams/readable:368:12)
Vite Error, /node_modules/.vite/deps/blockly_msg_zh-hans.js?v=51e1020b optimized info should be defined
17:04:50 [vite] hmr update /src/components/BlocklyComponent.vue
```

### Screenshots

![image](https://github.com/user-attachments/assets/bfd2fc2d-d4ac-48c8-a033-399c7204455d)

**Comment by cpcallen** [comment]
Yeah, no: the identifier you assign to the import must be a valid JavaScript identifier, and unlike in Lisp and Scheme, JS identifiers cannot contain the hyphen character (`-`).  Probably the most idiomatic thing to do would be to use camelCase:

```JS
import * as zhHans from 'blockly/msg/zh-hans'
```

No bug here, just a quirk of how we named the files interacting with JS syntax rules.
