### ISSUE TITLE
Using procedure blocks - typing error

### ISSUE THREAD

**Issue by mariocraft987** [rachel-fenichel/blockly-samples#2460]
### Check for duplicates

- [ ] I have searched for similar issues before opening a new one.

### Component

This isn't really a feature, but I found a typing error.

### Problem

There's a small typing error in [this page](https://developers.google.com/blockly/guides/create-custom-blocks/procedures/using-procedures).

### Request

Change _cusotm_ in [this example](https://developers.google.com/blockly/guides/create-custom-blocks/procedures/using-procedures#adding_them_to_the_toolbox) to _custom_, so other viewers won't get it wrong.

### Alternatives considered

idk, just to change it

### Additional context

![Screenshot 2024-09-05 142927](https://github.com/user-attachments/assets/7a963fc6-5955-40e3-8b16-69c0779cab50)

**Comment by rachel-fenichel** [comment]
Thanks for the report. I've made an internal PR to update the documentation and it should go live in the next week, at which point I will close this.

**Comment by mariocraft987** [comment]
k
