### ISSUE TITLE
Update goog_module renames in codelabs

### ISSUE THREAD

**Issue by BeksOmega** [rachel-fenichel/blockly-samples#884]
**Category**

 - Codelabs

**Describe the bug**

Codelabs still have the old names for things that were renamed..

Eg:
  * getMainWorkspace: [here](https://github.com/google/blockly-samples/blob/1be2b748414ef147c8f7d657fa440442c0ef49a8/examples/getting-started-codelab/complete-code/scripts/main.js#L12), [here](https://github.com/google/blockly-samples/blob/1be2b748414ef147c8f7d657fa440442c0ef49a8/codelabs/getting_started/getting_started.md), [here](https://github.com/google/blockly-samples/blob/1be2b748414ef147c8f7d657fa440442c0ef49a8/codelabs/custom_toolbox/custom_toolbox.md)

**Comment by maribethb** [comment]
Current plan is to save this work as a test for the renamings script when that is ready.
