### ISSUE TITLE
I can't reach the website

### ISSUE THREAD

**Issue by ghost** [rachel-fenichel/blockly-samples#886]
Well, I can't reach the website and then I can't run the app.

**Comment by alschmiedt** [comment]
Hello!

Can you please provide a bit more information on what is not working for you? For example: 

- What website is not working? Is it the [blockly samples](https://google.github.io/blockly-samples/index.html) website? If this is not working, could you please provide information on what you are seeing? 
- What are you trying to run? What steps have you taken to try to run it?

**Comment by alschmiedt** [comment]
I'm going to close this for now, but if you have any more questions or would like more help feel free to reach out on the [forum](https://groups.google.com/g/blockly?pli=1)!
