### ISSUE TITLE
plugins are not transpiling correctly 

### ISSUE THREAD

**Issue by alschmiedt** [rachel-fenichel/blockly-samples#887]
**Category**
Plugins

**Component**
block-test

**Describe the bug**
Our plugins that have IE 11 as one of the entries in browserlist are not actually compatible with IE 11. I originally thought this was just for block-test but it appears to be the same for all the following plugins: 
- content-highlight
- continuous-toolbox
- dev-tools
- field-date
- workspace-search

For example, the block-test [index.js](https://unpkg.com/@blockly/block-test@1.1.5/dist/index.js) we are publishing to npm contains template strings. These should be converted to strings so that it is compatible with ie11. 

When I run `npm run pack`, `dist/index.js` does not contain string literals.

**To Reproduce**
1. Navigate to block-test directory
2. `npm run build`
3. `npm pack`
4. Unpack the .tgz file and open index.js
5. Notice how there are no ` but on [index.js](https://unpkg.com/@blockly/block-test@1.1.5/dist/index.js) there are.

**Expected behavior**
We should have IE11 compatible syntax.

**Screenshots**

**Additional context**

**Comment by maribethb** [comment]
This was fixed back in #1124
