### ISSUE TITLE
TypeError: Class extends value undefined is not a constructor or null

### ISSUE THREAD

**Issue by mrredo-and-josetrindade1** [rachel-fenichel/blockly-samples#890]
**Category**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

-plugin @blockly/continuous-toolbox
idk
it is not loading the import i think?
idk
it prob dint load the constructor 
https://cdn.discordapp.com/attachments/887880548767391754/888475072535339008/unknown.png
[code](https://pastebin.com/em4tQMu8)

**Comment by alschmiedt** [comment]
Hello!

What version of Blockly are you using? I believe the continuous toolbox only works with versions of Blockly greater than or equal to 5.20210325.0.

**Comment by alschmiedt** [comment]
I'm closing this for right now, but feel free to leave a comment on the [forum](https://groups.google.com/g/blockly?pli=1) if you are still having trouble or have more questions. Thanks!
