### ISSUE TITLE
how could i create a backpack that save and load every block that is in it??

### ISSUE THREAD

**Issue by mrredo-and-josetrindade1** [rachel-fenichel/blockly-samples#894]
how could i crrate a backpack that saves and load all the blocks in it?

**Comment by alschmiedt** [comment]
Hello! In the [backpack](https://google.github.io/blockly-samples/plugins/workspace-backpack/test/) plugin you can use `backpack.getContents()` to get all the blocks that are currently in the backpack. You can then use `backpack.setContents(contents)` to add blocks back into the backpack. 

If you have any more questions please ask them on the [forum](https://groups.google.com/g/blockly?pli=1). This allows us to keep our issue list clean and gives other developers a chance to answer your questions! Thanks!
