### ISSUE TITLE
block-extension-tooltip not rendering tooltip correctly

### ISSUE THREAD

**Issue by moniika** [rachel-fenichel/blockly-samples#899]
**Category**
Plugins

**Component**
 block-extension-tooltip

**Describe the bug**
Tooltip not rendering correctly when depending on Blockly beta (post `goog.module` migration).

Expected:
![image](https://user-images.githubusercontent.com/6621618/135675255-2cb2bb43-6234-4656-86b7-8989f9d6e106.png)

Actual:
![image](https://user-images.githubusercontent.com/6621618/135675265-9db335fc-c9e2-4111-8c03-6d44872129c4.png)

**To Reproduce**

1. `npm install blockly@beta`
2. Run `blocky-extension-tooltip` with `npm run start`

**Comment by BeksOmega** [comment]
The monkey patch is touching some [private properties](https://github.com/google/blockly-samples/blob/21e3e227a16a171f95f93b6cc1947514b9764287/plugins/block-extension-tooltip/src/tooltip_monkey_patch.ts#L45) :/

**Comment by maribethb** [comment]
I made this plugin private in #983 so that it doesn't get published again until we sort this out. So when we do fix this, we need to remember to remove that from the package.json. Also, in `src/index.ts` we need to import from `blockly/core` instead of `blockly`.

**Comment by alschmiedt** [comment]
@maribethb can this be closed, or are you waiting until you implement your plan for deprecating?

**Comment by maribethb** [comment]
Remaining work: deprecate and remove the plugin
