### ISSUE TITLE
keyboard_nav plugin uses method deprecated in next Blockly release

### ISSUE THREAD

**Issue by moniika** [rachel-fenichel/blockly-samples#901]
**Category**
Plugins

**Component**
keyboard_nav

**Describe the bug**
Keyboard nav plugin uses deprecated method `Blockly.hideChaff`.

**To Reproduce**

1. Run plugin with `npm run start`
2. Enable Accessibility mode
3. Navigate to toolbox with t
4. Select block from toolbox using w/a/s/d keys to move and enter to select
5. Observe warning in console when toolbox is closed about using depcreated method:
```
Blockly.hideChaff was deprecated on September 2021 and will be deleted on September 2022.
```

**Comment by alschmiedt** [comment]
Fixed in #942.
