### ISSUE TITLE
Use automated releases

### ISSUE THREAD

**Issue by alschmiedt** [rachel-fenichel/blockly-samples#914]
**Category**
Release

**Is your feature request related to a problem? Please describe.**
- Creating manual release notes is a pain
- [Problems with lerna and our package-locks](https://github.com/google/blockly-samples/issues/632) 
- Manual releasing every week is a large pain point.

**Describe the solution you'd like**
Use [release please](https://github.com/googleapis/release-please) to help manage our releases. 

This would include: 
- Setting up release please to create a Release PR that can get merged into master. 
- Adding a [github action](https://github.com/googleapis/release-please) to automate releasing to npm when we merge the release PR into master.
- Looking into the [manifest releaser](https://github.com/googleapis/release-please/blob/main/docs/manifest-releaser.md#manifest-driven-release-please) to see if it fits our use case.
- Internally document anything the team should know when using release please. For example, information on how to only publish a single plugin and how to force publish a plugin.

**Describe alternatives you've considered**
We currently use lerna for publishing. We have run into problems with it in the past and think release please will be a better alternative.

**Additional context**

**Comment by maribethb** [comment]
We decided not to use release-please for reasons detailed in an internal doc, but Beka and I have been working on using GitHub Actions to release using our own scripts

**Comment by maribethb** [comment]
Fixed! https://github.com/google/blockly-samples/actions/runs/2625812756 First automated release!
