### ISSUE TITLE
Update eslint-related packages

### ISSUE THREAD

**Issue by maribethb** [rachel-fenichel/blockly-samples#917]
**Category**

- Tooling

**Component**

eslint-config

**Describe the bug**

* blockly-samples/plugins/eslint-config uses eslint v7
* It also uses `@typescript-eslint/parser`, `@typescript-eslint/eslint-plugin`, and `jsdoc-eslint-plugin` versions that are several years old and are not compatible with eslint v7
* This problem is exposed if you have to use the `--legacy-peer-deps` flag for any reason (e.g. install blockly beta with a plugin that hasn't been updated yet) where you get an error message about eslint not being installed.

**To Reproduce**

Use the `--legacy-peer-deps` flag and eslint will not be installed. 

**Additional context**

See https://groups.google.com/g/blockly/c/MpMkF-hgloA for initial context.

Currently, I've published beta versions of eslint-config (2.1.5-beta.0), dev-scripts (1.2.11-beta.0), and dev-tools (2.6.2-beta.0) that use the newest version of each of the dependencies listed above. However there is more additional work. Over time some of the rules have changed, been added/removed/renamed/etc so there are new lint errors and warnings.

- [ ] Investigate and fix missing rule names
- [ ] Resolve the additional lint errors/warnings (either by fixing actual style problems, or updating/disabling the new rules)
- [x] Release non-beta versions of eslint-config, dev-scripts, and dev-tools that use the new versions

While dev-tools has some changes that should remain part of the beta release (e.g. all changes related to the q4 release of Blockly) this problem is unrelated to the core beta release and can be fixed ahead of time.

**Comment by maribethb** [comment]
Current status: New versions of the eslint-related packages were used in order to solve some peerDependency issues, but we didn't sort out the newly introduced warnings. So this still needs some work to decide what to do with those warnings. I would have fixed errors but it looks like after the update there were only warnings and no errors.

Run `npm run lint` in samples to see warnings. I believe other than in nominal-connection-checker, previously the only warnings were about TODO comments and now there are more. Ideally we would have no lint messages

**Comment by BeksOmega** [comment]
Nominal connection checker can be deleted whenever. I talked w/ Rachel and we decided it would be better to pull it into a separate repo. I can put up a PR for removing it if you want =)

**Comment by maribethb** [comment]
Remaining lint errors/warnings were fixed in q1 2022.
