### ISSUE TITLE
Plugins workspace search

### ISSUE THREAD

**Issue by aktoak** [rachel-fenichel/blockly-samples#951]
- Plugins

**Component**

WorkspaceSearch Plugin

**Describe the bug**

WorkspaceSearch won't initialize correctly using an RTL workspace.
this bug also appears in google demo
[@blockly/workspaceSearch](https://google.github.io/blockly-samples/plugins/workspace-search/test/index#theme=dark)
when trying to change the workspace from LTR to RTL the page is stuck and unresponsive.

**Comment by gonfunko** [comment]
Thanks for reporting this! I was able to reproduce the problem and have sent a PR with a fix.
