### ISSUE TITLE
Update and consolidate demos into samples

### ISSUE THREAD

**Issue by alschmiedt** [rachel-fenichel/blockly-samples#968]
**Category**
Examples

**Component**
All examples

**Is your feature request related to a problem? Please describe.**
We currently have quite a few examples that we have moved over to samples but also left in [core](https://github.com/google/blockly/tree/master/demos). This is pretty annoying when we have to fix a bug for one of them and have to duplicate the bug fix.

**Describe the solution you'd like**

- [x] Remove duplicate examples/demos.
- [x] Add redirects to the [demos page](https://blockly-demo.appspot.com/static/demos/index.html) so that they redirect to the appropriate page on samples.
- [ ] Remove any broken/not useful demos/examples.
- [ ] Finish migrating over any examples/demos to samples.

**Describe alternatives you've considered**

**Additional context**

**Comment by rachel-fenichel** [comment]
See also https://github.com/google/blockly/issues/6065

**Comment by maribethb** [comment]
I think we can close this as the only remaining demos are listed in #6065.
